### ISSUE TITLE
Crash beim editieren einer Transaktion

### ISSUE THREAD

**Issue by Jabro** [buchen/portfolio#1011]
Hallo,

zunaechst vielen Dank fuer die tolle Software!

Ich bin auf folgendes Problem gestossen:
wenn ich versuche einen Aktienuebertrag zu editieren, erhalte ich eine Fehlermeldung mit folgendem Strack-Trace:
```

Wed Jul 25 11:10:38 CEST 2018
Internal Error

org.eclipse.e4.core.di.InjectionException: java.lang.IllegalArgumentException
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:65)
	at org.eclipse.e4.core.internal.di.InjectorImpl.processAnnotated(InjectorImpl.java:1005)
	at org.eclipse.e4.core.internal.di.InjectorImpl.internalInject(InjectorImpl.java:137)
	at org.eclipse.e4.core.internal.di.InjectorImpl.internalMake(InjectorImpl.java:412)
	at org.eclipse.e4.core.internal.di.InjectorImpl.make(InjectorImpl.java:345)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.make(ContextInjectionFactory.java:214)
	at name.abuchen.portfolio.ui.AbstractFinanceView.make(AbstractFinanceView.java:197)
	at name.abuchen.portfolio.ui.dialogs.transactions.OpenDialogAction.run(OpenDialogAction.java:81)
	at org.eclipse.jface.action.Action.runWithEvent(Action.java:473)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:565)
	at org.eclipse.jface.action.ActionContributionItem.lambda$4(ActionContributionItem.java:397)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:86)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5686)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1370)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4940)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4518)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1170)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1059)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:153)
	at org.eclipse.e4.ui.internal.workbench.swt.E4Application.start(E4Application.java:162)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:656)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:592)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1498)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1471)
Caused by: java.lang.IllegalArgumentException
	at name.abuchen.portfolio.ui.dialogs.transactions.SecurityDeliveryModel.<init>(SecurityDeliveryModel.java:24)
	at name.abuchen.portfolio.ui.dialogs.transactions.SecurityTransactionDialog.createModel(SecurityTransactionDialog.java:61)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:55)
	... 33 more
```

Der Uebertrag hat moeglicherweise keinen Kaufkurs, da er in der Performanceansicht als 100% Gewinnn gezeigt wird.

**Comment by buchen** [comment]
> Ich bin auf folgendes Problem gestossen:
> wenn ich versuche einen Aktienuebertrag zu editieren, erhalte ich eine Fehlermeldung mit folgendem Strack-Trace:

Ich kann das Problem gerade nicht nachvollziehen. Die Fehlermeldung besagt, dass der Typ der Buchung nicht zu dem Modell passen würde. Sehr komisch.

Kann ich mal einen Blick in Deine XML Datei werfen? Lösche einfach alle anderen Umsätze/Wertpapiere etc. raus und schicke sie mir an *portfolio dot performance dot help at gmail dot com*.
