### ISSUE TITLE
Running Portfolio Performance in IDE

### ISSUE THREAD

**Issue by HaidStefan** [buchen/portfolio#1031]
Hallo Leute,

ich habe gerade versucht die IDE aufzusetzen, habe jedoch noch ein Problem beim Ausführen des UI-Launchers. Die Tests in "name.abuchen.portfolio.tests.lauch" funktionieren erfolgreich. Bei den anderen erhalte ich ca. diese Fehlermeldung:

```
WARNING: Using incubator modules: jdk.incubator.httpclient
!SESSION 2018-09-21 22:22:34.683 -----------------------------------------------
eclipse.buildId=unknown
java.version=9
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=de_DE
Framework arguments:  -product name.abuchen.portfolio.bootstrap.product
Command-line arguments:  -product name.abuchen.portfolio.bootstrap.product -data C:\Users\Equintox\eclipse-workspace/../runtime-name.abuchen.portfolio.product -dev file:C:/Users/Equintox/eclipse-workspace/.metadata/.plugins/org.eclipse.pde.core/Portfolio Performance/dev.properties -os win32 -ws win32 -arch x86_64 -consoleLog

!ENTRY org.eclipse.osgi 4 0 2018-09-21 22:22:35.797
!MESSAGE Application error
!STACK 1
java.lang.NoClassDefFoundError: org/eclipse/swt/widgets/Display
	at org.eclipse.e4.ui.internal.workbench.swt.E4Application.start(E4Application.java:144)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:656)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:592)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1498)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1471)
Caused by: java.lang.ClassNotFoundException: org.eclipse.swt.widgets.Display cannot be found by org.eclipse.e4.ui.workbench.swt_0.14.200.v20180516-2019
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:508)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:419)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:411)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:150)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	... 14 more
An error has occurred. See the log file
C:\Users\Equintox\eclipse-workspace\.metadata\.plugins\org.eclipse.pde.core\Portfolio Performance\1537561354869.log.
```

Ich habe alles so ausgeführt wie in der Anleitung beschrieben. Hat jemand eine Idee was das Problem sein könnte? 

LG
Stefan

**Comment by Ragas13** [comment]
Ich hatte die letzten Tage ein ähnliches Problem, bei mir waren noch unter "Run > Run Confirmation > Plugins" notwendige Plugins einzubinden. Siehe den gleichnamigen Button.

**Comment by HaidStefan** [comment]
Vielen Dank @Ragas13 hat so funktioniert.
