### ISSUE TITLE
ClassNotFoundException: org.eclipse.swt.widgets.Display - PP lässt sich aus Eclipse 2018-09 nicht starten

### ISSUE THREAD

**Issue by yetipenguin** [buchen/portfolio#1107]
Ich kann PP auf dem aktuellen Master mit Eclipse 2018-09 nicht mittels Launch-Configuration starten.
Es erscheint die Fehlermeldung weiter unten.

Eclipse IDE for RCP and RAP Developers

Version: 2018-09 (4.9.0)
Build id: 20180917-1800

Kubuntu 14.04.5 LTS

java -version
openjdk version "1.8.0_202"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_202-b08)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.202-b08, mixed mode)

!SESSION 2019-02-01 15:58:06.782 -----------------------------------------------
eclipse.buildId=unknown
java.version=1.8.0_202
java.vendor=AdoptOpenJdk
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=de_DE
Framework arguments:  -product name.abuchen.portfolio.bootstrap.product
Command-line arguments:  -product name.abuchen.portfolio.bootstrap.product -data /home/user/eclipse-workspace-portfolio/../runtime-name.abuchen.portfolio.product -dev file:/home/user/eclipse-workspace-portfolio/.metadata/.plugins/org.eclipse.pde.core/Portfolio Performance/dev.properties -os linux -ws gtk -arch x86_64 -consoleLog

!ENTRY org.eclipse.osgi 4 0 2019-02-01 15:58:07.691
!MESSAGE Application error
!STACK 1
java.lang.NoClassDefFoundError: org/eclipse/swt/widgets/Display
	at org.eclipse.e4.ui.internal.workbench.swt.E4Application.start(E4Application.java:147)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:199)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:391)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:246)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:595)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1501)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1474)
Caused by: java.lang.ClassNotFoundException: org.eclipse.swt.widgets.Display cannot be found by org.eclipse.e4.ui.workbench.swt_0.14.300.v20180906-1121
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:511)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:422)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:414)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:153)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 14 more

**Comment by buchen** [comment]
> Ich kann PP auf dem aktuellen Master mit Eclipse 2018-09 nicht mittels Launch-Configuration starten.

Die Fehlermeldung ist etwas komisch weil meinem Verständnis nach eigentlich schon vorher der Check schief gehen sollte...

Kannst Du mal in der Launch Konfiguration nachschauen ob das SWT Bundle für Deine Platform ein Häkchen hat? Bei mir "sitzt" das bei macosx.cocoa.

<img width="859" alt="bildschirmfoto 2019-02-04 um 09 14 08" src="https://user-images.githubusercontent.com/587976/52196738-41a65480-285d-11e9-8521-3cf5f1fa92d6.png">

**Comment by yetipenguin** [comment]
Ich sehe da nur de.engehausen. ... und org.swtchart. ... Die Target-Platform kompiliert ja schon nicht richtig, siehe https://github.com/buchen/portfolio/issues/1071#issuecomment-459764201 - jetzt wo ich darüber nachdenke ergibt das natürlich Sinn, dass ich dann nicht starten kann ... 🤦‍♂️
Mit Java 8 findet Maven keine Tests, aber das schau ich mir mal wann anders an.
