### ISSUE TITLE
Performance-Probleme - zeitlicher Natur ;-) - mit PP

### ISSUE THREAD

**Issue by anroth** [buchen/portfolio#1116]
Hallo,

ich habe heute Abend auf 0.38.1 geupdated. Jetzt habe ich Performance Probleme, zeitlicher Natur. Für die monetäre Performance Flaute im Dezember kann ja das Tool nix ;-).
Vor dem Update lief alles wieder klasse, ich konnte sogar meine alten Watchlisten mit Version 0.38 löschen. Super, danke nochmal dafür :-).

So jetzt zur detaillierten Beschreibung:
Ich habe also das Update eingespielt. Der autom. Neustart des Tools schlug fehl, wie schon seit ein paar Releases, weil ich laut der Meldung noch ein Tab offen hatte. Offen hatte ich natürlich meine PP-Datei und den "Willkommen"-Tab.
Wie gewöhnlich dann das Programm geschlossen und manuell neu gestartet.

Beim ersten mal Laden der verschlüsselten Datei konnte PP die Datei nicht öffnen.
Beim zweiten Mal ging's dann, hat den Performance-Screen aber sehr langsam aufgebaut.

Laut Task-Manager genehmigt sich PP nach dem Laden meiner Datei fast 1 GB RAM (unter Win 10)
Es arbeitet auch sehr träge. teilweise kommt es zu Fehlermeldungen.

Viele Grüße,
Andrea

Eine der Fehlermeldungen, die genau 25 mal exakt so (mit Notepadd++ Compare, Verglichen) im Fehlerprotokoll steht:

Tue Feb 12 22:14:46 CET 2019
Internal Error

org.eclipse.swt.SWTException: Widget is disposed

	at org.eclipse.swt.SWT.error(SWT.java:4595)

	at org.eclipse.swt.SWT.error(SWT.java:4510)

	at org.eclipse.swt.SWT.error(SWT.java:4481)

	at org.eclipse.swt.widgets.Widget.error(Widget.java:451)

	at org.eclipse.swt.widgets.Widget.checkWidget(Widget.java:350)

	at org.eclipse.swt.widgets.Control.getParent(Control.java:1513)

	at name.abuchen.portfolio.ui.views.dashboard.DashboardView.updateScrolledCompositeMinSize(DashboardView.java:343)

	at name.abuchen.portfolio.ui.views.dashboard.DashboardView.access$1(DashboardView.java:341)

	at name.abuchen.portfolio.ui.views.dashboard.DashboardView$1.lambda$0(DashboardView.java:591)

	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)

	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185)

	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:3933)

	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3564)

	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1173)

	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)

	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1062)

	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)

	at org.eclipse.e4.ui.internal.workbench.swt.E4Application.start(E4Application.java:165)

	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:199)

	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)

	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)

	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:391)

	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:246)

	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)

	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)

	at java.lang.reflect.Method.invoke(Unknown Source)

	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)

	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:595)

	at org.eclipse.equinox.launcher.Main.run(Main.java:1501)

**Comment by buchen** [comment]
> Eine der Fehlermeldungen, die genau 25 mal exakt so

Ja, in der Tat habe ich eine vertikale Scrollbar in den Dashboards eingebaut. In dem Zusammenhang tritt der Fehler auf. 😬 

Die konkrete Fehlermeldung kann ich mir aber nur erklären, wenn man das Dashboard wechselt *bevor* die Daten im Hintergrund fertig gerechnet sind. Dann existiert das UI Element (Widget) nämlich nicht mehr und kann auch nicht mit Daten versorgt werden. Das kann ich abfangen.

Allerdings ist es schon komisch, dass der Fehler dann 25 (!) mal auftritt. Hast Du Dashboards gewechselt? wieviele Elemente hast Du so auf einem Dashboard?

> Beim zweiten Mal ging's dann, hat den Performance-Screen aber sehr langsam aufgebaut.

Das kann schon sein, wenn viele Exceptions geworfen werden.

Ich baue mal einen Fix - mal sehen ob das hilft.

**Comment by buchen** [comment]
@anroth Teste doch mal mit einer dieser Versionen (64bit und 32bit)

https://www.dropbox.com/s/7j1qaxdenhad2zd/PortfolioPerformance-distro-0.38.2-SNAPSHOT-win32.win32.x86_64.zip?dl=0
https://www.dropbox.com/s/aehhbcr15aetmdb/PortfolioPerformance-distro-0.38.2-SNAPSHOT-win32.win32.x86.zip?dl=0

**Comment by anroth** [comment]
@buchen, ich nutze die 64-Bit-Version.
Erster Start -> scheint wichtig: verkleinert, also nicht im "Vollbild" auf meinem 16:10 / 1920x1200 Pixel-Bildschirm:


![grafik](https://user-images.githubusercontent.com/11397152/52739593-8ce50380-2fd1-11e9-9ee3-3391e69e5df3.png)

Wed Feb 13 20:50:02 CET 2019
Internal Error

java.lang.IllegalArgumentException

	at name.abuchen.portfolio.ui.editor.ClientInput.setClient(ClientInput.java:435)

	at name.abuchen.portfolio.ui.editor.LoadClientThread.lambda$0(LoadClientThread.java:36)

	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)

	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185)

	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:3933)

	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3564)

	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1173)

	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)

	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1062)

	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)

	at org.eclipse.e4.ui.internal.workbench.swt.E4Application.start(E4Application.java:165)

	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:199)

	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)

	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)

	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:391)

	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:246)

	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

	at java.lang.reflect.Method.invoke(Method.java:498)

	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)

	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:595)

	at org.eclipse.equinox.launcher.Main.run(Main.java:1501)


Dann blieb es auf dieser Darstellung. Es wurden scheinbar Daten aktualisiert.
Bei den Fehlermeldungen habe ich gesehen, wie für Yahoo immer wieder einträge dazugeschrieben wurden und ich wurde beim schließen gefragt, ob ich Änderungen speichern möchte. Dass habe ich verneint.

![grafik](https://user-images.githubusercontent.com/11397152/52739710-c453b000-2fd1-11e9-994e-709f17e6eb5d.png)



Normalerweise soll es sich in der Performance-Ansicht öffnen.
Beim zweiten Versuch, nun maximiert auf dem ganzen Bildschirm, hat es sich in der Vermögensaufstellung geöffnet und die Ansicht war in Ordnung.

Die Ansichten Diagramm und Bestände haben auch funktioniert.
Der Speicherverbrauch liegt bei ca. 1 GB. Scheint mir sehr viel zu sein, aber ich habe darauf bei PP noch nie geachtet, muss ich zugeben.

Nun maximiert funktioniert auch die Ansicht "Performance".
Das Fenster verkleinern und wieder auf volle Größe maximieren hat auch funktioniert.

Aber beim zweiten öffnen kam dieser Fehler im Protokoll:
Wed Feb 13 20:50:02 CET 2019
Internal Error

java.lang.IllegalArgumentException

	at name.abuchen.portfolio.ui.editor.ClientInput.setClient(ClientInput.java:435)

	at name.abuchen.portfolio.ui.editor.LoadClientThread.lambda$0(LoadClientThread.java:36)

	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)

	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185)

	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:3933)

	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3564)

	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1173)

	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)

	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1062)

	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)

	at org.eclipse.e4.ui.internal.workbench.swt.E4Application.start(E4Application.java:165)

	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:199)

	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)

	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)

	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:391)

	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:246)

	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

	at java.lang.reflect.Method.invoke(Method.java:498)

	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)

	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:595)

	at org.eclipse.equinox.launcher.Main.run(Main.java:1501)



> Die konkrete Fehlermeldung kann ich mir aber nur erklären, wenn man das Dashboard wechselt _bevor_ die Daten im Hintergrund fertig gerechnet sind.

Es kann gut sein, dass ich gestern zu ungeduldig war und nicht gewartet habe, bis die Daten da waren. Das dauerte sicher über 10 Sekunden und mein Rechner hatte sonst nix zu tun.

Wechsele ich in dieser neuen Version die zwei Dashboards, die ich eingerichtet habe schnell hintereinander habe ich keinen Fehler registriert. Und keinen neuen im Fehlerprotokoll gesehen.


> Allerdings ist es schon komisch, dass der Fehler dann 25 (!) mal auftritt. Hast Du Dashboards gewechselt? wieviele Elemente hast Du so auf einem Dashboard?

Wahrscheinlich habe ich gestern dabei die Dashboards gewechselt. Ich versuch es nachher nochmal mit der alten Version. Was mit der oben verlinkten Version passiert habe ich ja gerade oben beschrieben.

Ich habe zurzeit einen 5 Jahreszeitraum ausgewählt und dabei zu den Standard-Performance-Zahlen noch das "Monatsrenditen in der Heatmap", die "Berechnung (weiß nicht mehr, ob die auf der Standard-Ansicht schon dabei war) und das Performance-Diagramm eingeblendet. Zudem noch ca. 5 verschiedene Performance-Kennzahlen, wie gesagt zusätzlich zu allem, was auf dem Standard dabei war.

**Comment by anroth** [comment]
Update zum Fehlverhalten in der Version 0.38.1.

> Hast Du Dashboards gewechselt?
Was ich unter Dashboard verstanden habe war: Eine neue, laut Tooltip, "Ansicht" im Abschnitt "Performance". Wenn ich diese Ansicht wechsle, während ich die Daten noch nicht geladen sind ist noch alles gut.
Wenn ich aber von "Performance" zu "Diagramm" oder wo auch immer wechsle, hast du recht, dann kommt da der Fehler.


Wed Feb 13 21:18:29 CET 2019
Internal Error

org.eclipse.swt.SWTException: Widget is disposed

	at org.eclipse.swt.SWT.error(SWT.java:4595)

	at org.eclipse.swt.SWT.error(SWT.java:4510)

	at org.eclipse.swt.SWT.error(SWT.java:4481)

	at org.eclipse.swt.widgets.Widget.error(Widget.java:451)

	at org.eclipse.swt.widgets.Widget.checkWidget(Widget.java:350)

	at org.eclipse.swt.widgets.Control.getParent(Control.java:1513)

	at name.abuchen.portfolio.ui.views.dashboard.DashboardView.updateScrolledCompositeMinSize(DashboardView.java:343)

	at name.abuchen.portfolio.ui.views.dashboard.DashboardView.access$1(DashboardView.java:341)

	at name.abuchen.portfolio.ui.views.dashboard.DashboardView$1.lambda$0(DashboardView.java:591)

	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)

	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185)

	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:3933)

	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3564)

	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1173)

	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)

	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1062)

	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)

	at org.eclipse.e4.ui.internal.workbench.swt.E4Application.start(E4Application.java:165)

	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:199)

	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)

	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)

	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:391)

	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:246)

	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)

	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)

	at java.lang.reflect.Method.invoke(Unknown Source)

	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)

	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:595)

	at org.eclipse.equinox.launcher.Main.run(Main.java:1501)

**Comment by buchen** [comment]
> Dann blieb es auf dieser Darstellung.

Verstehe ich das jetzt richtig: Du startest PP, es wird die Datei geladen, es kommt die IllegalArgumentException, im Hintergrund werden Kurse geladen, aber Du siehst nur den "Lade-Bildschirm mit Fortschrittsbalken"? Das Problem besteht also noch nach dem zweiten Starten, richtig?

Die IllegalArgumentException kann ich mir nicht erklären. Diesen Fehler werfe ich, wenn *eine* Datei mehrfach in das GUI geladen wird. Aber wie kann das sein? Da muss ich mir meinen Code noch mal genau anschauen.

Könntest Du mal probieren, dass workspace Verzeichnis zu löschen und dann PP zu starten:

unter Windows: $LOCALAPPDATA$/PortfolioPerformance/workspace wobei $LOCALAPPDATA$ überlicherweise nach C:\Users\{username}\AppData\Local zeigt.

**Comment by anroth** [comment]
Alles was ich in diesem Post schreibe bezieht sich auf: 0.38.2.201902130927

Hierzu ein klares Ja.
>  Verstehe ich das jetzt richtig: Du startest PP, es wird die Datei geladen, es kommt die IllegalArgumentException, im Hintergrund werden Kurse geladen, aber Du siehst nur den "Lade-Bildschirm mit Fortschrittsbalken"? 

Ich weiß nicht, ob ich wiederrum die Frage korrekt verstehe.
> Das Problem besteht also noch nach dem zweiten Starten, richtig?

Zur Erklärung meines obigen Posts:
Von meinem Text im zweiten Post "Erster Start -> scheint wichtig:" bis einschließlich zum Ladebalken, der dann unverändert so stehen geblieben ist, ist es ein Ladevorgang. Als der Balken stehen geblieben ist habe ich eine Weile (20-30 Sekunden) gewartet. Oben in der Beschreibung vom Tab "mein.portfolio" siehst du auch wie in dem Screenshot der Stern vor dem Namen steht "*mein.portfolio" steht. D.h. daran habe ich gemerkt, dass PP etwas in der Datei aktualisiert, es mir aber nichts anzeigt.
Dann habe ich PP geschlossen und die Frage kam auf, ob ich die Änderungen speichern möchte. Das habe ich nicht getan. Ich kann das Verhalten allerdings derzeit nicht wiederholen.
=> Also wäre die Antwort wohl: Nein, das Problem besteht derzeit nicht nach einem zweiten Start.

Beim zweiten Laden, wie ich es in meinem zweiten Post beschreibe, habe ich das PP-Fenster vor Eingabe meines Kennworts maximiert und da hat es dann geklappt. 
Das liest du ab "Normalerweise soll es sich in der Performance-Ansicht öffnen.
Beim zweiten Versuch, nun maximiert ..."


Beim ersten Laden dachte ich lag es am verkleinerten Fenster, da du erwähnt hattest, dass es am Scroll-Balken liegen könnte und ich habe es gar kein zweites Mal versucht.

Ich habe es jetzt vielfach ( >4x ) versucht, auch mit der alten Version 0.38.1 und es trat nicht mehr auf. Dabei habe ich darauf geachtet, dass möglichst alles so ist wie vorhin. Also auch der Zeitraum von 5 Jahren war so eingestellt.

**Comment by buchen** [comment]
Okay, der Fix kommt mit der nächsten Version - Du kannst die aktuelle Installation einfach weiter nutzen.

> Der Speicherverbrauch liegt bei ca. 1 GB.

> Das dauerte sicher über 10 Sekunden

> Es arbeitet auch sehr träge.

Ich vermute das ist immer noch der Fall, oder?
Um zu verstehen wo es da an der Performance hapert, würde mich Deine Datei interessieren.
Wenn es Dir nichts ausmacht, könntest Du die Datei an *portfolio dot performance dot help at gmail dot com* schicken. Du kannst einige Konten/Depots/Buchungen löschen aber am besten nur so dass man die Probleme immer noch sieht.

**Comment by anroth** [comment]
Super. Danke für den Fix.

Die Datei würde ich derzeit nur ungern rausgeben.
An der Verschlüsselung kann es nicht liegen, nehme ich an.

Was mir in Fehlerprotokoll noch um die Ohren gehauen wird ist:
Und das grob überschlagen so um die 100x.



Der erste Fehler
---------------------
Tue Feb 19 16:27:39 CET 2019
Warnung: Veränderung ohne Kapital: 16,84 am 29.03.2018

java.lang.RuntimeException: Warnung: Veränderung ohne Kapital: 16,84 am 29.03.2018

	at name.abuchen.portfolio.snapshot.ClientIndex.calculate(ClientIndex.java:85)

	at name.abuchen.portfolio.snapshot.PerformanceIndex.forClient(PerformanceIndex.java:73)

	at name.abuchen.portfolio.snapshot.PerformanceIndex.forPortfolio(PerformanceIndex.java:88)

	at name.abuchen.portfolio.ui.views.dataseries.DataSeriesCache.calculate(DataSeriesCache.java:132)

	at name.abuchen.portfolio.ui.views.dataseries.DataSeriesCache.lookup(DataSeriesCache.java:101)

	at name.abuchen.portfolio.ui.views.dashboard.DashboardData.calculate(DashboardData.java:185)

	at name.abuchen.portfolio.ui.views.dashboard.WidgetFactory.lambda$2(WidgetFactory.java:40)

	at name.abuchen.portfolio.ui.views.dashboard.IndicatorWidget.lambda$1(IndicatorWidget.java:130)

	at name.abuchen.portfolio.ui.views.dashboard.DashboardView$1.run(DashboardView.java:571)

	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)


--------------------------------------------------------------------------





Ein zweiter, für mich auf den den 
--------------------------------------------------------------------------

Tue Feb 19 16:27:34 CET 2019
Warnung: Veränderung ohne Kapital: 15,51 am 09.07.2018

java.lang.RuntimeException: Warnung: Veränderung ohne Kapital: 15,51 am 09.07.2018

	at name.abuchen.portfolio.snapshot.ClientIndex.calculate(ClientIndex.java:85)

	at name.abuchen.portfolio.snapshot.PerformanceIndex.forClient(PerformanceIndex.java:73)

	at name.abuchen.portfolio.snapshot.PerformanceIndex.forPortfolio(PerformanceIndex.java:88)

	at name.abuchen.portfolio.ui.views.dataseries.DataSeriesCache.calculate(DataSeriesCache.java:132)

	at name.abuchen.portfolio.ui.views.dataseries.DataSeriesCache.lookup(DataSeriesCache.java:101)

	at name.abuchen.portfolio.ui.views.dashboard.DashboardData.calculate(DashboardData.java:185)

	at name.abuchen.portfolio.ui.views.dashboard.WidgetFactory.lambda$2(WidgetFactory.java:40)

	at name.abuchen.portfolio.ui.views.dashboard.IndicatorWidget.lambda$1(IndicatorWidget.java:130)

	at name.abuchen.portfolio.ui.views.dashboard.DashboardView$1.run(DashboardView.java:571)

	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

**Comment by buchen** [comment]
> Veränderung ohne Kapital: 16,84 am 29.03.2018
> Veränderung ohne Kapital: 15,51 am 09.07.2018

Das sind Warnung die während der Rechnung ausgegeben werden. Die prozentuale Veränderung wird mit ```aktuelle Bewertung + Abgänge / Bewertung von gestern + Zugänge``` berechnet (Hintergrund: Annahme ist das neues Kapital am Anfang des Tages zur Verfügung steht, Kapitalabflüsse erst am Ende des Tages). Der Problem ist immer wenn der Teiler Null (0) - was soll PP dann rechnen.

Schau mal was für Buchungen es an diesem Tag gibt. Meist sind das Dividenden, die nach dem Verkauf des Wertpapiers noch gut geschrieben werden. Dann ist man mit 0 Euro Investiert, aber bekommt noch Dividende.

Das ist die ganze Diskussion um den Ex-Tag der Dividenden (hast Du vielleicht im Forum gesehen).

Ich mache das in diesem Fall meist so, dass ich das Datum der Dividende anpasse. Aber in der Tat sollte ich die Anzahl solcher Fehlermeldungen mal reduzieren.

**Comment by anroth** [comment]
Nachdem die Datei entschlüsselt ist fängt es mit fast 800 Operationen an. Wobei diese ziemlich schnell abgearbeitet sind. Da kenn ich noch andere Zeiten, wo das auch mal sehr langsam war.

Ich habe im Dashboard "Alle Wertpapiere" ca. 300 - 400 Einträge.

Sind deiner Meinung nach dies zu viele Operationen bzw. Einträge? Sollte ich hier mal ausmisten?

Ich bin seit ca. Anfang 2015 mit von der Partie, was die Nutzung von PP angeht. Welche Version damals auch immer aktuell war :-).

**Comment by buchen** [comment]
> Ich habe im Dashboard "Alle Wertpapiere" ca. 300 - 400 Einträge.
> Sind deiner Meinung nach dies zu viele Operationen bzw. Einträge? Sollte ich hier mal ausmisten?

Meine eigenen Date ist 6 MB groß (unkomprimiert). Ich habe aber auch schon eine Datei Deiner Größenordnung gesehen.

Mir ging es auch eher darum schöne Beispiele zu haben PP weiter zu optimieren. Ich weiß z.B. das ich in den Tabellen noch einige Berechnungen im UI Thread mache und dann das UI "einfrieren" kann.

Bei den Dashboards habe ich jetzt angefangen diese Berechnungen in den Hintergrund zu verlegen. Das sieht man, weil für einen Moment die Felder weiß sind bis die Werte berechnet wurden. In Deinem Fall habe ich zwischen den Zeilen gelesen, dass das doch trotzdem noch ziemlich lange dauert - sonst hättest Du nicht so schnell das Dashboard gewechselt. Ich kann aber auch verstehen, dass die Daten/Informationen vertraulich sind.

Beim nächsten Problem einfach ähnlich genau einen Issue hier aufmachen 😄

**Comment by anroth** [comment]
Ein kurzer Hinweis noch zu diesem Kommentar:
> Schau mal was für Buchungen es an diesem Tag gibt. Meist sind das Dividenden, die nach dem Verkauf des Wertpapiers noch gut geschrieben werden. Dann ist man mit 0 Euro Investiert, aber bekommt noch Dividende.

Es handelt sich auch um Dividenden, die gezahlt wurden als ich die Aktie noch gehalten habe.
Einen Kurs sehe ich für den angegeben Tag auch im Chart in PP.
