### ISSUE TITLE
NPE in AxisTickMarks.drawYTickMarks() in den Klassifizierungsansichten

### ISSUE THREAD

**Issue by yetipenguin** [buchen/portfolio#1129]
Version: 0.39.0 (Feb. 2019)
Platform: linux, x86_64

Reproduktionsschritte:
1. Kommer-Beispieldatei öffnen
2. Klick auf "Anlagekategorien" oder "Asset Allocation"

Erwartetes Verhalten:
Die Ansicht öffnet sich ohne Fehlermeldung.

Beobachtetes Verhalten:
Es wird eine NPE angezeigt:

`Sun Mar 03 01:06:48 CET 2019
Internal Error

java.lang.NullPointerException
	at org.swtchart.internal.axis.AxisTickMarks.drawYTickMarks(AxisTickMarks.java:305)
	at org.swtchart.internal.axis.AxisTickMarks.paintControl(AxisTickMarks.java:184)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:234)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5797)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1374)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1400)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1383)
	at org.eclipse.swt.widgets.Control.gtk_draw(Control.java:3698)
	at org.eclipse.swt.widgets.Composite.gtk_draw(Composite.java:435)
	at org.eclipse.swt.widgets.Widget.windowProc(Widget.java:1952)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:6524)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:6014)
	at org.eclipse.swt.internal.gtk.GTK._gtk_main_do_event(Native Method)
	at org.eclipse.swt.internal.gtk.GTK.gtk_main_do_event(GTK.java:4118)
	at org.eclipse.swt.widgets.Display.eventProc(Display.java:1414)
	at org.eclipse.swt.internal.gtk.GDK._gdk_window_process_updates(Native Method)
	at org.eclipse.swt.internal.gtk.GDK.gdk_window_process_updates(GDK.java:2712)
	at org.eclipse.swt.widgets.Control.update(Control.java:6461)
	at org.eclipse.swt.widgets.Control.update(Control.java:6447)
	at org.eclipse.jface.layout.AbstractColumnLayout.layoutTableTree(AbstractColumnLayout.java:239)
	at org.eclipse.jface.layout.AbstractColumnLayout.layout(AbstractColumnLayout.java:262)
	at org.eclipse.jface.layout.TreeColumnLayout.layout(TreeColumnLayout.java:92)
	at org.eclipse.swt.widgets.Composite.updateLayout(Composite.java:1847)
	at org.eclipse.swt.widgets.Composite.setBounds(Composite.java:1635)
	at org.eclipse.swt.widgets.Control.setBounds(Control.java:977)
	at org.eclipse.swt.custom.StackLayout.layout(StackLayout.java:126)
	at org.eclipse.swt.widgets.Composite.updateLayout(Composite.java:1847)
	at org.eclipse.swt.widgets.Composite.setBounds(Composite.java:1635)
	at org.eclipse.swt.widgets.Control.setBounds(Control.java:1017)
	at org.eclipse.swt.layout.GridLayout.layout(GridLayout.java:696)
	at org.eclipse.swt.layout.GridLayout.layout(GridLayout.java:200)
	at org.eclipse.swt.widgets.Composite.updateLayout(Composite.java:1847)
	at org.eclipse.swt.widgets.Composite.setBounds(Composite.java:1635)
	at org.eclipse.swt.widgets.Control.setBounds(Control.java:977)
	at org.eclipse.swt.custom.StackLayout.layout(StackLayout.java:126)
	at org.eclipse.swt.widgets.Composite.updateLayout(Composite.java:1847)
	at org.eclipse.swt.widgets.Composite.updateLayout(Composite.java:1853)
	at org.eclipse.swt.widgets.Composite.updateLayout(Composite.java:1853)
	at org.eclipse.swt.widgets.Composite.updateLayout(Composite.java:1853)
	at org.eclipse.swt.widgets.Composite.updateLayout(Composite.java:1853)
	at org.eclipse.swt.widgets.Composite.updateLayout(Composite.java:1853)
	at org.eclipse.swt.widgets.Composite.updateLayout(Composite.java:1853)
	at org.eclipse.swt.widgets.Composite.setLayoutDeferred(Composite.java:1694)
	at org.eclipse.swt.widgets.Display.runDeferredLayouts(Display.java:5075)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4570)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1173)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1062)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)
	at org.eclipse.e4.ui.internal.workbench.swt.E4Application.start(E4Application.java:165)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:199)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:391)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:246)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:595)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1501)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1474)

`

java -version
openjdk version "11.0.1" 2018-10-16
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.1+13)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.1+13, mixed mode)

GTK-3 in der PortfolioPerformance.ini

**Comment by dominikschulz** [comment]
Still happens with Version: 0.43.1 (Dez 2019), Platform: linux, x86_64.

**Comment by yetipenguin** [comment]
Problem mit dieser Version nicht mehr auf:
Version: 0.52.0 (Apr. 2021)
Platform: linux, x86_64
Java: 11.0.11+9-Ubuntu-0ubuntu2.18.04, Ubuntu
