### ISSUE TITLE
Widget is disposed

### ISSUE THREAD

**Issue by megabugman** [buchen/portfolio#1192]
Klassifizierung löschen, dann kommt der Fehler:

```
org.eclipse.swt.SWTException: Widget is disposed

	at org.eclipse.swt.SWT.error(SWT.java:4595)

	at org.eclipse.swt.SWT.error(SWT.java:4510)

	at org.eclipse.swt.SWT.error(SWT.java:4481)

	at org.eclipse.swt.widgets.Widget.error(Widget.java:451)

	at org.eclipse.swt.widgets.Widget.checkWidget(Widget.java:350)

	at org.eclipse.swt.widgets.Control.redraw(Control.java:2444)

	at name.abuchen.portfolio.ui.editor.Sidebar.select(Sidebar.java:137)

	at name.abuchen.portfolio.ui.editor.ClientEditorSidebar.select(ClientEditorSidebar.java:115)

	at name.abuchen.portfolio.ui.editor.PortfolioPart.activateView(PortfolioPart.java:496)

	at name.abuchen.portfolio.ui.editor.PortfolioPart.activateView(PortfolioPart.java:480)

	at name.abuchen.portfolio.ui.editor.ClientEditorSidebar$1.select(ClientEditorSidebar.java:68)

	at name.abuchen.portfolio.ui.editor.ClientEditorSidebar$1.select(ClientEditorSidebar.java:1)

	at name.abuchen.portfolio.ui.editor.Sidebar$Entry.handleMouseDown(Sidebar.java:386)

	at org.eclipse.swt.events.MouseListener$2.mouseDown(MouseListener.java:96)

	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:196)

	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)

	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4145)

	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1055)

	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3958)

	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3561)

	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1173)

	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)

	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1062)

	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)

	at org.eclipse.e4.ui.internal.workbench.swt.E4Application.start(E4Application.java:165)

	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:199)

	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)

	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)

	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:391)

	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:246)

	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)

	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)

	at java.lang.reflect.Method.invoke(Unknown Source)

	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)

	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:595)

	at org.eclipse.equinox.launcher.Main.run(Main.java:1501)

```

**Comment by buchen** [comment]
Danke. Ist behoben. Kommt mit der nächsten Version.
