### ISSUE TITLE
WebAccess mit Proxy 0.42.0

### ISSUE THREAD

**Issue by CJanne** [buchen/portfolio#1239]
Keine Verbindung zum Internet über Proxyverbindungen mehr möglich...
LOG:
Wed Oct 02 10:29:18 CEST 2019
Connect to www.portfolio-report.net:443 [www.portfolio-report.net/37.221.198.115] failed: connect timed out
org.apache.http.conn.ConnectTimeoutException: Connect to www.portfolio-report.net:443 [www.portfolio-report.net/37.221.198.115] failed: connect timed out
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:151)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:373)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:381)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:237)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:111)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
	at name.abuchen.portfolio.util.WebAccess.get(WebAccess.java:154)
	at name.abuchen.portfolio.online.impl.PortfolioReportNet.getUpdatedValues(PortfolioReportNet.java:232)
	at name.abuchen.portfolio.ui.jobs.SyncOnlineSecuritiesJob.run(SyncOnlineSecuritiesJob.java:49)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.net.SocketTimeoutException: connect timed out
	at java.base/java.net.PlainSocketImpl.waitForConnect(Native Method)
	at java.base/java.net.PlainSocketImpl.socketConnect(Unknown Source)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
	at java.base/java.net.AbstractPlainSocketImpl.connect(Unknown Source)
	at java.base/java.net.SocksSocketImpl.connect(Unknown Source)
	at java.base/java.net.Socket.connect(Unknown Source)
        at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:339)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
	... 13 more

**Comment by Ragas13** [comment]
Argh, dass hätte nicht sein dürfen. Aber ich arbeite ohne Proxy und da ist es nicht aufgefallen :sad:

https://github.com/buchen/portfolio/blob/master/name.abuchen.portfolio.ui/src/name/abuchen/portfolio/ui/addons/ProxyAddon.java

```
HttpHost proxy = new HttpHost("proxy.com", 80);
DefaultProxyRoutePlanner routePlanner = new DefaultProxyRoutePlanner(proxy);
CloseableHttpClient httpclient = HttpClients.custom()
                    .setRoutePlanner(routePlanner)
                    .build();
```

**Comment by buchen** [comment]
Ich veröffentliche gerade eine neue Version. Damit sollte es wieder gehen.
