### ISSUE TITLE
NullPointerException im WebAccess

### ISSUE THREAD

**Issue by sebasbaumh** [buchen/portfolio#1254]
Ich erhalte mit dem aktuellen Code eine `NullPointerException` im neuen `WebAccess`:

    Tue Oct 15 14:37:40 CEST 2019
    Während "Alpha Vantage" ist ein interner Fehler aufgetreten.
    
    java.lang.NullPointerException
    	at name.abuchen.portfolio.util.WebAccess.get(WebAccess.java:170)
    	at name.abuchen.portfolio.online.impl.AlphavantageQuoteFeed.updateLatestQuotes(AlphavantageQuoteFeed.java:108)
    	at name.abuchen.portfolio.ui.jobs.UpdateQuotesJob$1.run(UpdateQuotesJob.java:231)
    	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
    
    Tue Oct 15 14:37:40 CEST 2019
    Während "Yahoo Finance" ist ein interner Fehler aufgetreten.
    
    java.lang.NullPointerException
    	at name.abuchen.portfolio.util.WebAccess.get(WebAccess.java:170)
    	at name.abuchen.portfolio.online.impl.YahooFinanceQuoteFeed.updateLatestQuotes(YahooFinanceQuoteFeed.java:69)
    	at name.abuchen.portfolio.ui.jobs.UpdateQuotesJob$1.run(UpdateQuotesJob.java:231)
    	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

**Comment by sebasbaumh** [comment]
@Ragas13  Das Problem ist, dass der Port hier `null` ist, weil es ein `Integer` ist. Es müsste ein `int` `<=0` sein für den Standardport.

**Comment by Ragas13** [comment]
Danke für den Hinweis, war ein Flüchtigkeitsfehler. Integer anstelle int.  Ist bei mir warum auch immer nicht auf NPE gelaufen...

Danke
:+1:

**Comment by sebasbaumh** [comment]
Kein Problem - hat bei mir auch gedauert, das rauszufinden - sah nämlich recht sauber aus 😉 
Das Problem entstand quasi beim Aufruf, wodurch er den `Integer` nach `int` castet und dann in die Exception läuft. Der Code außerhalb der Funktion und der Code in `setPort` sah gut aus.

Eventuell könnte man bei manchen Klassen auch Null-Annotations zur Prüfung nutzen (kann eclipse von Haus aus).
Das wird nur schwieriger, wenn Felder mit Dependency Injection gefüllt werden.
Für Parameter und Rückgabewerte von Funktionen geht das aber recht gut und da nutze ich sowas gerne.
