### ISSUE TITLE
Donut Charts / Klassifizierungen werden nicht mehr angezeigt

### ISSUE THREAD

**Issue by th23x** [buchen/portfolio#1290]
Hallo,

leider kann ich seit einiger Zeit weder auf meinem Notebook (Win 10 LTSC) noch dem meiner Freundin (Win 10 Business) keine der Donut-Diagramme mehr sehen (andere funktionieren):

![donut-charts](https://user-images.githubusercontent.com/13735303/69748959-be3a5480-1149-11ea-987b-036ed51f682a.jpg)
![other-charts](https://user-images.githubusercontent.com/13735303/69748960-bed2eb00-1149-11ea-9cb9-87c2486a242d.jpg)

Im Forum hatte schon ein anderer Nutzer ähnliches berichtet, wobei sich keine Lösung gefunden hat: [https://forum.portfolio-performance.info/t/keine-tortendiagramme-sichtbar/370](https://forum.portfolio-performance.info/t/keine-tortendiagramme-sichtbar/370)

Meine PP Details:
Version: 0.42.1 (Nov. 2019)
Platform: win32, x86_64 [Windows 10]
Java: 11.0.4+11-LTS, Azul Systems, Inc.

**Comment by buchen** [comment]
Der Kommentar aus dem PP Forum gilt weiterhin.

Die Donut (oder Kuchendiagramme) werden per HTML in einen embedded Browser gezeichnet, das Schichtendiagramm nativ (ohne Browser). Es wundert mich also nicht wenn das zweite tut obwohl das erste nicht tut.

Aber warum tut das Kuchendiagramm nicht. Für das "embedding" des Browsers wird der Internet Explorer verwendet. Also nicht Edge. Oder andere Browser. Genau nur der Internet Explorer. Die letzte Version war wohl Version 11. **Den hast Du installiert?**

Dann geht vielleicht was schief beim "embedding"... dazu wäre interessant die **".log" Datei** zu haben (richtig. Die fängt mit einem Punkt an und hat dann nur die Datei Endung "log"). Such mal in dem [Workspace Verzeichnis](https://help.portfolio-performance.info/installation/#workspace-verzeichnis).

**Comment by th23x** [comment]
Okay, danke! Habe ich verstanden und auch die Tips dort mit zurücksetzen und check des IE (nochmal) gemacht. Leider ohne Erfolg...

Internet Explorer ist installiert:
![internet-explorer](https://user-images.githubusercontent.com/13735303/69825613-2b182200-1210-11ea-8229-3b7cc2edf210.jpg)

Und hier noch die .log Datei:
[pp-log.zip](https://github.com/buchen/portfolio/files/3902718/pp-log.zip)

Muss gestehen, dass ich aus letzterer nicht ganz schlau werde, sorry :-( Danke für Deine Hilfe!

**Comment by buchen** [comment]
Wo und wie hast Du PP denn installiert?

Es scheint sich um ein Berechtigungsproblem zu handeln. PP (beziehungsweise das Framework) packt Dateien aus um dem Browser Zugriff zu geben. Das geht schief. Siehe Fehlermeldungen unten.

Probiert mal PP "als Administrator" zu starten. Oder irgendwo das PP Installations-ZIP auspacken und von da starten. (Ich kenne mich mit den Berechtigungen unter Windows nicht so gut aus).

```
java.io.IOException: Die URL "bundleentry://318.fwk1278002745/META-INF/js/d3.min.js" konnte nicht extrahiert werden, möglicherweise wegen zu niedrigen Berechtigungen oder wegen fehlendem Speicherplatz.
```

und

```
java.io.IOException: Die URL "bundleentry://318.fwk1278002745/META-INF/css/pp.css" konnte nicht extrahiert werden, möglicherweise wegen zu niedrigen Berechtigungen oder wegen fehlendem Speicherplatz.
```

Full exception for reference - diese Fehlermeldung sollte dem Benutzer gezeigt werden.

```
!ENTRY name.abuchen.portfolio.ui 4 0 2019-11-27 19:09:35.078
!MESSAGE Die URL "bundleentry://318.fwk1278002745/META-INF/css/pp.css" konnte nicht extrahiert werden, möglicherweise wegen zu niedrigen Berechtigungen oder wegen fehlendem Speicherplatz.
!STACK 0
java.io.IOException: Die URL "bundleentry://318.fwk1278002745/META-INF/css/pp.css" konnte nicht extrahiert werden, möglicherweise wegen zu niedrigen Berechtigungen oder wegen fehlendem Speicherplatz.
	at org.eclipse.osgi.storage.url.BundleURLConverter.toFileURL(BundleURLConverter.java:43)
	at org.eclipse.core.runtime.FileLocator.toFileURL(FileLocator.java:258)
	at name.abuchen.portfolio.ui.util.EmbeddedBrowser$PathResolver.resolveToken(EmbeddedBrowser.java:109)
	at name.abuchen.portfolio.util.TokenReplacingReader.read(TokenReplacingReader.java:65)
	at name.abuchen.portfolio.util.TokenReplacingReader.read(TokenReplacingReader.java:88)
	at java.base/java.io.Reader.read(Unknown Source)
	at java.base/java.util.Scanner.readInput(Unknown Source)
	at java.base/java.util.Scanner.next(Unknown Source)
	at name.abuchen.portfolio.ui.util.EmbeddedBrowser.loadHTML(EmbeddedBrowser.java:91)
	at name.abuchen.portfolio.ui.util.EmbeddedBrowser.refresh(EmbeddedBrowser.java:81)
	at name.abuchen.portfolio.ui.views.taxonomy.DonutViewer.nodeChange(DonutViewer.java:50)
	at name.abuchen.portfolio.ui.views.taxonomy.TaxonomyModel.lambda$6(TaxonomyModel.java:389)
	at java.base/java.util.ArrayList.forEach(Unknown Source)
	at name.abuchen.portfolio.ui.views.taxonomy.TaxonomyModel.fireTaxonomyModelChange(TaxonomyModel.java:389)
	at name.abuchen.portfolio.ui.views.taxonomy.TaxonomyView.notifyModelUpdated(TaxonomyView.java:270)
	at name.abuchen.portfolio.ui.editor.PortfolioPart.onRecalculationNeeded(PortfolioPart.java:372)
	at java.base/java.util.ArrayList.forEach(Unknown Source)
	at name.abuchen.portfolio.ui.editor.ClientInput.setDirty(ClientInput.java:124)
	at name.abuchen.portfolio.ui.editor.ClientInput.lambda$10(ClientInput.java:476)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:3933)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3564)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1173)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1062)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)
	at org.eclipse.e4.ui.internal.workbench.swt.E4Application.start(E4Application.java:165)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:199)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:391)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:246)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:595)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1501)
```

**Comment by th23x** [comment]
Okay, danke Andreas, der Tip war Gold wert :-)

Ich habe PP (der Ordnung halber) in seinem Ordner unter Windows 10 nach "C:\Programme" (oder "C:\Programme (x86)") geschoben. In diesem Bereich kann man das Program ohne Probleme starten, aber da es kein Installer mit entsprechenden Berechtigungen ausgestattet hat, kann es selbst nicht in diesem / seinem Verzeichnis "schreiben".

Lösung(en), die vielleicht dem einen oder anderen helfen:

1) Programm als Admin ausführen - also Rechtsklick auf den Shortcut, "Als Administrator ausführen" und die UAC Abfrage bestätigen

2) Im Windows Explorer den Ordner unter "C:\Programme" finden, Rechtsklick, "Eigenschaften", Reiter "Sicherheit", Gruppenname "Alle Anwendungspakete" auswählen, "Bearbeiten..." klicken, dann "Schreiben" "zulassen" indem man das entsprechende Kästchen anhakt, dann muss man 10-15 Nachfragen zu Unterordnern mit "Weiter" bestätigen, letztlich mit "Ok" abschließen

Alle Grafiken und Auswertungen werden einwandfrei angezeigt - TOP :-)

**Comment by buchen** [comment]
Ich habe auch schon mal einen [Installer](https://github.com/buchen/portfolio/blob/master/portfolio-app/releng/build_installer.sh) gebaut. Aber schlußendlich noch nicht veröffentlicht weil ich mir nicht klar war wie ich das mit den Rechten handhaben muss.

Ich werde jetzt erstmal die Fehlermeldung so ändern, dass der Benutzer eine Chance hat zu sehen was da schief geht.

**Comment by th23x** [comment]
Nicht falsch verstehen mit dem Installer...ich wollte nicht sage es braucht den. Ich finde es ohne sogar flexibler. Nur muss man halt manuell dann die Ordner-Berechtigungen anpassen, wenn man die EXE (zumindest unter Win10) in den Programme Ordner verschiebt.

Die Fehlermeldung ist sicher eine gute Lösung - die hätte mich wahrscheinlich auch in die richtige Richtung geschickt, den Fehler in dem Setup hier zu finden :-)
