### ISSUE TITLE
Import PDF (Flatex) - Nullpointer Exception

### ISSUE THREAD

**Issue by maku** [buchen/portfolio#1305]
Beim Import eines PDF Documents bekomme ich eine Exception (ist eine Flatex Dividendengutschrift von Microsoft Aktien US5949181045)
```
Tue Dec 17 16:26:24 CET 2019


java.lang.reflect.InvocationTargetException

	at org.eclipse.jface.operation.ModalContext.run(ModalContext.java:401)

	at org.eclipse.jface.dialogs.ProgressMonitorDialog.run(ProgressMonitorDialog.java:474)

	at name.abuchen.portfolio.ui.handlers.ImportPDFHandler.runImport(ImportPDFHandler.java:105)

	at name.abuchen.portfolio.ui.handlers.ImportPDFHandler.lambda$0(ImportPDFHandler.java:56)

	at java.util.Optional.ifPresent(Unknown Source)

	at name.abuchen.portfolio.ui.handlers.ImportPDFHandler.doExecute(ImportPDFHandler.java:56)

	at name.abuchen.portfolio.ui.handlers.ImportPDFHandler.execute(ImportPDFHandler.java:51)

	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)

	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)

	at java.lang.reflect.Method.invoke(Unknown Source)

	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:58)

	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:320)

	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:254)

	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:164)

	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:156)

	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:497)

	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:490)

	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:207)

	at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.executeItem(HandledContributionItem.java:436)

	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.handleWidgetSelection(AbstractContributionItem.java:449)

	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.lambda$2(AbstractContributionItem.java:475)

	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)

	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4145)

	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1055)

	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3958)

	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3561)

	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1173)

	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)

	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1062)

	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)

	at org.eclipse.e4.ui.internal.workbench.swt.E4Application.start(E4Application.java:165)

	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:199)

	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)

	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)

	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:391)

	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:246)

	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)

	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)

	at java.lang.reflect.Method.invoke(Unknown Source)

	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)

	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:595)

	at org.eclipse.equinox.launcher.Main.run(Main.java:1501)

Caused by: java.lang.NullPointerException

	at java.text.DecimalFormat.parse(Unknown Source)

	at java.text.NumberFormat.parse(Unknown Source)

	at name.abuchen.portfolio.datatransfer.pdf.AbstractPDFExtractor.asExchangeRate(AbstractPDFExtractor.java:219)

	at name.abuchen.portfolio.datatransfer.pdf.FinTechGroupBankPDFExtractor.lambda$52(FinTechGroupBankPDFExtractor.java:485)

	at name.abuchen.portfolio.datatransfer.pdf.PDFParser$Section.parse(PDFParser.java:309)

	at name.abuchen.portfolio.datatransfer.pdf.PDFParser$Transaction.parse(PDFParser.java:216)

	at name.abuchen.portfolio.datatransfer.pdf.PDFParser$Block.parse(PDFParser.java:140)

	at name.abuchen.portfolio.datatransfer.pdf.PDFParser$DocumentType.parse(PDFParser.java:84)

	at name.abuchen.portfolio.datatransfer.pdf.AbstractPDFExtractor.parseDocumentTypes(AbstractPDFExtractor.java:129)

	at name.abuchen.portfolio.datatransfer.pdf.AbstractPDFExtractor.extract(AbstractPDFExtractor.java:98)

	at name.abuchen.portfolio.datatransfer.pdf.AbstractPDFExtractor.extract(AbstractPDFExtractor.java:85)

	at name.abuchen.portfolio.datatransfer.pdf.PDFImportAssistant.run(PDFImportAssistant.java:86)

	at name.abuchen.portfolio.ui.handlers.ImportPDFHandler.lambda$1(ImportPDFHandler.java:86)

	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)



```

**Comment by Ragas13** [comment]
Kannst du bitte noch den Debug des PDFs posten?

**Comment by maku** [comment]
@Ragas13 Sorry, was verstehst Du unter "Debug des PDF"?

**Comment by Ragas13** [comment]
* Im Menü "Datei" -> "Importieren..." -> "Debug: Text aus PDF extrahieren..." den Text aus der PDF Datei generieren
* Gegebenenfalls private Informationen wie Namen, Anschrift oder genaue Buchungswerte ändern. Dabei aber unbedingt darauf achten, dass man keine neuen Zeilen, keine Zeilenümbrüche, oder Leerzeichen oder ähnliches einfügt.

Beim Posten bitte den Text in drei Backticks ([code]```[/code]) einschließen, so dass die Formatierung nicht verändert wird.

**Comment by maku** [comment]
@Ragas13  Ok hier PDF als Text 
```
PDF Author: ''
PDFBox Version: 1.8.16
-----------------------------------------
flatex Bank AG
Kundenservice
Opernring 1 / Top 736
1010 Wien
Tel.: +43 - (0)720 518 777
Mail: info@flatex.at
flatex Bank AG -  Opernring 1 / Top 736 -  A-1010 Wien
0102382000001354970030
Herrn
Abcdef Abcd
Abcdefghijklmno 111
1010 Abcd 
ÖSTERREICH
                  Wien, 16.12.2019
Dividendengutschrift für ausländische Wertpapiere
Ihre Depotnummer: 31009492484
Depotinhaber    : , Abcdef
Nr.1757281127    MICROSOFT    DL-,00000625               (US5949181045/870747)
St.             :           15,00      Bruttodividende
                                       pro Stück       :          0,5100 USD
Extag           :      20.11.2019      Bruttodividende :            7,65 USD
Zahlungstag     :      12.12.2019      Bemessungs-
Valuta          :      12.12.2019      grundlage       :            6,87 EUR
                                      *Einbeh. Steuer  :            0,86 EUR
Devisenkurs     :        1,113700
Quellenst.-satz :           15,00 %    Gez. Quellenst. :            1,15 USD
                                       Endbetrag       :            4,98 EUR
* Einbehaltene Kapitalertragsteuer, ggf. ausländische Quellensteuer. Details
  dazu finden Sie im Steuerreport unter der Transaktion-Nr.: 1757281127
Die Verrechnung des Endbetrages erfolgt über Ihr Konto Nr.: 31009492476
Anrechenbare Quellensteuer**                  15,00 %  =            1,15 USD
** nur relevant für Steuerinländer
Die  Gutschrift erfolgt  unter Vorbehalt  des  Eingangs.  Einwendungen  müssen
unverzüglich  nach  Zugang  erhoben  werden.  Die  Unterlassung  rechtzeitiger
Einwendung gilt als Genehmigung.
Dieser   Beleg   ist    keine   Steuerbescheinigung.    Kapitalerträge   sind
einkommensteuerpflichtig.
Diese Mitteilung ist maschinell erstellt und wird nicht unterschrieben.
Für weitergehende Fragen wenden Sie sich bitte an Ihr flatex-Service-Team.
flatex Bank AG Niederlassung Österreich | Aktiengesellschaft | Opernring 1 / Top 736 | 1010 Wien | Handelsgericht Wien | FN 334642 x | DVR 4000544 | UID ATU 65140956
Hauptniederlassung: flatex Bank AG | Rotfeder-Ring 7 | 60327 Frankfurt am Main (Deutschland) | Amtsgericht Frankfurt am Main | HRB 105687
- Vorsitzender des Aufsichtsrats: Martin Korbmacher | Vorstand: Frank Niehage (Vors.), Jörn Engelmann -
2000001354970030 0351102380000101
```

**Comment by AlphaCentauri1983** [comment]
Ich habe immer noch das gleiche Problem. Siehe auch https://forum.portfolio-performance.info/t/dividenden-import-wechselkurs-des-nettowertes-fehlt-flatex/1366/22 durch den Post von Erdoes (Punkt 3). Ich habe das Regex auf 
`Pattern pExchangeRate = Pattern.compile(".*Devisenkurs *: *(?<exchangeRate>[.\\d]+,\\d+).*");`
geändert und damit haben alle Dividendenimporte seit 2013 funktioniert. Das heißt manche PDFs haben vor dem Text Devisenkurs noch einige Leerzeichen.

**Comment by buchen** [comment]
Fixed by @AlphaCentauri1983. Vielen Dank. Kommt mit der nächsten Version (ich denke bis Ende Januar).

**Comment by maku** [comment]
Ich bin noch immer nicht in der Lage eine Flatex Dividendengutschrift von Microsoft Aktien (US5949181045) zu importieren. Der aktuelle Status ist:

![image](https://user-images.githubusercontent.com/64805/77659891-eb243a00-6f78-11ea-9b13-41c236fc12fd.png)

Beim Fehlerprotokoll sehe ich keine Einträge...

@AlphaCentauri1983 funktioniert das bei Dir jetzt?

**Comment by AlphaCentauri1983** [comment]
@maku Habe bei dem Release auch noch den selben Fehler. Die Ursache dafür ist in diesem Ticket vermerkt: https://github.com/buchen/portfolio/issues/1346 
Ist immer noch offen. Die Lösung dafür übersteigt jedoch meine Kenntnisse in Java bzw. von PP.

**Comment by maku** [comment]
@buchen Könnte man diesen Issue wieder öffnen? - weil der ist nicht behoben - Danke!

**Comment by buchen** [comment]
fair point - das Problem ist, dass die Buchungen vor dem Import noch flexibel massiert werden können müssen (und zwar wenn der Importer die Währungen nicht kompatibel eingelesen hat). Das ist aber leider eine grössere Sache
