### ISSUE TITLE
java.util.MissingResourceException: Can't find bundle for base name descriptions.country_descriptions, locale en_US

### ISSUE THREAD

**Issue by cmaoling** [buchen/portfolio#1345]
Hi,
after some time I started to catch up with the development of the past year.
I run into trouble introduced w/ the TradeCalendarManager during the test:
java.util.MissingResourceException: Can't find bundle for base name descriptions.country_descriptions, locale en_US
        at java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:1573)
        at java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1396)
        at java.util.ResourceBundle.getBundle(ResourceBundle.java:1091)
        at de.jollyday.util.ResourceUtil.getResourceBundle(ResourceUtil.java:174)
        at de.jollyday.util.ResourceUtil.getCountryDescriptions(ResourceUtil.java:163)
        at de.jollyday.util.ResourceUtil.getCountryDescription(ResourceUtil.java:107)
        at de.jollyday.CalendarHierarchy.getDescription(CalendarHierarchy.java:79)
        at de.jollyday.CalendarHierarchy.getDescription(CalendarHierarchy.java:68)
        at name.abuchen.portfolio.util.TradeCalendarManager.<clinit>(TradeCalendarManager.java:38)

Any advise, what I might be missing, is appreciated.
FYI: I modified the static TradeCalenderManager function, to report the Stack in case Throwable Error occurs.
FYI: I am not at the latest main branch due to other reasons, but I assume this issue is independent of this fact.

**Comment by Ragas13** [comment]
@cmaoling 
It seems that your local repository is outdated as the library of jollyday was end/2018 jost for few weeks a part of Portfolio Performance. Please sync your repository against the latest version.

**Comment by Ragas13** [comment]
@cmaoling 
Perhaps the tutorial @ https://kbroman.org/github_tutorial/pages/fork.html could be helpful to sync your fork straight forward as synchronise your master via pull requests makes it difficult to follow your push requests...

**Comment by cmaoling** [comment]
@buchen Thanks for the advise. I was able to get it running again as soon as I went forward to commit 16fe24e1c1fca0597edb8fa24749fab84fecec69.
