### ISSUE TITLE
NullPointerException bei Flatex PDF import, sowohl 0.43.1 als auch 0.44

### ISSUE THREAD

**Issue by guruz** [buchen/portfolio#1370]
Hi, Portfolio-Performance Neuling hier.
Leider sehe ich ja nicht welche PDF es betrifft, ich importiere einige (mit Datum 2012 bis 2020).
Immerhin aendert sich der Backtrace :-)

0.44:
```
Caused by: java.lang.NullPointerException: text
	at java.base/java.util.Objects.requireNonNull(Unknown Source)
	at java.base/java.time.format.DateTimeFormatter.parse(Unknown Source)
	at java.base/java.time.LocalDate.parse(Unknown Source)
	at name.abuchen.portfolio.datatransfer.pdf.AbstractPDFExtractor.asDate(AbstractPDFExtractor.java:229)
	at name.abuchen.portfolio.datatransfer.pdf.OnvistaPDFExtractor.lambda$92(OnvistaPDFExtractor.java:1108)
	at name.abuchen.portfolio.datatransfer.pdf.PDFParser$Section.parse(PDFParser.java:309)
	at name.abuchen.portfolio.datatransfer.pdf.PDFParser$Transaction.parse(PDFParser.java:216)
	at name.abuchen.portfolio.datatransfer.pdf.PDFParser$Block.parse(PDFParser.java:140)
	at name.abuchen.portfolio.datatransfer.pdf.PDFParser$DocumentType.parse(PDFParser.java:84)
	at name.abuchen.portfolio.datatransfer.pdf.AbstractPDFExtractor.parseDocumentTypes(AbstractPDFExtractor.java:129)
	at name.abuchen.portfolio.datatransfer.pdf.AbstractPDFExtractor.extract(AbstractPDFExtractor.java:98)
	at name.abuchen.portfolio.datatransfer.pdf.AbstractPDFExtractor.extract(AbstractPDFExtractor.java:85)
	at name.abuchen.portfolio.datatransfer.pdf.PDFImportAssistant.run(PDFImportAssistant.java:86)
	at name.abuchen.portfolio.ui.handlers.ImportPDFHandler.lambda$1(ImportPDFHandler.java:86)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
```

0.43.1:
```
Caused by: java.lang.NullPointerException
	at java.base/java.text.DecimalFormat.parse(Unknown Source)
	at java.base/java.text.NumberFormat.parse(Unknown Source)
	at name.abuchen.portfolio.datatransfer.pdf.AbstractPDFExtractor.asExchangeRate(AbstractPDFExtractor.java:219)
	at name.abuchen.portfolio.datatransfer.pdf.FinTechGroupBankPDFExtractor.lambda$52(FinTechGroupBankPDFExtractor.java:485)
	at name.abuchen.portfolio.datatransfer.pdf.PDFParser$Section.parse(PDFParser.java:309)
	at name.abuchen.portfolio.datatransfer.pdf.PDFParser$Transaction.parse(PDFParser.java:216)
	at name.abuchen.portfolio.datatransfer.pdf.PDFParser$Block.parse(PDFParser.java:140)
	at name.abuchen.portfolio.datatransfer.pdf.PDFParser$DocumentType.parse(PDFParser.java:84)
	at name.abuchen.portfolio.datatransfer.pdf.AbstractPDFExtractor.parseDocumentTypes(AbstractPDFExtractor.java:129)
	at name.abuchen.portfolio.datatransfer.pdf.AbstractPDFExtractor.extract(AbstractPDFExtractor.java:98)
	at name.abuchen.portfolio.datatransfer.pdf.AbstractPDFExtractor.extract(AbstractPDFExtractor.java:85)
	at name.abuchen.portfolio.datatransfer.pdf.PDFImportAssistant.run(PDFImportAssistant.java:86)
	at name.abuchen.portfolio.ui.handlers.ImportPDFHandler.lambda$1(ImportPDFHandler.java:86)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
```

**Comment by guruz** [comment]
Ich dachte es koennte ja https://github.com/buchen/portfolio/issues/1305 sein (mein 0.43.1 backtrace)...
Dann ist die Frage warum sagt der 0.44 backtrace was von `OnvistaPDFExtractor`?!

**Comment by buchen** [comment]
Interessant. Es werden immer alle Extratouren auf die Dokumente losgelassen. Nach dem Motto: es wird schon ganz früh schief gehen. Beim ersten geht es schief beim Einlesen eines Datums, beim Zeiten beim Einlesen einer Zahl.

**Comment by guruz** [comment]
@buchen Wie kann ich denn ein debug log aktivieren? (nicht das exception log).
Bin leider C++er, kein Java-Mensch.
Auf https://forum.portfolio-performance.info/t/was-sollte-ich-beim-melden-eines-fehlers-beachten/463 steht nichts.

**Comment by buchen** [comment]
Ich habe die Fehlerbehandlung beim Import jetzt mal dahingehend geändert, dass zu der Exception zumindest der Dateinahme ausgegeben werden sollte. Aber ohne Beispieldateien sind beide Problem nicht so lösen. Die regulären Ausdrücken finden im ersten Fall das Datum und im zweiten Fall den Wechselkurs nicht. Aber warum ist ohne Beispiel schwer zu sagen - vermutlich hat sich das Format der Dateien geändert. Es würde mir helfen wenn Du mir die Datei die den Fehler provoziert (sollte mit dieser Change leichter erkennbar sein) als Text hier posten könntest (Datei -> Importieren... -> Debug: PDF in Text konvertieren).

> Wie kann ich denn ein debug log aktivieren? (nicht das exception log). Bin leider C++er, kein Java-Mensch.

Es gibt kein debug log über das Fehlerprotokoll hinaus.

**Comment by guruz** [comment]
Danke, mit 0.44.1 wirft er keine exception mehr. Jetzt muss ich nur noch dahinter steigen warum manche Wertpapiere eine negative Anzahl haben :-) Mal gucken heute abend..
