### ISSUE TITLE
NullpointerException in Performance Berechnung

### ISSUE THREAD

**Issue by curbaczek** [buchen/portfolio#1480]
Hi, ich nutze PP 0.46.0 (März 2020), sehr geiles Tool - vielen Dank dafür! Ich habe heute in einigen Konten manuelle Ergänzungen an den Buchungen durchgeüfhrt. Leider erhalte ich seitdem im Bericht Performance-Berechnung eine NullPointerException:

```
java.lang.NullPointerException
	at name.abuchen.portfolio.money.MutableMoney.subtract(MutableMoney.java:61)
	at name.abuchen.portfolio.snapshot.trail.ArithmeticTrail.<init>(ArithmeticTrail.java:44)
	at name.abuchen.portfolio.snapshot.trail.TrailRecord.substract(TrailRecord.java:70)
	at name.abuchen.portfolio.snapshot.ClientPerformanceSnapshot.lambda$5(ClientPerformanceSnapshot.java:561)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
	at java.base/java.util.HashMap$EntrySpliterator.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.collect(Unknown Source)
	at name.abuchen.portfolio.snapshot.ClientPerformanceSnapshot.addCapitalGains(ClientPerformanceSnapshot.java:577)
	at name.abuchen.portfolio.snapshot.ClientPerformanceSnapshot.calculate(ClientPerformanceSnapshot.java:321)
	at name.abuchen.portfolio.snapshot.ClientPerformanceSnapshot.<init>(ClientPerformanceSnapshot.java:217)
	at name.abuchen.portfolio.ui.views.PerformanceView.reportingPeriodUpdated(PerformanceView.java:126)
	at name.abuchen.portfolio.ui.views.PerformanceView.createBody(PerformanceView.java:171)
	at name.abuchen.portfolio.ui.editor.AbstractFinanceView.createViewControl(AbstractFinanceView.java:127)
	at name.abuchen.portfolio.ui.editor.PortfolioPart.createView(PortfolioPart.java:522)
	at name.abuchen.portfolio.ui.editor.PortfolioPart.activateView(PortfolioPart.java:492)
	at name.abuchen.portfolio.ui.editor.PortfolioPart.activateView(PortfolioPart.java:480)
	at name.abuchen.portfolio.ui.editor.ClientEditorSidebar$1.select(ClientEditorSidebar.java:68)
	at name.abuchen.portfolio.ui.editor.ClientEditorSidebar$1.select(ClientEditorSidebar.java:1)
	at name.abuchen.portfolio.ui.editor.Sidebar$Entry.handleMouseDown(Sidebar.java:389)
	at org.eclipse.swt.events.MouseListener$2.mouseDown(MouseListener.java:96)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:196)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4145)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1055)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3958)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3561)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1173)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1062)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)
	at org.eclipse.e4.ui.internal.workbench.swt.E4Application.start(E4Application.java:165)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:199)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:391)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:246)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:595)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1501)
```

**Comment by buchen** [comment]
Ok, die NPE tritt jetzt nicht mehr auf. Das habe ich behoben.

Allerdings stimmt die Rechnung trotzdem nicht weil es sich um einen Leerverkauf handelt den PP momentan (noch?) nicht unterstützt. Was ich mir dabei vor allem mal überlegen muss: wie berechne ich den FIFO Wert bei negativen Beständen. Momentan suche ich zu jedem Verkauf eine passende Kaufbuchung. Das geht dann aber nicht mehr. Wenn Du Links hast wie sich FIFO bei (gemischten) Long/Short Positionen errechnet, dann gerne her damit.
