### ISSUE TITLE
MonetaryException bei Wahl von YTD in Performance-View

### ISSUE THREAD

**Issue by sebasbaumh** [buchen/portfolio#1525]
Im Performance-View bekomme ich eine MonetaryException bei Wahl einiger Zeiträume:
- Aktuelles Jahr (YTD)
- 1 Jahr
- 6 Monate
- 2020

aber nicht bei:
- 1 Monat
- 7 Tage
- seit 01.01.2014
- seit 20.07.2018

Das ist die Exception:

Mon May 04 18:30:16 CEST 2020
Internal Error

name.abuchen.portfolio.money.MonetaryException

	at name.abuchen.portfolio.money.MutableMoney.add(MutableMoney.java:52)

	at name.abuchen.portfolio.money.MoneyCollectors$1.lambda$0(MoneyCollectors.java:58)

	at name.abuchen.portfolio.money.MoneyCollectors$1$$Lambda$121/0000000000000000.accept(Unknown Source)

	at java.base/java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)

	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)

	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)

	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1654)

	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:497)

	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:487)

	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)

	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:239)

	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)

	at name.abuchen.portfolio.snapshot.trail.ArithmeticTrail.<init>(ArithmeticTrail.java:38)

	at name.abuchen.portfolio.snapshot.trail.TrailRecord.of(TrailRecord.java:41)

	at name.abuchen.portfolio.snapshot.security.CostCalculation.getFifoCostTrail(CostCalculation.java:187)

	at name.abuchen.portfolio.snapshot.security.SecurityPerformanceRecord.calculateFifoAndMovingAverageCosts(SecurityPerformanceRecord.java:467)

	at name.abuchen.portfolio.snapshot.security.SecurityPerformanceRecord.calculate(SecurityPerformanceRecord.java:419)

	at name.abuchen.portfolio.snapshot.security.SecurityPerformanceSnapshot.doCreateSnapshot(SecurityPerformanceSnapshot.java:69)

	at name.abuchen.portfolio.snapshot.security.SecurityPerformanceSnapshot.create(SecurityPerformanceSnapshot.java:34)

	at name.abuchen.portfolio.ui.views.SecuritiesPerformanceView.reportingPeriodUpdated(SecuritiesPerformanceView.java:1135)

	at name.abuchen.portfolio.ui.util.ReportingPeriodDropDown.lambda$2(ReportingPeriodDropDown.java:113)

	at name.abuchen.portfolio.ui.util.ReportingPeriodDropDown$$Lambda$510/0000000000000000.run(Unknown Source)

	at name.abuchen.portfolio.ui.util.SimpleAction.run(SimpleAction.java:43)

	at org.eclipse.jface.action.Action.runWithEvent(Action.java:476)

	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:568)

	at org.eclipse.jface.action.ActionContributionItem.lambda$4(ActionContributionItem.java:400)

	at org.eclipse.jface.action.ActionContributionItem$$Lambda$356/0000000000000000.handleEvent(Unknown Source)

	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)

	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4145)

	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1055)

	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3958)

	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3561)

	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1173)

	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)

	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1062)

	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)

	at org.eclipse.e4.ui.internal.workbench.swt.E4Application.start(E4Application.java:165)

	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:199)

	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)

	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)

	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:391)

	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:246)

	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

	at java.base/java.lang.reflect.Method.invoke(Method.java:566)

	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)

	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:595)

	at org.eclipse.equinox.launcher.Main.run(Main.java:1501)

Getestet habe ich mit dem aktuellsten Code-Stand.

**Comment by sebasbaumh** [comment]
01.01.2020 geht auch nicht, also muss irgendwas danach Probleme machen.
Allerdings passiert das wie gesagt erst nachdem ich den aktuellen Stand gebaut habe.
Mein vorheriger war vom 24.04. - also müsste es dazwischen eine Änderung gegeben haben, die Probleme macht.

**Comment by sebasbaumh** [comment]
Geworfen wird die Exception bei Prüfung der Währung.
Ich glaube, die Ursache liegt hier: https://github.com/buchen/portfolio/commit/71b4f246898234e5acec5968a3a67d4268913d69

Das ist der Stacktrace:

    Thread [main] (Suspended (breakpoint at line 52 in MutableMoney))   
    MutableMoney.add(Money) line: 52    
    MoneyCollectors$1.lambda$0(MutableMoney, Money) line: 58    
    0000000000000000.accept(Object, Object) line: not available 
    ReduceOps$3ReducingSink.accept(T) line: 169 
    ReferencePipeline$2$1.accept(P_OUT) line: 177   
    ReferencePipeline$3$1.accept(P_OUT) line: 195   
    ArrayList$ArrayListSpliterator.forEachRemaining(Consumer<? super E>) line: 1654 
    AbstractPipeline<E_IN,E_OUT,S>.copyInto(Sink<P_IN>, Spliterator<P_IN>) line: 497    
    AbstractPipeline<E_IN,E_OUT,S>.wrapAndCopyInto(S, Spliterator<P_IN>) line: 487  
    ReduceOps$ReduceOp<T,R,S>.evaluateSequential(PipelineHelper<T>, Spliterator<P_IN>) line: 913    
    AbstractPipeline<E_IN,E_OUT,S>.evaluate(TerminalOp<E_OUT,R>) line: 239  
    ReferencePipeline$2(ReferencePipeline<P_IN,P_OUT>).collect(Collector<? super P_OUT,A,R>) line: 578  
    ArithmeticTrail.<init>(ArithmeticTrail$Operation, String, TrailRecord...) line: 38  
    TrailRecord.of(List<TrailRecord>) line: 41  
    CostCalculation.getFifoCostTrail() line: 187    
    SecurityPerformanceRecord.calculateFifoAndMovingAverageCosts(CurrencyConverter) line: 467   
    SecurityPerformanceRecord.calculate(Client, CurrencyConverter, Interval) line: 419  
    SecurityPerformanceSnapshot.doCreateSnapshot(Client, CurrencyConverter, Map<Security,SecurityPerformanceRecord>, Interval) line: 69 
    SecurityPerformanceSnapshot.create(Client, CurrencyConverter, Interval) line: 34    
    SecuritiesPerformanceView.reportingPeriodUpdated() line: 1135   
...

**Comment by sebasbaumh** [comment]
Und das sind die Werte genau an der Stelle:
`this: USD 3.436,20`
`money: EUR 1.090,43`
Die unterschiedliche Währung ist die Ursache.

**Comment by buchen** [comment]
Danke. Da fehlt wohl eine Währungsumwandlung. Gut das Du schon testest bevor ich das veröffentliche...

**Comment by sebasbaumh** [comment]
Ja gerne 😄 
Meist ziehe ich meinen Branch nur nach, wenn ich was interessantes sehe oder Du eine neue Version machst. Deswegen ist es mir zufällig aufgefallen.
Ich wollte erst versuchen es zu fixen, war mir aber nicht sicher, an welcher Stelle die Währungsumwandlung am besten wäre.

**Comment by sebasbaumh** [comment]
Funktioniert jetzt - danke 👍

**Comment by buchen** [comment]
Ich befürchte das Problem ist nicht behoben - ich habe heute kurzerhand die ursprüngliche Änderung revertet (darum die schnelle 0.46.3 Version). Ich schaue mir das aber bei Gelegenheit an.

**Comment by sebasbaumh** [comment]
Zumindest bei mir funktionieren damit alle Zeiträume, wo vorher die Exception kam.

**Comment by buchen** [comment]
Neuer Versuch. Jetzt sollte es tun.
