### ISSUE TITLE
Bug: Nullpointer Exception beim Öffnen

### ISSUE THREAD

**Issue by MarcDahlem** [buchen/portfolio#1541]
Hallo zusammen,

direkt beim Öffnen meines (verschlüsselten) Portfolios erhalte ich seit dem neusten Update folgende Fehlermeldung.

Beim entsprechenden Öffnen war gerade die Trade-View im Vordergrund.
Eventuell wurde der Fehler getriggert durch den automatischen Download neuer Kurse von Wertpapieren?

`Wed May 13 22:10:32 CEST 2020
Internal Error

java.lang.NullPointerException

	at name.abuchen.portfolio.ui.views.trades.TradeDetailsView.notifyModelUpdated(TradeDetailsView.java:103)

	at name.abuchen.portfolio.ui.editor.PortfolioPart.onRecalculationNeeded(PortfolioPart.java:372)

	at java.base/java.util.ArrayList.forEach(Unknown Source)

	at name.abuchen.portfolio.ui.editor.ClientInput.setDirty(ClientInput.java:126)

	at name.abuchen.portfolio.ui.editor.ClientInput.lambda$10(ClientInput.java:488)

	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)

	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185)

	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:3933)

	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3564)

	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1173)

	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)

	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1062)

	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)

	at org.eclipse.e4.ui.internal.workbench.swt.E4Application.start(E4Application.java:165)

	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:199)

	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)

	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)

	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:391)

	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:246)

	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)

	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)

	at java.base/java.lang.reflect.Method.invoke(Unknown Source)

	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)

	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:595)

	at org.eclipse.equinox.launcher.Main.run(Main.java:1501)`

**Comment by inv-trad** [comment]
Hallo Marc,

der Fehler wurde nun auch im Forum genannt:

https://forum.portfolio-performance.info/t/java-lang-nullpointerexception-bei-start-mit-trades/9487/3

Ist es möglich, eine Beispieldatei zu bekommen, weil ich den Fehler leider nicht reproduzieren kann...

Danke und Grüße
Sven

**Comment by inv-trad** [comment]
Sollte mit Pull Request https://github.com/buchen/portfolio/pull/1577 behoben sein.
