### ISSUE TITLE
Während "Kurse aktualisieren" ist ein interner Fehler aufgetreten.

### ISSUE THREAD

**Issue by Argent** [buchen/portfolio#1700]
**Describe the bug**
I opened Portfolio performance for the first time since 14.08 and it looks like all automatic quote lookups are broken.

All securities show 14.08. as the last update date and I get an error in the error log. I load all my quotes from Yahoo finance.

**EDIT**: I found out that this happens if you have a security without a name, just an ISIN. This happened because I imported the security via a transaction PDF import.

**Error description**
Thu Aug 27 11:04:49 CEST 2020
Während "Kurse aktualisieren" ist ein interner Fehler aufgetreten.

org.eclipse.core.runtime.AssertionFailedException: null argument:
	at org.eclipse.core.runtime.Assert.isNotNull(Assert.java:88)
	at org.eclipse.core.runtime.Assert.isNotNull(Assert.java:76)
	at org.eclipse.core.internal.jobs.InternalJob.<init>(InternalJob.java:160)
	at org.eclipse.core.runtime.jobs.Job.<init>(Job.java:260)
	at name.abuchen.portfolio.ui.jobs.UpdateQuotesJob$2.<init>(UpdateQuotesJob.java:254)
	at name.abuchen.portfolio.ui.jobs.UpdateQuotesJob.addHistoricalQuotesJobs(UpdateQuotesJob.java:254)
	at name.abuchen.portfolio.ui.jobs.UpdateQuotesJob.run(UpdateQuotesJob.java:149)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

**Screenshots**
![image](https://user-images.githubusercontent.com/717301/91421361-21caed00-e856-11ea-8711-d91480dc2d4f.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - Version 0.47.0

**Comment by buchen** [comment]
fixed
