### ISSUE TITLE
Internal error when importing from CSV, tied to asset related column

### ISSUE THREAD

**Issue by trkit** [buchen/portfolio#1722]
**Describe the bug**
When trying to import a .csv of asset trades, an Internal error occurs when proceeding to the import step 2 (parsing and check before import). I could nail it down, that the asset column either when linked to an asset name or WKN is tied to the error.

In a fresh .portfolio, this bug does not exist. I don't think that my file is corrupted, since I can still import various other asset related data, like ingoing / outgoing assets. However, there might be some data point of the last month which I have not figured out yet, triggering the bug during import? Below, I attached the stack trace.

This is a portfolio file I work with for two years now, with a lot of manual changes. So a re-start with a new portfolio file is highly avoided by me.

```
Wed Sep 02 15:55:40 CEST 2020
Internal Error

java.lang.NullPointerException
	at name.abuchen.portfolio.datatransfer.actions.DetectDuplicatesAction.lambda$0(DetectDuplicatesAction.java:49)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:176)
	at java.base/java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1632)
	at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.lambda$initPartialTraversalState$0(StreamSpliterators.java:294)
	at java.base/java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.fillBuffer(StreamSpliterators.java:206)
	at java.base/java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.doAdvance(StreamSpliterators.java:161)
	at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.tryAdvance(StreamSpliterators.java:300)
	at java.base/java.util.Spliterators$1Adapter.hasNext(Spliterators.java:681)
	at name.abuchen.portfolio.datatransfer.actions.DetectDuplicatesAction.process(DetectDuplicatesAction.java:50)
	at name.abuchen.portfolio.datatransfer.Extractor$BuySellEntryItem.apply(Extractor.java:359)
	at name.abuchen.portfolio.ui.wizards.datatransfer.ReviewExtractedItemsPage.checkEntries(ReviewExtractedItemsPage.java:763)
	at name.abuchen.portfolio.ui.wizards.datatransfer.ReviewExtractedItemsPage.setResults(ReviewExtractedItemsPage.java:719)
	at name.abuchen.portfolio.ui.wizards.datatransfer.ReviewExtractedItemsPage.access$2(ReviewExtractedItemsPage.java:717)
	at name.abuchen.portfolio.ui.wizards.datatransfer.ReviewExtractedItemsPage$12.lambda$1(ReviewExtractedItemsPage.java:683)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4928)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4449)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:823)
	at org.eclipse.jface.window.Window.open(Window.java:799)
	at name.abuchen.portfolio.ui.handlers.ImportCSVHandler.runImport(ImportCSVHandler.java:87)
	at name.abuchen.portfolio.ui.handlers.ImportCSVHandler.lambda$0(ImportCSVHandler.java:46)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at name.abuchen.portfolio.ui.handlers.ImportCSVHandler.execute(ImportCSVHandler.java:46)
	at jdk.internal.reflect.GeneratedMethodAccessor84.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:58)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:319)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:253)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:173)
	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:156)
	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:488)
	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:487)
	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:213)
	at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.executeItem(HandledContributionItem.java:438)
	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.handleWidgetSelection(AbstractContributionItem.java:449)
	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.lambda$2(AbstractContributionItem.java:475)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5685)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1423)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4953)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4446)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1158)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1047)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.e4.ui.internal.workbench.swt.E4Application.start(E4Application.java:166)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:657)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:594)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1447)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1420)
```

This is not tied to the data, since manually reducing or sanitizing it to different assets 

**To Reproduce**
1. Go to import from CSV
2. Click on the file to import
3. Let the file load and adjust columns, with the asset name or WKN column being present
4. Proceed
5. Internal error shows up with no further info besides the stack trace from the error report. The dialog window stays fully clear of data otherwise.

**Expected behavior**
Working import like my other import scripts without showing up internal errors.

**Desktop (please complete the following information):**
 - OS: independent, I tried macOS Big Sur and Ubuntu 20.04
 - Version 0.48.0

**Comment by trkit** [comment]
@buchen thank you very much, b02626fc10b19f9a0153cb12703552f74303f845 fixed it!
