### ISSUE TITLE
name.abuchen.portfolio.ui.tests .................... FAILURE

### ISSUE THREAD

**Issue by cmaoling** [buchen/portfolio#1727]
**Describe the bug**
While building PortfolioPerformance I get the following errors:
Errors: 
  SimpleMovingAverageTest.testCorrectSMAEntries:77 ? NoClassDefFound Could not i...
  SimpleMovingAverageTest.testSufficientPriceDataPass:97 ? NoClassDefFound Could...
  SimpleMovingAverageTest.testSufficientPriceDataStartDate:115 ? UnsatisfiedLink

**To Reproduce**

**Expected behavior**
Worked up to v0.47 w/o issues.

**Screenshots**

```
testSufficientPriceDataStartDate(name.abuchen.portfolio.ui.views.SimpleMovingAverageTest)  Time elapsed: 0.116 s  <<< ERROR!
java.lang.UnsatisfiedLinkError: 
Could not load SWT library. Reasons: 
	no swt-pi4-gtk-4934r6 in java.library.path
	no swt-pi4-gtk in java.library.path
	Can't load library: /home/user/.swt/lib/linux/x86_64/libswt-pi4-gtk-4934r6.so
	Can't load library: /home/user/.swt/lib/linux/x86_64/libswt-pi4-gtk.so

	at org.eclipse.swt.internal.Library.loadLibrary(Library.java:342)
	at org.eclipse.swt.internal.Library.loadLibrary(Library.java:256)
	at org.eclipse.swt.internal.gtk.OS.<clinit>(OS.java:90)
	at org.eclipse.swt.widgets.Scrollable.<clinit>(Scrollable.java:44)
	at name.abuchen.portfolio.ui.views.SimpleMovingAverage.calculateSMA(SimpleMovingAverage.java:90)
	at name.abuchen.portfolio.ui.views.SimpleMovingAverage.<init>(SimpleMovingAverage.java:34)
	at name.abuchen.portfolio.ui.views.SimpleMovingAverageTest.testSufficientPriceDataStartDate(SimpleMovingAverageTest.java:115)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[...]
testCorrectSMAEntries(name.abuchen.portfolio.ui.views.SimpleMovingAverageTest)  Time elapsed: 0.001 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class name.abuchen.portfolio.ui.util.chart.TimelineChart
	at name.abuchen.portfolio.ui.views.SimpleMovingAverage.calculateSMA(SimpleMovingAverage.java:90)
	at name.abuchen.portfolio.ui.views.SimpleMovingAverage.<init>(SimpleMovingAverage.java:34)
	at name.abuchen.portfolio.ui.views.SimpleMovingAverageTest.testCorrectSMAEntries(SimpleMovingAverageTest.java:77)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
[...]
testSufficientPriceDataPass(name.abuchen.portfolio.ui.views.SimpleMovingAverageTest)  Time elapsed: 0.003 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class name.abuchen.portfolio.ui.util.chart.TimelineChart
	at name.abuchen.portfolio.ui.views.SimpleMovingAverage.calculateSMA(SimpleMovingAverage.java:90)
	at name.abuchen.portfolio.ui.views.SimpleMovingAverage.<init>(SimpleMovingAverage.java:34)
	at name.abuchen.portfolio.ui.views.SimpleMovingAverageTest.testSufficientPriceDataPass(SimpleMovingAverageTest.java:97)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runn
```

**Desktop (please complete the following information):**
 - OS: Linux
 - Version 0.48.0

**Comment by Ragas13** [comment]
@cmaoling 
With release 0.48 the Eclipse SWT framework were updated to release 2020-06. And as far Google knows, SWT / GTK is not yet compliant w/ Raspberry Pi4 even if it's Linux. Do you use Raspberry Pi as platform?

**Comment by buchen** [comment]
First: those tests are in the UI test bundle and require UI classes, hence require SWT

Second: yes, the SWT has been updated to SWT version 4.16 - https://download.eclipse.org/eclipse/downloads/drops4/R-4.16-202006040540/

Third: if I look at the current contents of PP, it includes a ```libswt-pi3-gtk```. The previous version included ```libswt-pi-gtk```and ```libswt-pi3-gtk```. If I download the SWT binary from Eclipse directly, same contents. But never a pi4. Very strange. I have no idea why the build is trying to load that OS.

With 4.16, there is no 32bit version available anymore. But you are building x86_64...


What java version are you using to build PP?

**Comment by cmaoling** [comment]
Hi @buchen and @Ragas13 thanks for the reply.
I am running on an Intel/i5 ystem which was recently updated to Ubuntu 20.04. might this be the reason for pi4?
I am building with jre1.8.0_192

**Comment by cmaoling** [comment]
Is it a new requirement to explicitly download/install the SWT package into the user space?
I am installing java => maven => ecplise , but the UI tests never complained that there is no SWT installed...
user@173a708572b8:$ ls -al
total 28
drwxr-xr-x 6 user user 4096 Sep  3 08:02 .
drwxr-xr-x 6 root root 4096 Sep  3 08:02 ..
drwx------ 2 user user 4096 Sep  3 08:02 .cache
drwxr-xr-x 7 user user 4096 Sep  3 08:02 .eclipse
-rw-r--r-- 1 root root   45 Mar 31  2019 .gitconfig
drwxr-xr-x 3 user user 4096 Sep  3 08:02 .m2
drwxr-xr-x 3 user user 4096 Sep  3 08:02 .tooling
user@173a708572b8:$ 

THis seems related to Eclipse 2020-06. I upgraded to it and are unable to start the IDE now. :(

I went back to the commit 

> bd7c31d4cbae7390f2913ffffc1eb52503a3381c

 and it looks like this:
```
[INFO] ------------------------------------------------------------------------
[INFO] Building name.abuchen.portfolio.ui.tests 0.47.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ name.abuchen.portfolio.ui.tests ---
[INFO] Deleting /data/portfolio/name.abuchen.portfolio.ui.tests/target
[INFO] 
[INFO] --- tycho-packaging-plugin:1.5.1:build-qualifier (default-build-qualifier) @ name.abuchen.portfolio.ui.tests ---
[INFO] The project's OSGi version is 0.47.1.202009030821
[INFO] 
[INFO] --- tycho-packaging-plugin:1.5.1:validate-id (default-validate-id) @ name.abuchen.portfolio.ui.tests ---
[INFO] 
[INFO] --- tycho-packaging-plugin:1.5.1:validate-version (default-validate-version) @ name.abuchen.portfolio.ui.tests ---
[INFO] 
[INFO] --- maven-enforcer-plugin:3.0.0-M2:enforce (enforce-versions) @ name.abuchen.portfolio.ui.tests ---
[INFO] 
[INFO] --- maven-checkstyle-plugin:3.1.0:check (validate) @ name.abuchen.portfolio.ui.tests ---
[INFO] Starting audit...
Audit done.
[INFO] 
[INFO] --- jacoco-maven-plugin:0.8.5:prepare-agent (prepare-agent) @ name.abuchen.portfolio.ui.tests ---
[INFO] tycho.testArgLine set to -javaagent:/home/user/.m2/repository/org/jacoco/org.jacoco.agent/0.8.5/org.jacoco.agent-0.8.5-runtime.jar=destfile=/data/portfolio/name.abuchen.portfolio.ui.tests/target/jacoco.exec
[INFO] 
[INFO] --- maven-resources-plugin:3.1.0:resources (default-resources) @ name.abuchen.portfolio.ui.tests ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /data/portfolio/name.abuchen.portfolio.ui.tests/src/main/resources
[INFO] 
[INFO] --- tycho-compiler-plugin:1.5.1:compile (default-compile) @ name.abuchen.portfolio.ui.tests ---
[INFO] Compiling 4 source files to /data/portfolio/name.abuchen.portfolio.ui.tests/target/classes
[INFO] 
[INFO] --- maven-resources-plugin:3.1.0:testResources (default-testResources) @ name.abuchen.portfolio.ui.tests ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /data/portfolio/name.abuchen.portfolio.ui.tests/src/test/resources
[INFO] 
[INFO] --- target-platform-configuration:1.5.1:target-platform (default-target-platform) @ name.abuchen.portfolio.ui.tests ---
[INFO] 
[INFO] --- tycho-packaging-plugin:1.5.1:package-plugin (default-package-plugin) @ name.abuchen.portfolio.ui.tests ---
[INFO] Building jar: /data/portfolio/name.abuchen.portfolio.ui.tests/target/name.abuchen.portfolio.ui.tests-0.47.1-SNAPSHOT.jar
[INFO] 
[INFO] --- tycho-p2-plugin:1.5.1:p2-metadata-default (default-p2-metadata-default) @ name.abuchen.portfolio.ui.tests ---
[INFO] 
[INFO] --- tycho-surefire-plugin:1.5.1:test (default-test) @ name.abuchen.portfolio.ui.tests ---
[INFO] Expected eclipse log file: /data/portfolio/name.abuchen.portfolio.ui.tests/target/work/data/.metadata/.log
[INFO] Command line:
	[/opt/Oracle_Java/jre1.8.0_192/bin/java, -Dosgi.noShutdown=false, -Dosgi.os=linux, -Dosgi.ws=gtk, -Dosgi.arch=x86_64, -javaagent:/home/user/.m2/repository/org/jacoco/org.jacoco.agent/0.8.5/org.jacoco.agent-0.8.5-runtime.jar=destfile=/data/portfolio/name.abuchen.portfolio.ui.tests/target/jacoco.exec, -Dosgi.clean=true, -jar, /home/user/.m2/repository/p2/osgi/bundle/org.eclipse.equinox.launcher/1.5.100.v20180827-1352/org.eclipse.equinox.launcher-1.5.100.v20180827-1352.jar, -data, /data/portfolio/name.abuchen.portfolio.ui.tests/target/work/data, -install, /data/portfolio/name.abuchen.portfolio.ui.tests/target/work, -configuration, /data/portfolio/name.abuchen.portfolio.ui.tests/target/work/configuration, -application, org.eclipse.tycho.surefire.osgibooter.headlesstest, -testproperties, /data/portfolio/name.abuchen.portfolio.ui.tests/target/surefire.properties]
Running name.abuchen.portfolio.ui.views.SecurityChartRangeTest
Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.145 s - in name.abuchen.portfolio.ui.views.SecurityChartRangeTest
testRangeIntersection(name.abuchen.portfolio.ui.views.SecurityChartRangeTest)  Time elapsed: 0.009 s
testRangeIfIntervalEndsAfter(name.abuchen.portfolio.ui.views.SecurityChartRangeTest)  Time elapsed: 0 s
testRangeIfIntervalEndsOnGap(name.abuchen.portfolio.ui.views.SecurityChartRangeTest)  Time elapsed: 0.001 s
testRangeIfIntervalStartsBefore(name.abuchen.portfolio.ui.views.SecurityChartRangeTest)  Time elapsed: 0 s
testRangeIfIntervalDoesNotIntersect(name.abuchen.portfolio.ui.views.SecurityChartRangeTest)  Time elapsed: 0.001 s
testRangeIfIntervalStartsOnGap(name.abuchen.portfolio.ui.views.SecurityChartRangeTest)  Time elapsed: 0 s
testRangeIfIntervalStartsAndEndsOnGap(name.abuchen.portfolio.ui.views.SecurityChartRangeTest)  Time elapsed: 0 s
Running name.abuchen.portfolio.ui.views.SimpleMovingAverageTest
Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.236 s - in name.abuchen.portfolio.ui.views.SimpleMovingAverageTest
testSufficientPriceDataStartDate(name.abuchen.portfolio.ui.views.SimpleMovingAverageTest)  Time elapsed: 0.141 s
testCorrectSMAEntries(name.abuchen.portfolio.ui.views.SimpleMovingAverageTest)  Time elapsed: 0.001 s
testSufficientPriceDataPass(name.abuchen.portfolio.ui.views.SimpleMovingAverageTest)  Time elapsed: 0.08 s
testSecurityIsNull(name.abuchen.portfolio.ui.views.SimpleMovingAverageTest)  Time elapsed: 0 s
testSecurityHasOnlyOnePrice(name.abuchen.portfolio.ui.views.SimpleMovingAverageTest)  Time elapsed: 0.001 s
Running name.abuchen.portfolio.ui.views.IssuePerformanceIndicatorsWithPartialAssignmentTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.445 s - in name.abuchen.portfolio.ui.views.IssuePerformanceIndicatorsWithPartialAssignmentTest
testFullAssignments(name.abuchen.portfolio.ui.views.IssuePerformanceIndicatorsWithPartialAssignmentTest)  Time elapsed: 0.028 s
testPartialAssignments(name.abuchen.portfolio.ui.views.IssuePerformanceIndicatorsWithPartialAssignmentTest)  Time elapsed: 0.005 s
Running name.abuchen.portfolio.ui.update.NewVersionTest
Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.013 s - in name.abuchen.portfolio.ui.update.NewVersionTest
testVersionIsSmallerConditionalMessage(name.abuchen.portfolio.ui.update.NewVersionTest)  Time elapsed: 0.006 s
testConditionalMessage(name.abuchen.portfolio.ui.update.NewVersionTest)  Time elapsed: 0.001 s
testMultipleConditionalMessage(name.abuchen.portfolio.ui.update.NewVersionTest)  Time elapsed: 0.001 s
testVersionConditionalMessage(name.abuchen.portfolio.ui.update.NewVersionTest)  Time elapsed: 0.002 s
testIfBundleNotExists(name.abuchen.portfolio.ui.update.NewVersionTest)  Time elapsed: 0.001 s
testIfBundleExists(name.abuchen.portfolio.ui.update.NewVersionTest)  Time elapsed: 0 s

Results:

Tests run: 20, Failures: 0, Errors: 0, Skipped: 0

```
after appling  

> 4d8db638a52bd82b0cb38981b62589ea5a3fd6f3

```
[INFO] ------------------------------------------------------------------------
[INFO] Building name.abuchen.portfolio.ui.tests 0.48.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ name.abuchen.portfolio.ui.tests ---
[INFO] Deleting /data/portfolio/name.abuchen.portfolio.ui.tests/target
[INFO] 
[INFO] --- tycho-packaging-plugin:1.5.1:build-qualifier (default-build-qualifier) @ name.abuchen.portfolio.ui.tests ---
[INFO] The project's OSGi version is 0.48.1.202009021857
[INFO] 
[INFO] --- tycho-packaging-plugin:1.5.1:validate-id (default-validate-id) @ name.abuchen.portfolio.ui.tests ---
[INFO] 
[INFO] --- tycho-packaging-plugin:1.5.1:validate-version (default-validate-version) @ name.abuchen.portfolio.ui.tests ---
[INFO] 
[INFO] --- maven-checkstyle-plugin:3.1.0:check (validate) @ name.abuchen.portfolio.ui.tests ---
[INFO] Starting audit...
Audit done.
[INFO] 
[INFO] --- jacoco-maven-plugin:0.8.5:prepare-agent (prepare-agent) @ name.abuchen.portfolio.ui.tests ---
[INFO] tycho.testArgLine set to -javaagent:/home/user/.m2/repository/org/jacoco/org.jacoco.agent/0.8.5/org.jacoco.agent-0.8.5-runtime.jar=destfile=/data/portfolio/name.abuchen.portfolio.ui.tests/target/jacoco.exec
[INFO] 
[INFO] --- maven-resources-plugin:3.1.0:resources (default-resources) @ name.abuchen.portfolio.ui.tests ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /data/portfolio/name.abuchen.portfolio.ui.tests/src/main/resources
[INFO] 
[INFO] --- tycho-compiler-plugin:1.5.1:compile (default-compile) @ name.abuchen.portfolio.ui.tests ---
[INFO] Compiling 4 source files to /data/portfolio/name.abuchen.portfolio.ui.tests/target/classes
[INFO] 
[INFO] --- maven-resources-plugin:3.1.0:testResources (default-testResources) @ name.abuchen.portfolio.ui.tests ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /data/portfolio/name.abuchen.portfolio.ui.tests/src/test/resources
[INFO] 
[INFO] --- target-platform-configuration:1.5.1:target-platform (default-target-platform) @ name.abuchen.portfolio.ui.tests ---
[INFO] 
[INFO] --- tycho-packaging-plugin:1.5.1:package-plugin (default-package-plugin) @ name.abuchen.portfolio.ui.tests ---
[INFO] Building jar: /data/portfolio/name.abuchen.portfolio.ui.tests/target/name.abuchen.portfolio.ui.tests-0.48.1-SNAPSHOT.jar
[INFO] 
[INFO] --- tycho-p2-plugin:1.5.1:p2-metadata-default (default-p2-metadata-default) @ name.abuchen.portfolio.ui.tests ---
[INFO] 
[INFO] --- tycho-surefire-plugin:1.5.1:test (default-test) @ name.abuchen.portfolio.ui.tests ---
[INFO] Expected eclipse log file: /data/portfolio/name.abuchen.portfolio.ui.tests/target/work/data/.metadata/.log
[INFO] Command line:
	[/opt/Oracle_Java/jre1.8.0_192/bin/java, -Dosgi.noShutdown=false, -Dosgi.os=linux, -Dosgi.ws=gtk, -Dosgi.arch=x86_64, -javaagent:/home/user/.m2/repository/org/jacoco/org.jacoco.agent/0.8.5/org.jacoco.agent-0.8.5-runtime.jar=destfile=/data/portfolio/name.abuchen.portfolio.ui.tests/target/jacoco.exec, -Dosgi.clean=true, -jar, /home/user/.m2/repository/p2/osgi/bundle/org.eclipse.equinox.launcher/1.5.700.v20200207-2156/org.eclipse.equinox.launcher-1.5.700.v20200207-2156.jar, -data, /data/portfolio/name.abuchen.portfolio.ui.tests/target/work/data, -install, /data/portfolio/name.abuchen.portfolio.ui.tests/target/work, -configuration, /data/portfolio/name.abuchen.portfolio.ui.tests/target/work/configuration, -application, org.eclipse.tycho.surefire.osgibooter.headlesstest, -testproperties, /data/portfolio/name.abuchen.portfolio.ui.tests/target/surefire.properties]
Running name.abuchen.portfolio.ui.views.SecurityChartRangeTest
Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.11 s - in name.abuchen.portfolio.ui.views.SecurityChartRangeTest
testRangeIntersection(name.abuchen.portfolio.ui.views.SecurityChartRangeTest)  Time elapsed: 0.009 s
testRangeIfIntervalEndsAfter(name.abuchen.portfolio.ui.views.SecurityChartRangeTest)  Time elapsed: 0 s
testRangeIfIntervalEndsOnGap(name.abuchen.portfolio.ui.views.SecurityChartRangeTest)  Time elapsed: 0.001 s
testRangeIfIntervalStartsBefore(name.abuchen.portfolio.ui.views.SecurityChartRangeTest)  Time elapsed: 0 s
testRangeIfIntervalDoesNotIntersect(name.abuchen.portfolio.ui.views.SecurityChartRangeTest)  Time elapsed: 0.001 s
testRangeIfIntervalStartsOnGap(name.abuchen.portfolio.ui.views.SecurityChartRangeTest)  Time elapsed: 0 s
testRangeIfIntervalStartsAndEndsOnGap(name.abuchen.portfolio.ui.views.SecurityChartRangeTest)  Time elapsed: 0 s
Running name.abuchen.portfolio.ui.views.SimpleMovingAverageTest
Tests run: 5, Failures: 0, Errors: 3, Skipped: 0, Time elapsed: 0.126 s <<< FAILURE! - in name.abuchen.portfolio.ui.views.SimpleMovingAverageTest
testSufficientPriceDataStartDate(name.abuchen.portfolio.ui.views.SimpleMovingAverageTest)  Time elapsed: 0.116 s  <<< ERROR!
java.lang.UnsatisfiedLinkError: 
Could not load SWT library. Reasons: 
	no swt-pi4-gtk-4934r6 in java.library.path
	no swt-pi4-gtk in java.library.path
	Can't load library: /home/user/.swt/lib/linux/x86_64/libswt-pi4-gtk-4934r6.so
	Can't load library: /home/user/.swt/lib/linux/x86_64/libswt-pi4-gtk.so

```
If I install Ecplise 2020-06 it fails to start
```
!SESSION 2020-09-03 08:44:17.789 -----------------------------------------------
eclipse.buildId=4.16.0.I20200604-0540
java.version=1.8.0_192
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Framework arguments:  -product org.eclipse.epp.package.java.product
Command-line arguments:  -os linux -ws gtk -arch x86_64 -product org.eclipse.epp.package.java.product -data /data/workspace

!ENTRY org.eclipse.osgi 4 0 2020-09-03 08:44:22.009
!MESSAGE Application error
!STACK 1
java.lang.UnsatisfiedLinkError: Could not load SWT library. Reasons: 
	no swt-pi4-gtk-4934r6 in java.library.path
	no swt-pi4-gtk in java.library.path
	Can't load library: /home/user/.swt/lib/linux/x86_64/libswt-pi4-gtk-4934r6.so
	Can't load library: /home/user/.swt/lib/linux/x86_64/libswt-pi4-gtk.so

	at org.eclipse.swt.internal.Library.loadLibrary(Library.java:342)
	at org.eclipse.swt.internal.Library.loadLibrary(Library.java:256)
	at org.eclipse.swt.internal.gtk.OS.<clinit>(OS.java:90)
	at org.eclipse.swt.internal.Converter.wcsToMbcs(Converter.java:209)
	at org.eclipse.swt.internal.Converter.wcsToMbcs(Converter.java:155)
	at org.eclipse.swt.widgets.Display.<clinit>(Display.java:164)
	at org.eclipse.ui.internal.Workbench.createDisplay(Workbench.java:760)
	at org.eclipse.ui.PlatformUI.createDisplay(PlatformUI.java:166)
	at org.eclipse.ui.internal.ide.application.IDEApplication.createDisplay(IDEApplication.java:180)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:123)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:657)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:594)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1447)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1420)

```

Will investigate further. I now at least have an area to look into more...

**Comment by cmaoling** [comment]
For reference: https://community.talend.com/s/feed/0D53p00007vCmfpCAC

> This error on start:
> 
>  
> 
> java.lang.UnsatisfiedLinkError: Could not load SWT library. Reasons:
> 
> no swt-pi4-gtk-4922r32 in java.library.path
> 
> no swt-pi4-gtk in java.library.path
> 
> /home/ubuntu/.swt/lib/linux/x86_64/libswt-pi4-gtk-4922r32.so: libgtk-3.so.0: cannot open shared object file: No such file or directory
> 
> Can't load library: /home/ubuntu/.swt/lib/linux/x86_64/libswt-pi4-gtk.so
> 
>

**Comment by cmaoling** [comment]
https://www.cnblogs.com/emanlee/p/13341691.html
pointed me to https://stackoverflow.com/questions/2706222/create-cross-platform-java-swt-application/3204032#3204032
May it be a general issue because PP is cross platform Mac/Win/Linux?
Anyone else got PP w/ 2020-06 on Ubuntu running recently?

**Comment by buchen** [comment]
I testet PP on Ubuntu 20.04 LTS, but I did not *build* it

**Comment by cmaoling** [comment]
**I was able to successfully build and run PP after installing the libgtk-3-0 package.**
Thanks for your help debugging this @buchen and @Ragas13 .
