### ISSUE TITLE
Unknown column layout data in "Earnings& Expenses"

### ISSUE THREAD

**Issue by cmaoling** [buchen/portfolio#1743]
**Describe the bug**
I get `org.eclipse.core.runtime.AssertionFailedException: assertion failed: Unknown column layout data` erros while browsing through the various options in "Earnings & Expenses"
In the error logs there is alway the last function being `createVehicleColumn`

**To Reproduce**
1. Go to 'Eardning & Expenses
2. Click on 'Month/Instrument'
3. Scroll through the "Dividends", "Interest" and Fees options
4. Click on several of the other options beside 'Month/Instrument'
4. See error evry-other time in average

like:
```
Wed Sep 09 13:13:18 GMT 2020
Internal Error

org.eclipse.core.runtime.AssertionFailedException: assertion failed: Unknown column layout data
	at org.eclipse.core.runtime.Assert.isTrue(Assert.java:113)
	at org.eclipse.jface.layout.AbstractColumnLayout.layoutTableTree(AbstractColumnLayout.java:194)
	at org.eclipse.jface.layout.AbstractColumnLayout.layout(AbstractColumnLayout.java:262)
	at org.eclipse.jface.layout.TableColumnLayout.updateColumnData(TableColumnLayout.java:110)
	at org.eclipse.jface.layout.AbstractColumnLayout.lambda$0(AbstractColumnLayout.java:76)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5685)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1423)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1449)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1428)
	at org.eclipse.swt.widgets.TableColumn.gtk_size_allocate(TableColumn.java:420)
	at org.eclipse.swt.widgets.Widget.windowProc(Widget.java:2268)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:5919)
	at org.eclipse.swt.internal.gtk.GTK.gtk_widget_size_allocate(Native Method)
	at org.eclipse.swt.widgets.Control.forceResize(Control.java:894)
	at org.eclipse.swt.widgets.Table.createItem(Table.java:745)
	at org.eclipse.swt.widgets.TableColumn.createWidget(TableColumn.java:199)
	at org.eclipse.swt.widgets.TableColumn.<init>(TableColumn.java:83)
	at org.eclipse.jface.viewers.TableViewerColumn.createColumn(TableViewerColumn.java:83)
	at org.eclipse.jface.viewers.TableViewerColumn.<init>(TableViewerColumn.java:61)
	at org.eclipse.jface.viewers.TableViewerColumn.<init>(TableViewerColumn.java:43)
**	at name.abuchen.portfolio.ui.views.earnings.EarningsPerMonthMatrixTab.createVehicleColumn(EarningsPerMonthMatrixTab.java:157)
**	at name.abuchen.portfolio.ui.views.earnings.EarningsPerYearMatrixTab.createColumns(EarningsPerYearMatrixTab.java:42)
**	at name.abuchen.portfolio.ui.views.earnings.EarningsPerMonthMatrixTab.updateColumns(EarningsPerMonthMatrixTab.java:294)
**	at name.abuchen.portfolio.ui.views.earnings.EarningsPerMonthMatrixTab.lambda$2(EarningsPerMonthMatrixTab.java:128)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at name.abuchen.portfolio.ui.views.earnings.EarningsViewModel.fireUpdateChange(EarningsViewModel.java:372)
	at name.abuchen.portfolio.ui.views.earnings.EarningsViewModel.recalculate(EarningsViewModel.java:230)
	at name.abuchen.portfolio.ui.views.earnings.EarningsViewModel.setMode(EarningsViewModel.java:188)
	at name.abuchen.portfolio.ui.views.earnings.EarningsView.lambda$1(EarningsView.java:107)
	at name.abuchen.portfolio.ui.util.SimpleAction.run(SimpleAction.java:43)
	at org.eclipse.jface.action.Action.runWithEvent(Action.java:474)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:579)
	at org.eclipse.jface.action.ActionContributionItem.lambda$5(ActionContributionItem.java:452)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5685)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1423)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4953)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4446)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1158)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1047)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.e4.ui.internal.workbench.swt.E4Application.start(E4Application.java:166)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:657)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:594)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1447)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1420)

```

or 
```
Wed Sep 09 13:09:07 GMT 2020
Internal Error

org.eclipse.core.runtime.AssertionFailedException: assertion failed: Unknown column layout data
	at org.eclipse.core.runtime.Assert.isTrue(Assert.java:113)
	at org.eclipse.jface.layout.AbstractColumnLayout.layoutTableTree(AbstractColumnLayout.java:194)
	at org.eclipse.jface.layout.AbstractColumnLayout.layout(AbstractColumnLayout.java:262)
	at org.eclipse.jface.layout.TableColumnLayout.updateColumnData(TableColumnLayout.java:110)
	at org.eclipse.jface.layout.AbstractColumnLayout.lambda$0(AbstractColumnLayout.java:76)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5685)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1423)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1449)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1428)
	at org.eclipse.swt.widgets.TableColumn.gtk_size_allocate(TableColumn.java:420)
	at org.eclipse.swt.widgets.Widget.windowProc(Widget.java:2268)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:5919)
	at org.eclipse.swt.internal.gtk.GTK.gtk_widget_size_allocate(Native Method)
	at org.eclipse.swt.widgets.Control.forceResize(Control.java:894)
	at org.eclipse.swt.widgets.Table.createItem(Table.java:745)
	at org.eclipse.swt.widgets.TableColumn.createWidget(TableColumn.java:199)
	at org.eclipse.swt.widgets.TableColumn.<init>(TableColumn.java:83)
	at org.eclipse.jface.viewers.TableViewerColumn.createColumn(TableViewerColumn.java:83)
	at org.eclipse.jface.viewers.TableViewerColumn.<init>(TableViewerColumn.java:61)
	at org.eclipse.jface.viewers.TableViewerColumn.<init>(TableViewerColumn.java:43)
	at name.abuchen.portfolio.ui.views.earnings.EarningsPerMonthMatrixTab.createVehicleColumn(EarningsPerMonthMatrixTab.java:157)
	at name.abuchen.portfolio.ui.views.earnings.EarningsPerQuarterMatrixTab.createColumns(EarningsPerQuarterMatrixTab.java:42)
	at name.abuchen.portfolio.ui.views.earnings.EarningsPerMonthMatrixTab.updateColumns(EarningsPerMonthMatrixTab.java:294)
	at name.abuchen.portfolio.ui.views.earnings.EarningsPerMonthMatrixTab.lambda$2(EarningsPerMonthMatrixTab.java:128)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at name.abuchen.portfolio.ui.views.earnings.EarningsViewModel.fireUpdateChange(EarningsViewModel.java:372)
	at name.abuchen.portfolio.ui.views.earnings.EarningsViewModel.recalculate(EarningsViewModel.java:230)
	at name.abuchen.portfolio.ui.views.earnings.EarningsView.notifyModelUpdated(EarningsView.java:91)
	at name.abuchen.portfolio.ui.editor.PortfolioPart.onRecalculationNeeded(PortfolioPart.java:372)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at name.abuchen.portfolio.ui.editor.ClientInput.setDirty(ClientInput.java:145)
	at name.abuchen.portfolio.ui.editor.ClientInput.lambda$10(ClientInput.java:589)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4928)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4449)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1158)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1047)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.e4.ui.internal.workbench.swt.E4Application.start(E4Application.java:166)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:657)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:594)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1447)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1420)


```

**Expected behavior**
No erroor

**Desktop (please complete the following information):**
 - OS: Linux
 - Version 0.48.1

**Comment by dfdario** [comment]
Present also on both 0.50.4 and test version:
Version: 0.50.5.202102152006 (feb 2021)
Platform: linux, x86_64
Java: 11.0.9.1+1-post-Debian-1deb10u2, Debian
[pp-error-2021-02-18.log](https://github.com/buchen/portfolio/files/6003465/pp-error-2021-02-18.log)

Windows version is not affected
