### ISSUE TITLE
Multiple columns missing in asset allocation view

### ISSUE THREAD

**Issue by StegSchreck** [buchen/portfolio#1748]
**Describe the bug**
Some columns are missing in the classification views.

**To Reproduce**
1. Go to any view in Classification (e.g. "Asset Allocation")
2. Check visible Columns
3. Multiple columns missing which are important for rebalancing the portfolio, e.g. "Soll %"

Creating a new view yields the same result. The Submenu for adding additional columns to the view does not contain the missing columns either.

**Expected behavior**
* Column "Soll %" visible
* Column for relative difference in % visible
* Column for absolute difference visible
* Column for graphical indicator of difference visible

**Screenshots**
![image](https://user-images.githubusercontent.com/9078002/92998618-0bda4f00-f51b-11ea-929a-dfedcd4369fb.png)

**Error protocol**
```
Sat Sep 12 17:05:52 CEST 2020
Problems occurred when invoking code from plug-in: "org.eclipse.equinox.app".

java.lang.NoClassDefFoundError: org/eclipse/swt/accessibility/AccessibleObject
	at org.eclipse.equinox.launcher.JNIBridge._takedown_splash(Native Method)
	at org.eclipse.equinox.launcher.JNIBridge.takeDownSplash(JNIBridge.java:173)
	at org.eclipse.equinox.launcher.Main.takeDownSplash(Main.java:2156)
	at org.eclipse.equinox.launcher.Main$SplashHandler.run(Main.java:122)
	at org.eclipse.core.runtime.internal.adaptor.DefaultStartupMonitor.applicationRunning(DefaultStartupMonitor.java:71)
	at org.eclipse.equinox.internal.app.EclipseAppHandle$1.run(EclipseAppHandle.java:279)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.applicationRunning(EclipseAppHandle.java:267)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1093)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1047)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.e4.ui.internal.workbench.swt.E4Application.start(E4Application.java:166)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:657)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:594)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1447)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1420)
Caused by: java.lang.ClassNotFoundException: org.eclipse.swt.accessibility.AccessibleObject
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 26 more


```

**Desktop (please complete the following information):**
 - OS: Manjaro Arch Linux
 - Version 0.48.1

**Comment by cmaoling** [comment]
I guess you need do select to the next sub selection view "Rebalancing":
![image](https://user-images.githubusercontent.com/11899631/93005449-3e9f3a00-f551-11ea-9b9c-245eb5d51a11.png)

In the the list view, these attributes are not available. Would be an enhancement to get them there IMHO...

**Comment by StegSchreck** [comment]
@cmaoling that works, thanks. I was under the impression it was available in the main table before. But maybe my memory deceives me.
