### ISSUE TITLE
Offene Punkte beim Style-Update (Tooltips)

### ISSUE THREAD

**Issue by sebasbaumh** [buchen/portfolio#1751]
Seit dem letzten Style-Update (Entwicklungsversion 0.48.2+) sind anscheinend die Tooltips kaputt bzw. falsch stilisiert.

Zum Beispiel hier beim Ertrag:
![PortfolioPerformance_2020-09-15_20-54-20](https://user-images.githubusercontent.com/670885/93252563-f4f36100-f795-11ea-87c3-01a8f70e2321.png)
Aber auch in den Kursdiagrammen:
![PortfolioPerformance_2020-09-15_20-57-26](https://user-images.githubusercontent.com/670885/93252671-181e1080-f796-11ea-858c-37facaf8c468.png)
Bzw. in so ziemlich allen Diagrammen, wo es welche gibt.

Bei den Widgets sind da auch noch kleinere Unregelmäßigkeiten:
![PortfolioPerformance_2020-09-15_21-00-41](https://user-images.githubusercontent.com/670885/93253013-92e72b80-f796-11ea-855c-f81ec4e9abb2.png)

Nur, falls das noch nicht aufgefallen ist 😉 
Bin mir nämlich nicht ganz sicher, ob das auf MacOS X auch so ausschaut.

Die zwei Meldungen erscheinen auch im Fehlerlog:

    Missing font for symbolic name org.eclipse.ui.workbench.TAB_TEXT_FONT
    Missing color for symbolic name org.eclipse.ui.workbench.INACTIVE_TAB_BG_END

Ansonsten sieht das neue eclipse Theme ziemlich gut und frisch aus - bin gespannt, was da noch kommt 👍 
Die Performance scheint soweit auch zu passen.

**Comment by DomBok** [comment]
Bei den ersten beiden liegt es daran, dass die Schriftfarbe weiß ist, was man dann auf weiß natürlich nicht mehr sieht.
Lässt sich recht einfach fixen, wenn man in der css für das weiße Profil beim Label die Schriftfarbe auf schwarz setzt.
Die farbige Markierung funktioniert nicht mehr, weil das gesamte Label halt in weiß oder schwarz dargestellt wird.

**Comment by buchen** [comment]
Vielen Dank für die Screenshots. Gerne mehr davon. Die Probleme schaue ich mir an. Es scheint mir als überschreibt die Styling Engine die manuell gesetzten Farben (der Tooltip müsste ja den Hintergrund der Datenreihe haben).
Könnt Ihr auch mal den Dark Mode ausprobieren? #973

**Comment by buchen** [comment]
Mit dem letzten Commit sollten die Tooltips wieder gut aussehen.

**Comment by sebasbaumh** [comment]
@DomBok ja, das denke ich auch - da passen einfach ein paar Farben noch nicht.

@buchen 
So, ich habe es gleich mal getestet.
Die Tooltips beim Ertrag und Kursdiagramm schauen gut aus.

Bei dem Widget für die Jahresrenditen sieht es eher schlechter aus:
![XGz0mtudbS](https://user-images.githubusercontent.com/670885/93734514-ccc29280-fbd9-11ea-9f37-a80d5f931086.png)

Das mit dem grauen Hintergrund ist bei einigen Controls zu sehen:
![PortfolioPerformance_8MIK1amg6a](https://user-images.githubusercontent.com/670885/93734729-bc5ee780-fbda-11ea-8583-e85ef95ccc91.png)


Im Fehlerlog taucht nur noch diese Meldung auf:

    Missing font for symbolic name org.eclipse.ui.workbench.TAB_TEXT_FONT

Allerdings taucht beim Öffnen der Performance-Ansicht eine Exception auf:

     Internal Error
    
    java.lang.NullPointerException
    	at name.abuchen.portfolio.ui.util.Colors.getTextColor(Colors.java:121)
    	at name.abuchen.portfolio.ui.util.swt.ColoredLabel.handlePaint(ColoredLabel.java:77)
    	at name.abuchen.portfolio.ui.util.swt.ColoredLabel$$Lambda$569/0000000000000000.handleEvent(Unknown Source)
    	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
    	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4213)
    	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1037)
    	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1061)
    	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1046)
    	at org.eclipse.swt.widgets.Composite.WM_PAINT(Composite.java:1616)
    	at org.eclipse.swt.widgets.Control.windowProc(Control.java:4797)
    	at org.eclipse.swt.widgets.Canvas.windowProc(Canvas.java:340)
    	at org.eclipse.swt.widgets.Display.windowProc(Display.java:4931)
    	at org.eclipse.swt.internal.win32.OS.DispatchMessage(Native Method)
    	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3628)
    	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1158)
    	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
    	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1047)
    	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
    	at org.eclipse.e4.ui.internal.workbench.swt.E4Application.start(E4Application.java:166)
    	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
    	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
    	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
    	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
    	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
    	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
    	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:657)
    	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:594)
    	at org.eclipse.equinox.launcher.Main.run(Main.java:1447)


Und danach sind die monatlichen Erträge kaputt (die Farbe, 0,00 stimmt für den gewählten Monat):
![PortfolioPerformance_WfUx0RHd7E](https://user-images.githubusercontent.com/670885/93734637-56726000-fbda-11ea-9e5c-0bf4af5a367b.png)

Ich schau mir den Darkmode mal an und gebe mal Feedback bei dem anderen Ticket.

**Comment by buchen** [comment]
Ok, ok, I fixed some of the issues. I did not look into the preferences yet.

**Comment by buchen** [comment]
I hope once this is over we not only have a dark mode, but it is also fairly easy to change the font size. The theming is a lot more work than I thought...

**Comment by sebasbaumh** [comment]
Danke für die gute Arbeit! 😄 
Die `NullPointerException` ist weg und das Fehlerlog ist sauber.
Bei den Farben sind noch ein paar Baustellen, aber es ist definitiv erst einmal benutzbar.

Die Schrift bei den Heatmaps müsste einen kleinen Tick größer sein und wie oben beschrieben passen die Farben nicht immer.
Ich schau da vielleicht mal rein, bin mir nur nicht sicher, wie ich das sauber anpassen kann - ohne, dass es dann auf anderen Plattformen schlechter wird. Oder ist das CSS-Styling zwischen den Plattformen an sich recht stabil?

**Comment by sebasbaumh** [comment]
Ich habe die Schrift/Farbe mal im PR #1759 angepasst.
Leider gibt es bei der Höhe nur ganzzahlige Schritte, gefühlt könnte es auch -1.5 für "smaller" sein.
