### ISSUE TITLE
Taxonomy -> Regions not does not work in English - crashed and not translated

### ISSUE THREAD

**Issue by tixona** [buchen/portfolio#1853]
**Describe the bug**
Adding Taxonomy -> Regions not does not work in English.

**To Reproduce**
1. Go to 'Help' -> 'Preferences'
2. Click on 'Language'
3. Select 'English' as language
4. Click 'Apply and Close'
5. Restart Portfolio Performance
6. Open Depot
7. Add Taxonomie 'Regions' (no translation given)
8. Crashed

**Expected behavior**
Same regions as in german without crash.

**Screenshots**
![image](https://user-images.githubusercontent.com/199562/101295875-76501200-3820-11eb-8c55-108bf494324b.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro - Version 20H2 (Build 19042.630)
 - Version: 0.49.3 (Nov 2020)
 - Platform: win32, x86_64
 - Java: 11.0.4+11-LTS, Azul Systems, Inc.

**Error Log**
`Internal Error
java.lang.IllegalArgumentException
	at name.abuchen.portfolio.model.TaxonomyTemplate.buildFromTemplate(TaxonomyTemplate.java:108)
	at name.abuchen.portfolio.model.TaxonomyTemplate.build(TaxonomyTemplate.java:67)
	at name.abuchen.portfolio.ui.editor.Navigation.lambda$17(Navigation.java:465)
	at name.abuchen.portfolio.ui.util.SimpleAction.run(SimpleAction.java:43)
	at org.eclipse.jface.action.Action.runWithEvent(Action.java:474)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:579)
	at org.eclipse.jface.action.ActionContributionItem.lambda$4(ActionContributionItem.java:413)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4213)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1037)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4030)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3630)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1158)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1047)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.e4.ui.internal.workbench.swt.E4Application.start(E4Application.java:166)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:657)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:594)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1447)`

**Comment by Nirus2000** [comment]
Pull request is done.

**Comment by buchen** [comment]
Fixed.
