### ISSUE TITLE
[meta] Blog: technical changes to PP source code

### ISSUE THREAD

**Issue by buchen** [buchen/portfolio#1914]
As more people are contributing to the code base of PP, I will use this issue to "blog" about technical changes to the source code. It is not meant to discuss features, but library upgrades, changes to the target platform, etc.

**Comment by buchen** [comment]
Today's changes update the master branch to the 2020-12 release of Eclipse (4.18).
**Make sure to open and re-set the target platform. And you need Java11**

Here are some things to note:
* This version includes all macOS Big Sur fixes and should re-enable the auto update on the macOS platform.
* Eclipse now requires Java 11. I have changes the environment to JavaSE-11 in the Manifest files accordingly. However, because I want to be able to downport the ```name.abuchen.portfolio``` to the 32bit branch, this bundle remains on Java8
* With Eclipse 2020-12, we finally have typed Eclipse Databinding API. That allows me to remove a lot of restriction annotations. At the time of writing, the "Problems" view is finally empty again (the "other" category contains SonarLink and Inifitest warnings which I typically only fix if I happen to touch the source code)
<img width="336" alt="Bildschirmfoto 2020-12-28 um 10 20 43" src="https://user-images.githubusercontent.com/587976/103203907-5929d300-48f6-11eb-8b54-a1395b5f07c0.png">

**Comment by chrisaut** [comment]
Hi @buchen 

Good idea with this mini-blog.
Unfortunately with latest master I get tons of errors:

![image](https://user-images.githubusercontent.com/8252355/103206365-f9cec180-48fb-11eb-9242-9e03797166ab.png)

**Comment by buchen** [comment]
> Unfortunately with latest master I get tons of errors

🤔 I would start looking at three things:
* First: did the new target platform properly resolve? Open ```portfolio-target-definition/portfolio-target-definition.target``` and reload (top left button in the editor), if necessary.
* Second: Is the right Java library on the path? Right-click on project -> Properties -> Java Build Path -> Libraries (Tab)
* Third: Is Java11 the default JRE? Open the Preferences -> Java -> Installed JREs -> checkbox next to Java11 ticked

**Comment by chrisaut** [comment]
> * First: did the new target platform properly resolve? Open `portfolio-target-definition/portfolio-target-definition.target` and reload (top left button in the editor), if necessary.

Ah ok, yes that fixed a ton of issues, only one remains:
![image](https://user-images.githubusercontent.com/8252355/103209522-9f396380-4903-11eb-8e99-27c4e04cd2af.png)


> * Second: Is the right Java library on the path? Right-click on project -> Properties -> Java Build Path -> Libraries (Tab)
![image](https://user-images.githubusercontent.com/8252355/103209568-b6785100-4903-11eb-85e7-2916e95e34f2.png)

It says JavaSE-1.8 I guess? Should it be 11?

> * Third: Is Java11 the default JRE? Open the Preferences -> Java -> Installed JREs -> checkbox next to Java11 ticked

Hmm...if I can decypher this correctly I have Java 15?
![image](https://user-images.githubusercontent.com/8252355/103209858-5afa9300-4904-11eb-838c-cc9fdde04684.png)

**Comment by buchen** [comment]
> If I instead try Portfolio Performance Java 11 .... it errors out with

The problem is: this launch configuration is specific to my macOS platform. You would have to "fix it" for your Windows platform (open the Launch Configuration and on the "Plug-ins" tab select "Add required Plug-ins").

This is actually the reason for https://github.com/buchen/portfolio/issues/1913 - it should create launch configurations independent of the platform.

Alas, that is where the missing ```org.eclipse.ant.core.antRunner``` is reported.
If I open the ```launches.lc``` file, what applications do you get? (Press Ctrl-Space for suggestions)
<img width="585" alt="Bildschirmfoto 2020-12-28 um 16 02 13" src="https://user-images.githubusercontent.com/587976/103223276-28619200-4926-11eb-900a-c5bba8677f5f.png">

Your Java Version looks fine.

**Comment by chrisaut** [comment]
![image](https://user-images.githubusercontent.com/8252355/103224061-7dea6e80-4927-11eb-9ea8-0db540f8d9cb.png)

Perhaps rename it "... (MacOS)" then? Or are you saying with #1913 this should also work for windows?

**Comment by buchen** [comment]
> Or are you saying with #1913 this should also work for windows?

Yes, that should work for Windows too (as it is dynamically resolving the dependencies).

But first we need to get it working. Very strange that offers antRunner as a proposal, but then errors on it.
Which Eclipse version are you running?

**Comment by chrisaut** [comment]
> Which Eclipse version are you running?

Eclipse IDE for Java Developers (includes Incubating components)
Version: 2020-12 (4.18.0)
Build id: 20201210-1552
OS: Windows 10, v.10.0, x86_64 / win32
Java version: 15.0.1

**Comment by inv-trad** [comment]
After removing `antRunner`, typing Ctrl-Space to get suggestions and selecting antRunner once again, the error disappears in my installation.

**Comment by damarvin** [comment]
Hi,
And yes, there should be a channel for fast syncing on issues (maybe in addition to "Blog: technical changes...".
I would like to look into the (more general) csv import, and was wondering how to build PP (on Windows), preferably with mvn and Java11 only  ⇒ @buchen Is the **README.md** still correct? Travis is replaced? By Github Actions?

**Comment by chrisaut** [comment]
> After removing `antRunner`, typing Ctrl-Space to get suggestions and selecting antRunner once again, the error disappears in my installation.

Lol, amazingly this works. Seems like a bug with Ecplise?

**Comment by buchen** [comment]
> I [...] was wondering how to build PP (on Windows), preferably with mvn and Java11 only ⇒ @buchen Is the README.md still correct? Travis is replaced? By Github Actions?

You can build PP fully with mvn only. But I assume you might not be able to build the Linux and macOS versions on Windows. But other than that, I would think you can build the full distribution on Windows as well.

To check the build, I run from the command line
```
mvn clean verify
```

This will not build all products - in particular not the "distributions" which includes the Java Runtime. To do so, run:
```
mvn clean verify -Ppackage-distro
```
You should find all ZIPs in the ```portfolio-product/target/products``` folder.


And, yes, I moved to [Github Actions](https://github.com/buchen/portfolio/actions) a while ago. I fixed the README file.

If you check the [workflow definition](https://github.com/buchen/portfolio/blob/master/.github/workflows/main.yml), I am running three builds
* ```mvn verify``` (if a pull request is build)
* ```mvn verify sonar:sonar``` (on the master branch - to report to [Sonarqube](https://sonarcloud.io/dashboard?id=name.abuchen.portfolio%3Aportfolio-app))
* ```mvn verify -pl :portfolio-target-definition,:name.abuchen.portfolio,:name.abuchen.portfolio.tests -am -amd``` (to build and test only the name.abuchen.portfolio bundle with Java8)

There are a couple other flags in the build - which I use locally to sign the build result: with a Java Code Signing certificate and an Apple developer certificate.


> build_installer.sh

I am not using this file at the moment. The idea was to have an EXE installer instead of a ZIP on Windows. However, I had troubles with the administration mode and the updates. I could try this again, though. At the moment, the code is checking if the user has write permissions to the install directly and asks the user to run PP "as administrator" if not (only for the update, of course).

**Comment by damarvin** [comment]
Thanks a lot!
This works nicely in Ubuntu, and I can start the built exe in Windows.

_But_ running `mvn` under Windows does not get over the `<evaluateBeanshell/>` **`<condition/>`** with `${project.basedir}`, as it gives the Windows path with raw backslashes and fails before you have a chance to replace them with doubled ones.
@buchen Not sure, what you are testing there, but for maven builds in Windows this check needs to be off, or be fixed by a correct Windows paths evaluation, or...? Is there something else of https://maven.apache.org/enforcer/enforcer-rules/index.html You could use?

**Comment by buchen** [comment]
> Not sure, what you are testing there, but for maven builds in Windows this check needs to be off, or be fixed by a correct Windows paths evaluation, or...?

@damarvin Well, obviously I am not testing the build on Windows... 🙃  Every once in a while I copy the Windows build result to a virtual machine and run PP there. I just assumed the build runs on Windows as well...

You could try running it with ```-Denforcer.skip=true``` to skip that section. Or you can try if we can fix the bean shell condition to something like ```java.nio.file.Paths.get("${project.basedir}/".replace("\\", "/"),```.
If that works, can you create a pull request?

**Comment by damarvin** [comment]
Unfortunately this seems to be a **bug in apache/maven-enforcer**.
I only found https://issues.apache.org/jira/browse/MENFORCER-100, which was auto-closed,
or https://stackoverflow.com/questions/63263586/maven-enforcer-how-to-access-maven-properties-from-beanshell-rule neither with a solution so far.

Already
```
    <evaluateBeanshell>
        <condition>
            print(java.nio.file.Paths.get("${project.basedir}/".replace("\\", "/"));
            1==1
        </condition>
    </evaluateBeanshell>
```
fails with `Couldn't evaluate condition...` as `${project.basedir}` is seamingly taken as a Java string directly, w/o escaping the backslashes.
While the `message` part
```
    <evaluateBeanshell>
        <condition>
            1==0
        </condition>
        <message>condition failed, project.basedir=${project.basedir}</message>
    </evaluateBeanshell>
```
logs the Windows path correctly:
```
    [WARNING] Rule 2: org.apache.maven.plugins.enforcer.EvaluateBeanshell failed with message:
    condition failed, project.basedir=C:\Users\me\git\portfolio\portfolio-app
```
Others gave up here as well: https://github.com/quarkusio/quarkus/pull/6335 :(
So I raised https://issues.apache.org/jira/browse/MENFORCER-370.
And thank You for the `-Denforcer.skip=true` hint.

**Comment by damarvin** [comment]
Just to inform, in **Windows**, with `JAVA_HOME` pointing to an 11.0.9.1 OJDK installation:
`C:\Users\me\git\portfolio>mvn -f portfolio-app\pom.xml -Denforcer.skip=true clean verify -Ppackage-distro`
works well. Built PortfolioPerformance.exe runs fine.

You migth want to update the main **readme.md**.

**Comment by buchen** [comment]
FYI, with #1932, the precision of shares and quotes would be added to 8 digits.

**Comment by buchen** [comment]
With the latest commit, I have refactored the "information pane" in the views - the lower part where the historical prices, transactions, security chart, etc. are shown. I wanted to make the [detail pages re-usable](https://github.com/buchen/portfolio/blob/master/name.abuchen.portfolio.ui/src/name/abuchen/portfolio/ui/views/panes/InformationPanePage.java) across multiple views. The area can be hidden with Strl-L (or Command-L on macOS).

For example, if you click in the holdings chart on one of the pies, details for the security are to be shown. The same is available in the statement of assets view now.

If you sync your local project to the latest commit, please give it a go and test it. I had to shuffle quite some code around which makes it easy to introduce bugs.

**Comment by Nirus2000** [comment]
Hallo @buchen 
I took a look and somehow calling it with the "STRL+L" does not work. I also think that the key combination would not be so practical with one hand.
STRL+I for information would be an alternative...

Maybe it would also be good if in the navigation menu the "ShortCuts" are to be seen, or a tab, in which all "ShortCuts" are shown.

**Comment by buchen** [comment]
Have a look at #2363 - I have drafted an implementation using protocol buffers to the store the data in a binary format. I knew XML was slow, but I did not expect it to be that slow.

**Comment by buchen** [comment]
PP dependencies are now updated to Eclipse 2021-09 release. This allows us to support the Apple Silicon M1 build. You have to update the target platform in your Eclipse installation

**Comment by eztam-** [comment]
Hi all,
I'm a very happy user of PP for many years and now it's time for me to giving back to the project and to contribute. I'm having plenty of time in the next two weeks that I'd like to use, to support the project. I'd be happy if you could help me to identify some new joiner friendly issues to work on (be it in the area of development, translation or design). I just started to get familiar with the code and submitted already my first PR [#2773](https://github.com/buchen/portfolio/pull/2773/).

Thanks!
Mat

**Comment by buchen** [comment]
With commit 9f695b36474642fb2408bcffa5f5e3b7cd5b7714 I have updated to Eclipse 2022-03.

The basic steps to update your workspace:
* open the target platform and "reload"
* re-generate the LCDSL run configurations

**Comment by Nirus2000** [comment]
Nice 👍🏻 
I have tested once...
![grafik](https://user-images.githubusercontent.com/45203494/164960839-6ce39563-db1d-4231-8a26-129c0b375b92.png)

**Comment by tquellenberg** [comment]
For me this warnings disappeared after closing and reopening the "portfolio-app" project in eclipse. 

Looks fine with MacOS and Wndows 10.

**Comment by buchen** [comment]
I have created a new branch [feature_java17](https://github.com/buchen/portfolio/tree/feature_java17) move PP to Java17. It includes updates to Java17, Eclipse 2022-12, and Tycho 3.0.1.

The two big changes are:
* the target platform can now contain references to Maven artifacts directly --> therefore the separate portfolio-deps projects is not necessary. There are 2 dependencies why we still need our own Maven repository but they hardly ever change (the old SWTChart library and the TreeMap SWT implementation)
* I had to refactor the code and move some Test helper classes to its own bundle. When updating, you need to add this new project to your workspace

**Comment by buchen** [comment]
The error message says:

> Der Import name.abuchen.portfolio.junit kann nicht aufgelöst werden

That is exactly the new project I created in order to refactor the test classes. It was necessary, because otherwise the name.abuchen.portfolio bundle is re-exporting test classes which led to errors.

Select in the menu "File" -> "Import..." -> "Existing projects into workspace" -> navigate to your local directory where you have the git checkout -> pick "name.abuchen.portfolio.junit"

**Comment by Nirus2000** [comment]
There are no embedded projects in the workspace...

![grafik](https://user-images.githubusercontent.com/45203494/210269396-7dd2aac8-1966-4810-bc6e-9cf2e468954f.png)

**Comment by buchen** [comment]
FYI: With f66332813f4e9e0f141afbc1058e687b0298a895, the google Protobuf library has been updated.

Make sure you update your project configuration by
* reloading the target platform (open the file, let it resolve, then click "reload" at the top right corner)
* rebuild the run configuration (open the launch configuration and right-click "re-generate launch configuration")

**Comment by buchen** [comment]
@OnkelDok @Nirus2000 - other window testers:

I have extended the dashboard to show a "jump to view" button only if the mouse hovers over the chart. See the short video below. It is only in the latest commit on master and (for now) only for the new dividend charts (add widgets -> earnings -> earnings per month/year/quarter). 

**Can one of you test how this behaves on Windows?**

https://github.com/buchen/portfolio/assets/587976/248b6d74-4bd5-4f6c-abdd-083a37f7cce9

**Comment by OnkelDok** [comment]
> **Can one of you test how this behaves on Windows?**

Here a video of my test:

https://github.com/buchen/portfolio/assets/90478568/9280f225-6421-427a-844c-d1b0e39ed74e

The style in darkmode is not the same as the permanent button of the performance diagram.
And for me the delay is not necessary. The first time I tested the function, it felt a little strange when there is no delay on hover start and after mouse leaves the chart.

**Comment by buchen** [comment]
Thanks @OnkelDok for testing. I'll try to fix the style in dark mode.

The delay is necessary because the mouse move listener is attached to multiple widgets (the chart, the plot area, the title, the composite). If I do not add the delay, it would hide the button when moving from the plot to the chart - and that results in flickering.

**Comment by buchen** [comment]
Eclipse Core has been updated to 4.27 (March 2023) version.

Same procedure as every time:
* open target platform in target platform editor, let it load (takes time), click "reload target platform" on the top right
* open the launch configuration view, right-click "re-generate Eclipse launch configuration"

**Comment by buchen** [comment]
I have updated to the 4.28 version (release 14 June 2023).

Same procedure as every time:
* open target platform in target platform editor, let it load (takes time), click "reload target platform" on the top right
* open the launch configuration view, right-click "re-generate Eclipse launch configuration"

I also updated my Eclipse installation to 2023-06 version to match the platform.


When running the unit tests, I get this error message. When clicking "continue" the tests run fine. The mentioned plugins are about Junit5 (but PP is using Junit4). I have no idea (yet) how to get rid of this error dialog other than adding _all_ plugins of the target platform to the launch configuration.

<img width="404" alt="Bildschirmfoto 2023-06-16 um 09 52 35" src="https://github.com/buchen/portfolio/assets/587976/3ebc1c69-ec17-4a33-b87c-b3130416ca25">

**Comment by buchen** [comment]
Please checkout #3458 about transferring the repository to the [portfolio-performance](https://github.com/portfolio-performance) organization:

> After 11 years, the project has outgrown my personal GitHub account. Transferring it to an organization allows better management of collaborators, projects, issues, help pages, etc. Moreover, it offers a fresh start for the list of open issues, resolving past mismanagement.

**Comment by buchen** [comment]
The repository has been transferred (noticed the new URL in your browser). I updated my local clone by running

```
git remote set-url origin https://github.com/portfolio-performance/portfolio.git
```

Depending on your setup, you'll need to replace the remote name with the one you use in your copy.

**Comment by buchen** [comment]
FYI, I have updated the Orbit dependencies (from the March 2022 to the May 2023 repository) with commit e30de802472f260857c2ecba66ee8dc50c080fd1

Same procedure as every time:

* open target platform in target platform editor, let it load (takes time), click "reload target platform" on the top right
* open the launch configuration view, right-click "re-generate Eclipse launch configuration"

**Comment by buchen** [comment]
With merge #3487, PP is using Tycho 4.x.
To build locally with Maven, you need Maven 3.9.x

**Comment by buchen** [comment]
Out of an forum conversation with @OnkelDok, I have create a new tag to categorize issues: [[meta]](https://github.com/portfolio-performance/portfolio/labels/%5Bmeta%5D). The idea is to use for all meta discussions (how do we want to work? How to prioritize certain changes? Does it make sense to implement something like this?) which are not on a level of a bug or concrete feature.

**Comment by Nirus2000** [comment]
Hello @buchen 
I can't get Eclipse to run at all after the update.... Here my Error.log
PDE is installed... !
`
!SESSION 2023-09-17 10:10:36.923 -----------------------------------------------
eclipse.buildId=unknown
java.version=17.0.6
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=de_DE
Framework arguments:  -version 3 -port 58678 -testLoaderClass org.eclipse.jdt.internal.junit4.runner.JUnit4TestLoader -loaderpluginname org.eclipse.jdt.junit4.runtime -testNameFile C:\Users\Nirus\AppData\Local\Temp\testNames3732117043112969719.txt -application org.eclipse.pde.junit.runtime.nonuithreadtestapplication -testApplication org.eclipse.pde.junit.runtime.coretestapplication -testpluginname name.abuchen.portfolio
Command-line arguments:  -version 3 -port 58678 -testLoaderClass org.eclipse.jdt.internal.junit4.runner.JUnit4TestLoader -loaderpluginname org.eclipse.jdt.junit4.runtime -testNameFile C:\Users\Nirus\AppData\Local\Temp\testNames3732117043112969719.txt -application org.eclipse.pde.junit.runtime.nonuithreadtestapplication -testApplication org.eclipse.pde.junit.runtime.coretestapplication -dev file:D:/Portfolio/.git/.metadata/.plugins/org.eclipse.pde.core/PortfolioPerformance_Tests/dev.properties -os win32 -ws win32 -arch x86_64 -testpluginname name.abuchen.portfolio

!ENTRY org.eclipse.pde.junit.runtime 4 0 2023-09-17 10:10:38.513
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: org.eclipse.pde.junit.runtime [1190]
  Unresolved requirement: Require-Bundle: org.eclipse.core.runtime; bundle-version="[3.29.0,4.0.0)"

	at org.eclipse.osgi.container.Module.start(Module.java:463)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel$2.run(ModuleContainer.java:1852)
	at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor$1$1.execute(EquinoxContainerAdaptor.java:136)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1845)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1786)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1750)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1672)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:345)

!ENTRY org.eclipse.pde.junit.runtime 2 0 2023-09-17 10:10:38.588
!MESSAGE Could not resolve module: org.eclipse.pde.junit.runtime [1190]
  Unresolved requirement: Require-Bundle: org.eclipse.core.runtime; bundle-version="[3.29.0,4.0.0)"


!ENTRY org.eclipse.osgi 4 0 2023-09-17 10:10:38.589
!MESSAGE Anwendungsfehler
!STACK 1
java.lang.RuntimeException: Die Anwendung {0} konnte nicht in der Registry gefunden werden. Die verfügbaren Anwendungen sind: org.eclipse.ant.core.antRunner, org.eclipse.e4.ui.workbench.swt.E4Application, org.eclipse.e4.ui.workbench.swt.GenTopic, org.eclipse.equinox.app.error, org.eclipse.equinox.p2.garbagecollector.application, org.eclipse.equinox.p2.publisher.InstallPublisher, org.eclipse.equinox.p2.publisher.EclipseGenerator, org.eclipse.equinox.p2.publisher.ProductPublisher, org.eclipse.equinox.p2.publisher.FeaturesAndBundlesPublisher, org.eclipse.equinox.p2.touchpoint.natives.nativePackageExtractor
	at org.eclipse.equinox.internal.app.EclipseAppContainer.startDefaultApp(EclipseAppContainer.java:252)
	at org.eclipse.equinox.internal.app.MainApplicationLauncher.run(MainApplicationLauncher.java:33)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1440)

`

**Comment by buchen** [comment]
FYI, with this change 5aac558dce5f36fbf3c396549702ab3e41c6f4d1 the target platform has been updated. You need to reload the target platform and re-generate the launch configurations.

I plan to push the update to Eclipse 4.30 soon (which then will require the same procedures)

**Comment by buchen** [comment]
With commit 6a10792794d67ecdeaa91dad8b71fe1a8b1be509 the target platform has been updated to Eclipse 4.30.
I also changed the definition to use the new Orbit repositories for (some of the) 3rd party libraries. The new structure should make it easier to keep the dependencies up-to-date and in sync with the Eclipse release train.

As always, you need to reload the target platform and re-generate the launch configurations.

**Comment by OnkelDok** [comment]
@buchen: Long time since I compiled and started PP via eclipse.
Today I had a try and it does not work. I updated Eclipse to ``2023-12 (4.30.0)``, ``Reloaded Target Platform`` and ``re-generated the launch configuration``.
I see a lot of errors in the ``Error Log``:
![grafik](https://github.com/portfolio-performance/portfolio/assets/90478568/2daa58af-9e2c-40cd-ba8f-f118f9085217)

When I try to run I get this message:
![grafik](https://github.com/portfolio-performance/portfolio/assets/90478568/b13fba2e-ef67-4883-8415-1a75b9295502)

And when I ``Continue`` then PP is started, but GUI is corrupt:
![grafik](https://github.com/portfolio-performance/portfolio/assets/90478568/e1a43052-a009-4468-81f7-a8a07f41b66d)
And a lot of errors are logged into console. Here some of their messages:
- ``org.osgi.framework.BundleException: Could not resolve module: org.eclipse.ecf.provider.filetransfer.httpclient5 [3267]``
- ``org.osgi.framework.BundleException: Could not resolve module: org.eclipse.ecf.provider.filetransfer.httpclient5.win32 [3268]``
- ``org.osgi.framework.BundleException: Could not resolve module: name.abuchen.portfolio [4327]``
- ``org.osgi.framework.BundleException: Could not resolve module: name.abuchen.portfolio.ui [4329]``
- ``java.io.IOException: Unable to resolve plug-in "platform:/meta/name.abuchen.portfolio.ui/custom.css"``

Any idea what I can do to get this working? Thanks a lot.

**Comment by buchen** [comment]
@OnkelDok 

The first screenshots are error from the Eclipse installation itself. To be honest, it reads a little like the installation itself is corrupt. If JDT (Java Development Tools) reports issues, then this is not good. Maybe consider a fresh install?

> When I try to run I get this message:
> Missing constaint: Require-Capability: osgi.serviceloader; (filter=org.slf4j.spi.SLF4JServiceProvider)' 

To my understanding, the bundle ```slf4j.simple``` should provide this capability. Of course, the generated launch configuration should select this plug-in, but can you check your run configuration.

I think the rest can then easily be follow-up errors - if one bundle is not activated, then some of the other are not either. And then the UI bundle is not active (only the bootstrap bundle which includes the menu).

**Comment by buchen** [comment]
I have added aggregate rows (header and/or footer) to the *Performance -> Securities* view. The aggregate rows show the sums of relevant columns (i.e. where a sum of values makes sense). If you can test and provide feedback, I'd be thankful.

**Comment by pfalcon** [comment]
> I have added aggregate rows (header and/or footer) to the Performance -> Securities view.

Looks good!

**Comment by buchen** [comment]
FYI, the Java21 branch is merged.

Java21 is the current long-term support version of Java. With the change, I have also updated the Eclipse Framework to the 2024-09 version (Eclipse 4.33). Eclipse itself requires Java 21 as well.

Make sure you have a Java 21 JDK installed locally for development. Personally, I am using the [Azul distribution](https://www.azul.com) because that is also the embedded Java Runtime (= the distribution of PP that includes a Java runtime).

If run into issues, please let me know.

**Comment by Nirus2000** [comment]
Yes and yes 👍🏻

**Comment by buchen** [comment]
I have now created a separate branch [master-eclipse430](https://github.com/portfolio-performance/portfolio/tree/master-eclipse430) that remains on Eclipse 4.30 (Eclipse 2023-12) and which can support Win7 and other older operating systems.

My idea is to downport changes to the PDF importers, model changes, and changes to the quote provider to the branch. For Version 0.72.2 that was very easy. If we refrain from using Java21 features for some time, it should be possible to support older version for some time.

This the update site to point Win 7 installations to:
```https://updates.portfolio-performance.info/portfolio-e430```

**Comment by buchen** [comment]
The master branch is now updated to Eclipse 2024-12 (Eclipse 4.34).

As always, you need to reload the target platform and re-generate the launch configurations.

**Comment by buchen** [comment]
FYI, I have just merged #4450 into the master branch.

You need to update your local development setup:
* There are 2 new plug-in projects. Import them by *File -> Import... -> Existing projects into Workspace -> [select your local git repository]*.
* Update the target platform. open target platform in target platform editor, let it load (takes time), click "reload target platform" on the top right
* open the launch configuration view, right-click "re-generate Eclipse launch configuration"

**Comment by buchen** [comment]
I have now merged a new feed implementation: the buid-in feed of historical data. That uses data for which I have redistribution rights. However, it requires an authenticated users (I can distribute to "members"). The authentication is done with a JWT token retrieved from an identity server. If you want to test locally in your development setup, drop me an email for configuration file.

**Comment by buchen** [comment]
While playing around with Claude Code, I noticed that the tool is not running the full tests because it takes too long (I guess consumes too much tokens). I found out that a lot of time is used to resolve the target platform if it includes the translations bundles. With 78061e6a1f1a41f8d9105f60307d86388fa088fd, I have created a Maven profile ```local-dev``` that uses a target platform without the translation bundles, skips code coverage, and protobuf generation. To enable this, there is now a copy of the default target platform.

Run it like this:
```
mvn clean verify -Plocal-dev
```

In the IDE, it does not seem to make a difference. The Eclipse IDE resolves the target platform once. And it builds incrementally.

**Comment by buchen** [comment]
I think I have figured out how to sign the Windows executables. 😄

Check out #5117 and report issue there.

**Comment by buchen** [comment]
I have updated the master branch to Eclipse 2025-09 - see b1fefdaaf03046c223652f7e8066ea61c7ef0fab

As always, you need to reload the target platform and re-generate the launch configurations.

**Comment by buchen** [comment]
I have updated the master branch to Eclipse 2025-12 - see 8a8911a43af1d6c083d32ca3b957ff6aee782022

Same procedure as every time: reload the target platform and re-generate the launch configurations.

**Comment by buchen** [comment]
I have updated the master branch to Eclipse 2026-06 - see bf7f69ea5d14b641070c1f966360b61884554ed2

Same procedure as every time: reload the target platform and re-generate the launch configurations.

If you see issues, please let me know. I did a first spot check on all three platforms and it looked good. But I also updated all dependencies, so there could be small gotchas
