### ISSUE TITLE
PortfolioPerformance not starting on Ubuntu 20.10 after upgrade to 0.50.1 

### ISSUE THREAD

**Issue by danielkr123** [buchen/portfolio#1978]
Hello,
I just upgraded from PortfolioPerformance 0.49.x to PortfolioPerformance 0.50.1 and now the program doesn't start any more.

**Error message upon startup:**
An error has occured. See the log file /home/daniel/.eclipse/734398179_linux_gtk_x86_64/configuration/-1610717976539.log

**Content of logfile 1610717976539.log:**

```
!SESSION Fri Jan 15 14:39:36 CET 2021 ------------------------------------------
!ENTRY org.eclipse.equinox.launcher 4 0 2021-01-15 14:39:36.556
!MESSAGE Could not find extension: reference:file:org.eclipse.osgi.compatibility.state_1.1.800.v20200511-1223.jar
!ENTRY org.eclipse.equinox.launcher 4 0 2021-01-15 14:39:36.566
!MESSAGE Could not find extension: reference:file:org.eclipse.osgi.nl_de_4.14.0.v20200113020001.jar
!ENTRY org.eclipse.equinox.launcher 4 0 2021-01-15 14:39:36.567
!MESSAGE Could not find extension: reference:file:org.eclipse.osgi.nl_es_4.14.0.v20200113020001.jar
!ENTRY org.eclipse.equinox.launcher 4 0 2021-01-15 14:39:36.569
!MESSAGE Could not find extension: reference:file:org.eclipse.osgi.nl_fr_4.14.0.v20200113020001.jar
!ENTRY org.eclipse.equinox.launcher 4 0 2021-01-15 14:39:36.570
!MESSAGE Could not find extension: reference:file:org.eclipse.osgi.nl_nl_4.14.0.v20200113020001.jar
!ENTRY org.eclipse.equinox.launcher 4 0 2021-01-15 14:39:36.572
!MESSAGE Could not find extension: reference:file:org.eclipse.osgi.nl_pt_4.14.0.v20200113020001.jar
!ENTRY org.eclipse.equinox.launcher 4 0 2021-01-15 14:39:36.722
!MESSAGE Exception launching the Eclipse Platform:
!STACK
java.lang.ClassNotFoundException: org.eclipse.core.runtime.adaptor.EclipseStarter
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:650)
        at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
        at org.eclipse.equinox.launcher.Main.run(Main.java:1461)
        at org.eclipse.equinox.launcher.Main.main(Main.java:1434)
```

**Steps to reproduce:**

```
cd /opt/
sudo wget https://github.com/buchen/portfolio/releases/download/0.50.1/PortfolioPerformance-0.50.1-linux.gtk.x86_64.tar.gz
sudo tar xzf PortfolioPerformance-0.50.1-linux.gtk.x86_64.tar.gz
/opt/portfolio/PortfolioPerformance
```

**Hints from the installation section of the website do not help (https://help.portfolio-performance.info/installation/):**

`sudo apt install libwebkitgtk-3.0-0 default-jre`
--> Paket no longer available on Ubuntu 20.10

`env SWT_GTK3=0 /opt/portfolio/PortfolioPerformance`
--> Same error

Version 0.49.x just worked fine.

I would be grateful for any advice on how to get it running on Ubuntu 20.10 again (or whether this is a bug).

Thanks!
Daniel

**Comment by chirlu** [comment]
Did you try clearing `~/.eclipse`? Do you have Java ≥11?

**Comment by marius** [comment]
I moved my workspace to workspace.old and then it worked. I quit PP, moved the workspace back and it still worked.
https://help.portfolio-performance.info/installation/#workspace-verzeichnis

**Comment by danielkr123** [comment]
@chirlu: Thank you! Deleting `~/.eclipse` solved the issue.
