### ISSUE TITLE
custom.css not found and strange styling

### ISSUE THREAD

**Issue by sebasbaumh** [buchen/portfolio#2306]
**Describe the bug**
The error shows up in the error log and the UI looks a bit strange.
I think this code [block](https://github.com/buchen/portfolio/blob/193ea7045d1bd82ba16437e14957a586d6b7ec98/name.abuchen.portfolio.bootstrap/src/name/abuchen/portfolio/bootstrap/LifeCycleManager.java#L73) is the cause. It immediately throws an IOException on `FileLocator.resolve`. 

**To Reproduce**
Just open Portfolio Performance 0.53.3.

**Expected behavior**
Nothing like that ;-)

**Screenshots**
![image](https://user-images.githubusercontent.com/670885/123596509-9104cb00-d7f2-11eb-9f28-343dcf73436f.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 0.53.3

Logfile:

    Mon Jun 28 09:21:07 CEST 2021
    C:\Users\sbaumhekel\AppData\Local\PortfolioPerformance\workspace\.metadata\.plugins\name.abuchen.portfolio.ui\custom.css (Das System kann den angegebenen Pfad nicht finden)
    java.io.FileNotFoundException: C:\Users\sbaumhekel\AppData\Local\PortfolioPerformance\workspace\.metadata\.plugins\name.abuchen.portfolio.ui\custom.css (Das System kann den angegebenen Pfad nicht finden)
    	at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
    	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
    	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:112)
    	at java.base/sun.net.www.protocol.file.FileURLConnection.connect(FileURLConnection.java:86)
    	at java.base/sun.net.www.protocol.file.FileURLConnection.getInputStream(FileURLConnection.java:184)
    	at java.base/java.net.URL.openStream(URL.java:1140)
    	at org.eclipse.e4.ui.css.core.impl.engine.AbstractCSSEngine.parseStyleSheet(AbstractCSSEngine.java:224)
    	at org.eclipse.e4.ui.css.swt.internal.theme.ThemeEngine.setTheme(ThemeEngine.java:473)
    	at org.eclipse.e4.ui.css.swt.internal.theme.ThemeEngine.setTheme(ThemeEngine.java:434)
    	at org.eclipse.e4.ui.css.swt.internal.theme.ThemeEngine.setTheme(ThemeEngine.java:426)
    	at org.eclipse.e4.ui.css.swt.internal.theme.ThemeEngine.restore(ThemeEngine.java:622)
    	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.setCSSTheme(PartRenderingEngine.java:1419)
    	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.initializeStyling(PartRenderingEngine.java:1326)
    	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1050)
    	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
    	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
    	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
    	at org.eclipse.e4.ui.internal.workbench.swt.E4Application.start(E4Application.java:166)
    	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
    	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
    	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
    	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
    	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
    	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
    	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
    	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
    	at org.eclipse.equinox.launcher.Main.run(Main.java:1461)

**Comment by zr40** [comment]
Creating the directory `.../workspace/.metadata/.plugins/name.abuchen.portfolio.ui` solved the problem for me.

**Comment by bllngr** [comment]
I can confirm the behaviour (and the @zr40's workaround) with the dark mode on Linux, where it's noticeable noticable.

![Screenshot_20210629_174720](https://user-images.githubusercontent.com/303458/123829580-e03a2100-d902-11eb-9c9e-e497ac81949c.png)

**Comment by buchen** [comment]
> the UI looks a bit strange.

That happens for me right after dynamically changing the theme.
But for me, it does not persist if I reopen the view or if I start right away in the correct theme.
@sebasbaumh - can you confirm this behavior, or does the strange rendering remain?

**Comment by sebasbaumh** [comment]
Yes, if I remember correctly I tried to even clear the metadata of SWT (`C:\Users\%USERNAME%\AppData\Local\PortfolioPerformance\workspace`).

**Comment by bllngr** [comment]
0.54.0 again doesn't look very dark on Windows with dark mode enabled:

![image](https://user-images.githubusercontent.com/303458/126123969-5caae570-c608-4037-88ec-bce802902889.png)

It worked before (0.52.x I think). Manually creating the directory `%localappdata%\PortfolioPerformance\workspace\.metadata\.plugins\name.abuchen.portfolio.ui` helped, and PP created `default.css` there on the next start.

**Comment by sebasbaumh** [comment]
Yes, I can confirm with 0.54.0 the bug with the missing folder for `custom.css` is still there.
It can be solved by manually creating it, but it would be better if Portfolio Performance could do that on startup.
I use only the light mode and the other errors in the UI I saw before 0.54.0 have not shown up on the new version.
