### ISSUE TITLE
Searching instrument doesn't work

### ISSUE THREAD

**Issue by AndrejGajdos** [buchen/portfolio#2346]
**Describe the bug**

I followed [this](https://indexfundinvestor.eu/2019/06/27/how-to-track-your-investments-with-portfolio-performance/) tutorial, but I have an issue with finding IWDA instrument. If I type in search instrument 'IWDA', it doesn't find instrument as [here](https://indexfundinvestor.eu/wp-content/uploads/2019/06/add_instrument.png).

**To Reproduce**
1. Go to Securities
2. Click on New Instrument
3. Type 'IWDA'
4. See error in screenshot

**Expected behavior**

**Screenshots**

<img width="1068" alt="Screenshot 2021-07-22 at 10 04 12" src="https://user-images.githubusercontent.com/1593758/126609333-1759c12e-538f-428e-9022-3bd7d65457a4.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - Version 0.54.0

**Comment by ganeshjp** [comment]
Same issue with 0.54.0 on Windows 10

**Comment by throwaway876** [comment]
Can also confirm with 0.54.0 flatpak on Linux. Error clip below.

```
https://s.yimg.com/aq/autoc?query=vtsax&region=DE&lang=de-DE&callback=YAHOO.util.ScriptNodeDataSource.callbacks --> 404

name.abuchen.portfolio.util.WebAccess$WebAccessException: https://s.yimg.com/aq/autoc?query=vtsax&region=DE&lang=de-DE&callback=YAHOO.util.ScriptNodeDataSource.callbacks --> 404
	at name.abuchen.portfolio.util.WebAccess.executeWith(WebAccess.java:205)
	at name.abuchen.portfolio.util.WebAccess.get(WebAccess.java:173)
	at name.abuchen.portfolio.online.impl.YahooSymbolSearch.search(YahooSymbolSearch.java:105)
	at name.abuchen.portfolio.online.impl.YahooSearchProvider.addSymbolSearchResults(YahooSearchProvider.java:58)
	at name.abuchen.portfolio.online.impl.YahooSearchProvider.search(YahooSearchProvider.java:35)
	at name.abuchen.portfolio.ui.wizards.security.SearchSecurityWizardPage.lambda$3(SearchSecurityWizardPage.java:157)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)


```
