### ISSUE TITLE
v0.55.0 Could not initialize class com.thoughtworks.xstream.converters.collections.TreeMapConverter

### ISSUE THREAD

**Issue by tfeldmann** [buchen/portfolio#2440]
**Describe the bug**
Portfolio performance can be started, but the portfolio xml file does not load anymore

**To Reproduce**
1. Open PP
2. Load a portfolio file

**Desktop (please complete the following information):**
 - OS: macOS 10.14.6
 - Version 0.55.0

Running the executable in terminal produces the following output:

```
/Applications/PortfolioPerformance.app/Contents/MacOS/PortfolioPerformance                                 ~ 127 ↵
OpenJDK 64-Bit Server VM warning: Ignoring option --illegal-access=permit; support was removed in 17.0
WARNING: Using incubator modules: jdk.incubator.vector, jdk.incubator.foreign
Exception in thread "Thread-4" java.lang.NoClassDefFoundError: Could not initialize class com.thoughtworks.xstream.converters.collections.TreeMapConverter
	at com.thoughtworks.xstream.XStream.setupConverters(XStream.java:820)
	at com.thoughtworks.xstream.XStream.<init>(XStream.java:574)
	at com.thoughtworks.xstream.XStream.<init>(XStream.java:496)
	at com.thoughtworks.xstream.XStream.<init>(XStream.java:465)
	at com.thoughtworks.xstream.XStream.<init>(XStream.java:411)
	at com.thoughtworks.xstream.XStream.<init>(XStream.java:350)
	at name.abuchen.portfolio.model.ClientFactory.xstream(ClientFactory.java:1178)
	at name.abuchen.portfolio.model.ClientFactory.access$0(ClientFactory.java:1174)
	at name.abuchen.portfolio.model.ClientFactory$XmlSerialization.load(ClientFactory.java:104)
	at name.abuchen.portfolio.model.ClientFactory$PlainWriter.load(ClientFactory.java:142)
	at name.abuchen.portfolio.model.ClientFactory.load(ClientFactory.java:415)
	at name.abuchen.portfolio.ui.editor.LoadClientThread.run(LoadClientThread.java:34)
^C%
```

**Comment by chirlu** [comment]
Possibly an update problem. You could try reinstalling PP.

**Comment by tfeldmann** [comment]
Thanks, reinstallation worked.
