### ISSUE TITLE
PP is incompatible with Java 17

### ISSUE THREAD

**Issue by pascalhein** [buchen/portfolio#2453]
**Describe the bug**
Java 17 is now [available and the current LTS release](https://openjdk.java.net/projects/jdk/17/). It now [enforces strong encapsulation](https://openjdk.java.net/jeps/403).

This behaviour was already the default in JDK 16, but overridden by PP using the flag `--illegal-access=permit` in PortfolioPerformance.ini. This flag has now been removed.

PP can therefore no longer load or save portfolio XMLs and reports with the following message:
```
OpenJDK 64-Bit Server VM warning: Ignoring option --illegal-access=permit; support was removed in 17.0
WARNING: Using incubator modules: jdk.incubator.vector, jdk.incubator.foreign
Exception in thread "Thread-4" java.lang.NoClassDefFoundError: Could not initialize class com.thoughtworks.xstream.converters.collections.TreeMapConverter
	at com.thoughtworks.xstream.XStream.setupConverters(XStream.java:820)
	at com.thoughtworks.xstream.XStream.<init>(XStream.java:574)
	at com.thoughtworks.xstream.XStream.<init>(XStream.java:496)
	at com.thoughtworks.xstream.XStream.<init>(XStream.java:465)
	at com.thoughtworks.xstream.XStream.<init>(XStream.java:411)
	at com.thoughtworks.xstream.XStream.<init>(XStream.java:350)
	at name.abuchen.portfolio.model.ClientFactory.xstream(ClientFactory.java:1178)
	at name.abuchen.portfolio.model.ClientFactory.access$0(ClientFactory.java:1174)
	at name.abuchen.portfolio.model.ClientFactory$XmlSerialization.load(ClientFactory.java:104)
	at name.abuchen.portfolio.model.ClientFactory$PlainWriter.load(ClientFactory.java:142)
	at name.abuchen.portfolio.model.ClientFactory.load(ClientFactory.java:415)
	at name.abuchen.portfolio.ui.editor.LoadClientThread.run(LoadClientThread.java:34)
```

(Note that the same stacktrace was observed in #2440; for some reason a new installation fixed the problem there. However, having a Java 17 installed as the system default, I can reliably reproduce the above error even after a clean reinstallation.)

PP should update and/or avoid dependencies that access internals of other modules (which has been deprecated since Java 9), to maintain compatibility with modern Java releases.

**To Reproduce**
1. Have the system's default Java be version 17 (if necessary, install via APT and `sudo update-alternatives --set java /usr/lib/jvm/java-17-openjdk-amd64/bin/java`)
3. Run PortfolioPerformance
4. Try to open a portfolio XML file.
 
Alternatively, try creating a new portfolio file (this works) and save it (this doesn't).

Now, set system Java to another version (`sudo update-alternatives --set java /usr/lib/jvm/java-11-openjdk-amd64/bin/java`) and try again - PP works as expected.

**Expected behavior**
PP loads and saves portfolios from/to XML files.

**Screenshots:**

Loading a file:

![image](https://user-images.githubusercontent.com/5236894/136075199-066d0ea9-e290-40c9-8253-48af7764dc0d.png)

The UI (e.g., menu bar) remains responsive, but loading does not continue.

Saving a file:

![image](https://user-images.githubusercontent.com/5236894/136076053-d43d28c1-83b7-457e-9d1a-67c945c4e2f1.png)

The save file is created but remains empty.

**Desktop:**
 - OS: Linux x86_64 (Xubuntu 21.04 hirsute)
 - Version: 0.55.0
 - Java: 17+35-Ubuntu-121.04 installed via APT (openjdk-17-jre:amd64, version 17+35-1~21.04)

**Comment by chirlu** [comment]
https://forum.portfolio-performance.info/t/could-not-initialize-class-com-thoughtworks-xstream-converters-collections-treemapconverter-beim-offnen/18067

**Comment by rondadon** [comment]
I can confirm this.
Setting jdk11-openjdk as default on Archlinux with `archlinux-java set java-11-openjdk` resolved the issue.

Thank you for providing a solution/workaround! :)

**Comment by mgeha** [comment]
Seems like gentoo now comes with openjdk-17 per default. You can install v11 in parallel and then switch the version to 11 for your user only:

`$ eselect java-vm set user openjdk-bin-11`
