### ISSUE TITLE
Cant open portfolio with 0.55.0

### ISSUE THREAD

**Issue by hkujath** [buchen/portfolio#2454]
**Describe the bug**
I cant open a portfolio. It works when a new portfolio is created. But me current one cant be loaded / opened.

**To Reproduce**
Start the version 0.55.0
Open a portfolio

**Expected behavior**

**Screenshots**
Content from the log file.

SESSION 2021-10-07 20:59:48.467 -----------------------------------------------
eclipse.buildId=unknown
java.version=17
java.vendor=Private Build
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=de_DE
Command-line arguments:  -os linux -ws gtk -arch x86_64

!ENTRY org.eclipse.core.jobs 4 2 2021-10-07 20:59:50.169
!MESSAGE Während "Wechselkurse von Europäische Zentralbank aktualisieren" ist ein interner Fehler aufgetreten.
!STACK 0
java.lang.ExceptionInInitializerError
	at com.thoughtworks.xstream.XStream.setupConverters(XStream.java:820)
	at com.thoughtworks.xstream.XStream.<init>(XStream.java:574)
	at com.thoughtworks.xstream.XStream.<init>(XStream.java:496)
	at com.thoughtworks.xstream.XStream.<init>(XStream.java:465)
	at com.thoughtworks.xstream.XStream.<init>(XStream.java:411)
	at com.thoughtworks.xstream.XStream.<init>(XStream.java:350)
	at name.abuchen.portfolio.money.impl.ECBExchangeRateProvider.xstream(ECBExchangeRateProvider.java:216)
	at name.abuchen.portfolio.money.impl.ECBExchangeRateProvider.load(ECBExchangeRateProvider.java:75)
	at name.abuchen.portfolio.ui.addons.StartupAddon$UpdateExchangeRatesJob.loadFromFile(StartupAddon.java:80)
	at name.abuchen.portfolio.ui.addons.StartupAddon$UpdateExchangeRatesJob.run(StartupAddon.java:65)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make field private final java.util.Comparator java.util.TreeMap.comparator accessible: module java.base does not "opens java.util" to unnamed module @1a63bf02
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:178)
	at java.base/java.lang.reflect.Field.setAccessible(Field.java:172)
	at com.thoughtworks.xstream.core.util.Fields.locate(Fields.java:39)
	at com.thoughtworks.xstream.converters.collections.TreeMapConverter.<clinit>(TreeMapConverter.java:50)
	... 11 more

**Desktop (please complete the following information):**
 - OS: [e.g. Windows - OS: [e.g. Windows, Linux, macOS]
Ubuntu 20.04.3 LTS

**Comment by hkujath** [comment]
Closed because of duplicate. Thx
