### ISSUE TITLE
Automatische Aktualisierung scheitert bei Installation

### ISSUE THREAD

**Issue by anroth** [buchen/portfolio#259]
Die automatische Aktualisierung scheitert bei der Installation. Ich nutze PortfolioPerformance seit ca. 4 Versionen und musste bisher jedes Mal die Dateien manuell herunterladen, entzippen und die alten Dateien durch die Neuen ersetzen.
Ich nutze Windows 7 und habe die Dateien auf Laufwerk D in einem Unterverzeichnis entpackt.

**Comment by buchen** [comment]
Könntest Du mir das Log in ```workspace/.metadata/.log``` zu kommen lassen? Und gibt es eine Log Datei im ```configuration``` Verzeichnis?

**Comment by anroth** [comment]
Klar, wie kann ich dir die Datei schicken?
Ich habe in den Dateien der Vorgängerversion nachgesehen und es gibt keine Log-Datei im configuration Verzeichnis.

**Comment by buchen** [comment]
Schick sie mir an *andreas dot buchen at gmail dot com*.

**Comment by buchen** [comment]
"interessante" Log Einträge:

```
!ENTRY org.eclipse.e4.ui.workbench 4 0 2015-03-08 17:24:46.335
!MESSAGE Internal Error
!STACK 0
org.eclipse.e4.core.di.InjectionException: java.util.ConcurrentModificationException
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:62)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:247)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:229)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:132)
	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:149)
	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:499)
	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:508)
	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:210)
	at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.executeItem(HandledContributionItem.java:825)
	at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.handleWidgetSelection(HandledContributionItem.java:701)
	at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.access$6(HandledContributionItem.java:685)
	at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem$4.handleEvent(HandledContributionItem.java:613)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4353)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1061)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4172)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3761)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$9.run(PartRenderingEngine.java:1151)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1032)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:148)
	at org.eclipse.e4.ui.internal.workbench.swt.E4Application.start(E4Application.java:164)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:648)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:603)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1465)
Caused by: java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(Unknown Source)
	at java.util.ArrayList$Itr.next(Unknown Source)
	at com.thoughtworks.xstream.converters.collections.CollectionConverter.marshal(CollectionConverter.java:73)
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller.convert(AbstractReferenceMarshaller.java:69)
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:58)
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller$1.convertAnother(AbstractReferenceMarshaller.java:84)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.marshallField(AbstractReflectionConverter.java:250)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter$2.writeField(AbstractReflectionConverter.java:226)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter$2.<init>(AbstractReflectionConverter.java:189)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.doMarshal(AbstractReflectionConverter.java:135)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.marshal(AbstractReflectionConverter.java:83)
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller.convert(AbstractReferenceMarshaller.java:69)
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:58)
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:43)
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller$1.convertAnother(AbstractReferenceMarshaller.java:88)
	at com.thoughtworks.xstream.converters.collections.AbstractCollectionConverter.writeItem(AbstractCollectionConverter.java:64)
	at com.thoughtworks.xstream.converters.collections.CollectionConverter.marshal(CollectionConverter.java:74)
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller.convert(AbstractReferenceMarshaller.java:69)
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:58)
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller$1.convertAnother(AbstractReferenceMarshaller.java:84)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.marshallField(AbstractReflectionConverter.java:250)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter$2.writeField(AbstractReflectionConverter.java:226)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter$2.<init>(AbstractReflectionConverter.java:189)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.doMarshal(AbstractReflectionConverter.java:135)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.marshal(AbstractReflectionConverter.java:83)
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller.convert(AbstractReferenceMarshaller.java:69)
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:58)
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:43)
	at com.thoughtworks.xstream.core.TreeMarshaller.start(TreeMarshaller.java:82)
	at com.thoughtworks.xstream.core.AbstractTreeMarshallingStrategy.marshal(AbstractTreeMarshallingStrategy.java:37)
	at com.thoughtworks.xstream.XStream.marshal(XStream.java:1022)
	at com.thoughtworks.xstream.XStream.marshal(XStream.java:1011)
	at com.thoughtworks.xstream.XStream.toXML(XStream.java:984)
	at name.abuchen.portfolio.model.ClientFactory$XmlSerialization.save(ClientFactory.java:83)
	at name.abuchen.portfolio.model.ClientFactory$Decryptor.save(ClientFactory.java:256)
	at name.abuchen.portfolio.model.ClientFactory.save(ClientFactory.java:354)
	at name.abuchen.portfolio.ui.PortfolioPart.save(PortfolioPart.java:318)
	at name.abuchen.portfolio.ui.handlers.SaveFileHandler.execute(SaveFileHandler.java:36)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:55)
	... 33 more
```


```
!ENTRY org.eclipse.equinox.p2.repository 2 0 2015-03-09 21:05:04.089
!MESSAGE Server returned lastModified <= 0 for http://updates.abuchen.name/portfolio/content.jar

!ENTRY org.eclipse.equinox.p2.repository 2 0 2015-03-09 21:05:05.166
!MESSAGE Server returned lastModified <= 0 for http://updates.abuchen.name/portfolio/artifacts.jar

!ENTRY org.eclipse.equinox.p2.touchpoint.natives 4 0 2015-03-09 21:05:26.382
!MESSAGE Manual restore of backup needed for: C:\Users\Markus\AppData\Local\Temp\DefaultProfile_2980048c14c0_c0a80505d403\D\Private Dokumente\Finanzen\Depottool\PortfolioPerformance.exe

!ENTRY org.eclipse.equinox.p2.touchpoint.natives 4 0 2015-03-09 21:05:26.383
!MESSAGE 0 von 1 Objekten wiederhergestellt.

!ENTRY org.eclipse.equinox.p2.engine 4 4 2015-03-09 21:05:26.384
!MESSAGE An error occurred while committing the engine session for profile: DefaultProfile.
!SUBENTRY 1 org.eclipse.equinox.p2.touchpoint.natives 4 0 2015-03-09 21:05:26.384
!MESSAGE Restore of backup failed - see log for details. Backup directory name: DefaultProfile_2980048c14c0_c0a80505d403.
!STACK 0
java.io.IOException: Errors while restoring - see earlier logged errors
	at org.eclipse.equinox.internal.p2.touchpoint.natives.BackupStore.close(BackupStore.java:526)
	at org.eclipse.equinox.internal.p2.touchpoint.natives.BackupStore.restore(BackupStore.java:489)
	at org.eclipse.equinox.internal.p2.touchpoint.natives.LazyBackupStore.restore(LazyBackupStore.java:53)
	at org.eclipse.equinox.internal.p2.touchpoint.natives.NativeTouchpoint.rollback(NativeTouchpoint.java:108)
	at org.eclipse.equinox.internal.p2.engine.EngineSession.rollback(EngineSession.java:196)
	at org.eclipse.equinox.internal.p2.engine.Engine.perform(Engine.java:84)
	at org.eclipse.equinox.internal.p2.engine.Engine.perform(Engine.java:44)
	at org.eclipse.equinox.p2.operations.ProvisioningSession.performProvisioningPlan(ProvisioningSession.java:174)
	at org.eclipse.equinox.p2.operations.ProfileModificationJob.runModal(ProfileModificationJob.java:79)
	at name.abuchen.portfolio.ui.update.UpdateHelper.runUpdateOperation(UpdateHelper.java:266)
	at name.abuchen.portfolio.ui.update.UpdateHelper.runUpdate(UpdateHelper.java:151)
	at name.abuchen.portfolio.ui.handlers.UpdateHandler$1.run(UpdateHandler.java:39)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
```

**Comment by buchen** [comment]
***
Similar report - allerdings ohne Antwort
https://www.eclipse.org/forums/index.php/t/881863/

Probleme mit der Installation auf D:
https://issues.jboss.org/browse/JBDS-3362
https://issues.jboss.org/browse/JBDS-3295

> If you use Windows, install JBDS or Eclipse on your C drive ONLY.

Angeblich mit Luna SR2 gefixt:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=441098#c6
***

@anroth Einige Meldungen deuten darauf hin, dass unter Windows eine Installation auf ein anderes Verzeichnis als C: ein Problem ist. Bei Dir ist das ja auf D: installiert. Kann das sein, dass Du das Programm "umgezogen" hast und es seit dem nicht mehr geht?

Wie auch immer, dieses Problem sollte in Luna SR2 gefixt sein. Mit dem letzten Update habe ich mein Programm auf diese Version der Bibliothek aktualisiert. Es könnte beim nächsten Update also vielleicht wieder klappen.

Alternative könntest Du vielleicht ausprobieren, ob eine Installation auf C: funktioniert. Hier gibt es https://github.com/buchen/portfolio/releases auch eine ältere Version zum Download. Dann kannst Du den Ugrade testen.

**Comment by buchen** [comment]
@anroth Korrektur: das **nächste** Update wird erst auf Luna SR2 aktualisieren. Also wird erst das übernächste Update wieder funktionieren (unter der Annahme das ist das Problem hier).

**Comment by anroth** [comment]
Update hierzu:
Beim Update von 17.0 auf 17.1 war es so, dass erkannt wurde, dass ein Update zur Verfügung steht, leider aber das Update nach dem Neustart des Programms nicht durchgeführt war. Neuer Versionsstand: 17.0 und es wurde wieder angeboten das Update herunterzuladen und zu installieren.
Mal schauen, ob es dann auf Version 17.2 klappt.

Ich habe nochmal die Version 17.0 auf C:/ entpackt und dann dort den Ordner "portfolio" in "test" umbenannt. Das Update auf 17.1 hat funktioniert.
2. Versuch: Wieder auf c:/ entpackt eine Testdatei mit 2 Konten angelgt und diesmal auf d:/ verschoben. Siehe da: Das Update funktioniert nicht mehr.

3. Versuch: Ich dachte, dann entpacke ich es doch einfach gleich auf "d:/...". Das Update funktioniert nicht.

Ergo: Wie du schon geschrieben hast wird es dann wohl mit Luna SR2 klappen. Wenn es soweit ist werde ich hier wieder schreiben.
