### ISSUE TITLE
Datei ist nicht mehr zu öffnen: xml kann nicht geparst werden: no converter available

### ISSUE THREAD

**Issue by mor3dr3ad** [buchen/portfolio#2592]
Hallo,

erstmal danke für das tolle Programm. Ich bin grundsätzlich sehr zufrieden, nur leider kann ich meine lange mühevoll erarbeitete Datei nicht mehr öffnen. Auch das backup zeigt die gleichen Fehler. 

Das Öffnen der Datei scheitert mit der Fehlermeldung "XML kann nicht geparst werden: no converter available". 

Hier das volle Fehlerprotokoll des Öffnungsversuchs: 

    !ENTRY name.abuchen.portfolio.ui 4 0 2021-12-21 21:41:26.611
    !MESSAGE XML kann nicht geparst werden: No converter available
    ---- Debugging information ---- 
    message             : No converter available
    type                : java.util.Arrays$ArrayList
    converter           : com.thoughtworks.xstream.converters.reflection.ReflectionConverter
    message[1]          : Unable to make field protected transient int java.util.AbstractList.modCount accessible: module java.base does 
    not "opens java.util" to unnamed module @53306d13
    class               : name.abuchen.portfolio.model.Taxonomy
    required-type       : name.abuchen.portfolio.model.Taxonomy
    converter-type      : com.thoughtworks.xstream.converters.reflection.ReflectionConverter
    path                : /client/taxonomies/taxonomy/dimensions
    line number         : 135876
    class[1]            : java.util.ArrayList
    required-type[1]    : java.util.ArrayList
    converter-type[1]   : com.thoughtworks.xstream.converters.collections.CollectionConverter
    class[2]            : name.abuchen.portfolio.model.Client
    required-type[2]    : name.abuchen.portfolio.model.Client
    version             : not available
    -------------------------------
    !STACK 0
    java.io.IOException: XML kann nicht geparst werden: No converter available
    ---- Debugging information ----
    message             : No converter available
    type                : java.util.Arrays$ArrayList
    converter           : com.thoughtworks.xstream.converters.reflection.ReflectionConverter
    message[1]          : Unable to make field protected transient int java.util.AbstractList.modCount accessible: module java.base does         not "opens java.util" to unnamed module @53306d13
    class               : name.abuchen.portfolio.model.Taxonomy
    required-type       : name.abuchen.portfolio.model.Taxonomy
    converter-type      : com.thoughtworks.xstream.converters.reflection.ReflectionConverter
    path                : /client/taxonomies/taxonomy/dimensions
    line number         : 135876
    class[1]            : java.util.ArrayList
    required-type[1]    : java.util.ArrayList
    converter-type[1]   : com.thoughtworks.xstream.converters.collections.CollectionConverter    
    class[2]            : name.abuchen.portfolio.model.Client
    required-type[2]    : name.abuchen.portfolio.model.Client
    version             : not available
    -------------------------------
	at name.abuchen.portfolio.model.ClientFactory$XmlSerialization.load(ClientFactory.java:125)
	at name.abuchen.portfolio.model.ClientFactory$PlainWriter.load(ClientFactory.java:151)
	at name.abuchen.portfolio.model.ClientFactory.load(ClientFactory.java:528)
	at name.abuchen.portfolio.ui.editor.LoadClientThread.run(LoadClientThread.java:34)
    Caused by: com.thoughtworks.xstream.converters.ConversionException: No converter available
    ---- Debugging information ----
    message             : No converter available
    type                : java.util.Arrays$ArrayList
    converter           : com.thoughtworks.xstream.converters.reflection.ReflectionConverter
    message[1]          : Unable to make field protected transient int java.util.AbstractList.modCount accessible: module java.base does     not "opens java.util" to unnamed module @53306d13
    class               : name.abuchen.portfolio.model.Taxonomy
    required-type       : name.abuchen.portfolio.model.Taxonomy
    converter-type      : com.thoughtworks.xstream.converters.reflection.ReflectionConverter
    path                : /client/taxonomies/taxonomy/dimensions
    line number         : 135876
    class[1]            : java.util.ArrayList
    required-type[1]    : java.util.ArrayList
    converter-type[1]   : com.thoughtworks.xstream.converters.collections.CollectionConverter
    class[2]            : name.abuchen.portfolio.model.Client
    required-type[2]    : name.abuchen.portfolio.model.Client
    version             : not available
    -------------------------------
    	at com.thoughtworks.xstream.core.DefaultConverterLookup.lookupConverterForType(DefaultConverterLookup.java:88)
	at com.thoughtworks.xstream.XStream$1.lookupConverterForType(XStream.java:472)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:56)
	at     com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshallField(AbstractReflectionConverter.java:499)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.doUnmarshal(AbstractReflectionConverter.java:425)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshal(AbstractReflectionConverter.java:277)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)
	at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:72)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:50)
	at com.thoughtworks.xstream.converters.collections.AbstractCollectionConverter.readBareItem(AbstractCollectionConverter.java:132)
	at com.thoughtworks.xstream.converters.collections.AbstractCollectionConverter.readItem(AbstractCollectionConverter.java:117)
	at com.thoughtworks.xstream.converters.collections.CollectionConverter.addCurrentElementToCollection(CollectionConverter.java:98)
	at com.thoughtworks.xstream.converters.collections.CollectionConverter.populateCollection(CollectionConverter.java:91)
	at com.thoughtworks.xstream.converters.collections.CollectionConverter.populateCollection(CollectionConverter.java:85)
	at com.thoughtworks.xstream.converters.collections.CollectionConverter.unmarshal(CollectionConverter.java:80)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)
	at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:72)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshallField(AbstractReflectionConverter.java:499)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.doUnmarshal(AbstractReflectionConverter.java:425)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshal(AbstractReflectionConverter.java:277)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)
	at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:72)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:50)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.start(TreeUnmarshaller.java:134)
	at com.thoughtworks.xstream.core.AbstractTreeMarshallingStrategy.unmarshal(AbstractTreeMarshallingStrategy.java:32)
	at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:1391)
	at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:1376)
	at com.thoughtworks.xstream.XStream.fromXML(XStream.java:1261)
	at name.abuchen.portfolio.model.ClientFactory$XmlSerialization.load(ClientFactory.java:113)
	... 3 more

Wenn ich eine neue Datei erstelle und ohne Veränderung speichere, dann lässt sich diese auch wieder öffnen. Allerdings kann ich in einer neuen Datei kein neues Wertpapier hinzufügen. Folgende Fehlermeldung wird hierbei ausgespuckt:

    java.lang.reflect.InaccessibleObjectException: Unable to make field private final int java.time.LocalDate.year accessible: module 
    java.base does not "opens java.time" to unnamed module @41bd6a0f

Hier scheint eine ganze Reihe an Fehlermeldungen zu bestehen - erste Vermutung ist, dass es ein Problem mit Java Versionen ist. 

Versionen: 

Version: 0.56.2 (Dez. 2021)
Platform: linux, x86_64
Java: 17.0.1+12, Oracle Corporation

Hat jemand schon mal das gleiche Problem gehabt? Gibt es Lösungsansätze? 

Danke schonmal

**Comment by OnkelDok** [comment]
Das dürfte an der verwendeten Java-Version liegen.
* https://forum.portfolio-performance.info/t/java-error-unable-to-make-field-private/18935
* https://forum.portfolio-performance.info/t/could-not-initialize-class-com-thoughtworks-xstream-converters-collections-treemapconverter-beim-offnen/18067
* #2453
* #2454

Versuch mal Version 11 zu nutzen.

**Comment by mor3dr3ad** [comment]
Jupp, das war es - danke. topic closed
