### ISSUE TITLE
NPE when assigning a security with amount 0 to asset class

### ISSUE THREAD

**Issue by yetipenguin** [buchen/portfolio#2594]
**Describe the bug**
An error message is show: "An error occurred. For details have a look in the error protocol java.lang.NullPointerException"
The stacktrace can only be seen on stderr if you start PortfolioPerformance from the console.

```
Exception occurred
java.lang.NullPointerException
        at name.abuchen.portfolio.ui.views.taxonomy.ReBalancingViewer$9.getText(ReBalancingViewer.java:348)
        at org.eclipse.jface.viewers.ColumnLabelProvider.update(ColumnLabelProvider.java:40)
        at org.eclipse.jface.viewers.ViewerColumn.refresh(ViewerColumn.java:144)
        at org.eclipse.jface.viewers.AbstractTreeViewer.doUpdateItem(AbstractTreeViewer.java:957)
        at org.eclipse.jface.viewers.AbstractTreeViewer$UpdateItemSafeRunnable.run(AbstractTreeViewer.java:126)
        at org.eclipse.jface.util.SafeRunnable$1.run(SafeRunnable.java:129)
        at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:174)
        at org.eclipse.jface.viewers.AbstractTreeViewer.doUpdateItem(AbstractTreeViewer.java:1035)
        at org.eclipse.jface.viewers.StructuredViewer$UpdateItemSafeRunnable.run(StructuredViewer.java:427)
        at org.eclipse.jface.util.SafeRunnable$1.run(SafeRunnable.java:129)
        at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:174)
        at org.eclipse.jface.viewers.StructuredViewer.updateItem(StructuredViewer.java:2109)
        at org.eclipse.jface.viewers.AbstractTreeViewer.createTreeItem(AbstractTreeViewer.java:851)
        at org.eclipse.jface.viewers.AbstractTreeViewer.createChildren(AbstractTreeViewer.java:829)
        at org.eclipse.jface.viewers.TreeViewer.createChildren(TreeViewer.java:604)
        at org.eclipse.jface.viewers.AbstractTreeViewer.createChildren(AbstractTreeViewer.java:777)
        at org.eclipse.jface.viewers.AbstractTreeViewer.setExpandedState(AbstractTreeViewer.java:2524)
        at name.abuchen.portfolio.ui.views.taxonomy.AbstractNodeTreeViewer$11.run(AbstractNodeTreeViewer.java:883)
        at org.eclipse.jface.action.Action.runWithEvent(Action.java:474)
        at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:580)
        at org.eclipse.jface.action.ActionContributionItem.lambda$4(ActionContributionItem.java:414)
        at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
        at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5884)
        at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1522)
        at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:5126)
        at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4576)
        at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1150)
        at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
        at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1041)
        at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
        at org.eclipse.e4.ui.internal.workbench.swt.E4Application.start(E4Application.java:168)
        at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
        at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
        at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
        at org.eclipse.equinox.launcher.Main.main(Main.java:1440)
```

**To Reproduce**
Steps to reproduce the behavior (with kommer.xml):
1. Go to 'All Securites', add (for example) "LU0603933895" (C003) as a new instrument and save kommer.xml to disk.
2. Do not buy/add any amount of the security.
3. Go to 'Asset Classes"
4. Select 'Asset Classes" --> 'Equity"
5. Right click on 'Equity' and select 'Assign'

Be aware, that the error is not always reproducible!

**Expected behavior**
The instrument gets assigned to "Equity" and no error message is shown.

**Observed behavior**
The error message is shown and the instrument is assigned to "Equity"-

**Desktop (please complete the following information):**
 - OS: linux, x86_64
 - Version 0.56.2 (Dez. 2021)

**Comment by tquellenberg** [comment]
My guess: when assigning a security to an asset class, the rebalancing view is redrawn after the security is added to the mode but before the recalculation of the model is done.
An easy solution is to switch two lines in `name.abuchen.portfolio.ui.views.taxonomy.AbstractNodeTreeViewer.addAvailableAssignments(...).Action`
 and run `setExpandedState` after `onTaxnomyNodeEdited`.
