### ISSUE TITLE
Nach Neustart wird nicht gefragt ob die aktuell geöffnete Datei gespeichert werden soll

### ISSUE THREAD

**Issue by buchen** [buchen/portfolio#287]
> Eine kleine Bug-Meldung: Ich habe beobachtet, dass beim Neustart nach der Aktualisierung scheinbar nicht gefragt wird, ob man die aktuell geöffnete Datei speichern will, trotz Sternchen am Tab. Das kann ich natürlich jetzt schlecht reproduzieren, deshalb mit Fragezeichen.

**Comment by buchen** [comment]
```
Caused by: java.lang.NullPointerException
	at name.abuchen.portfolio.ui.addons.StartupAddon.registerCustomSaveHandler(StartupAddon.java:113)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:55)
```
