### ISSUE TITLE
Project file cannot be opened if path contains umlaut

### ISSUE THREAD

**Issue by dbankmann** [buchen/portfolio#3096]
**Describe the bug**
Opening a project file whose path contains an umlaut fails with
"File <filename> does not exist (anymore)".

**To Reproduce**
1. Create a folder containing an umlaut, e.g. `testÜ` and put some project file (or even any file) inside
2. Open that file in portfolio

**Stack trace**
```
!MESSAGE File /home/daniel/testÜ/pp.xml does not exist (anymore).
!STACK 0
java.io.FileNotFoundException: File /home/daniel/testÜ/pp.xml does not exist (anymore).
	at name.abuchen.portfolio.model.ClientFactory.load(ClientFactory.java:542)
	at name.abuchen.portfolio.ui.editor.LoadClientThread.run(LoadClientThread.java:34)
Caused by: java.io.FileNotFoundException: /home/daniel/projects/testÜ/pp.xml (No such file or directory)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
	at name.abuchen.portfolio.model.ClientFactory.load(ClientFactory.java:530)
```

**Expected behavior**
File should load.

**Additional Information**

I have not experienced this problem in the past, however I have similar problems recently with other java applications. Still, something has to be special about this particular setup, as a simple 
```java
import java.io.*;
class LoadWithUmlaut
{
    public static void main(String args[])
    {
	    File file = new File("/home/daniel/testÜ/pp.xml");
	    try{
		    FileInputStream input = new FileInputStream(file);
	    }
	    catch(Exception e) {
		    e.printStackTrace();
	    }
    }
}
```
will not throw.

**Desktop (please complete the following information):**
 - OS: archlinux
 - Version 0.60
 
``` 
java --version
openjdk 11.0.17 2022-10-18
OpenJDK Runtime Environment (build 11.0.17+1)
OpenJDK 64-Bit Server VM (build 11.0.17+1, mixed mode)
```

**Comment by dbankmann** [comment]
I was able to fix the issue. Was a problem with my local installation.
