### ISSUE TITLE
Dependencie issues

### ISSUE THREAD

**Issue by RomanLangrehr** [buchen/portfolio#3414]
I just freshly installed eclipse and followed all the steps described in CONTRIBUTING.md#development-setup (including everything optional except for the language package). Now I get the following errors:

```
Description	Resource	Path	Location	Type
Bundle 'jakarta.inject.jakarta.inject-api' cannot be resolved	MANIFEST.MF	/name.abuchen.portfolio.bootstrap/META-INF	line 7	Plug-in Problem
Feature org.eclipse.nebula.cwt.feature does not exist in the workspace or the current target platform	launches.lc	/portfolio-app/eclipse	line: 15 /portfolio-app/eclipse/launches.lc	LcDsl Problem
Feature org.eclipse.nebula.cwt.feature does not exist in the workspace or the current target platform	launches.lc	/portfolio-app/eclipse	line: 57 /portfolio-app/eclipse/launches.lc	LcDsl Problem
Feature org.eclipse.nebula.widgets.cdatetime.feature does not exist in the workspace or the current target platform	launches.lc	/portfolio-app/eclipse	line: 16 /portfolio-app/eclipse/launches.lc	LcDsl Problem
Feature org.eclipse.nebula.widgets.cdatetime.feature does not exist in the workspace or the current target platform	launches.lc	/portfolio-app/eclipse	line: 58 /portfolio-app/eclipse/launches.lc	LcDsl Problem
```

(and some more that are obviously directly consequences of the above).

When ignoring these issues, all the JUnit test work fine, but trying to start PP causes the following exception:
```
java.lang.RuntimeException: Es konnten keine Anwendungskennung gefunden werden.
	at org.eclipse.equinox.internal.app.EclipseAppContainer.startDefaultApp(EclipseAppContainer.java:246)
	at org.eclipse.equinox.internal.app.MainApplicationLauncher.run(MainApplicationLauncher.java:33)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1440)
```

(OS is Windows 10)

**Comment by RomanLangrehr** [comment]
Replacing `jakarta.inject.jakarta.inject-api` with `javax.inject` in `MANIFEST.MF` of the bootstrap project did the trick for me. I don’t know if this is a good official solution though.

**Comment by buchen** [comment]
Did you update the target platform? (Open target platform -> reload)

With the latest eclipse version, the bundle java.inject does not exist anymore.
Therefore this b4fb4de03b4f62b7a9a86e663c0e52a0e8c96605 actually changes the bundle requirement.

**Comment by RomanLangrehr** [comment]
Yes, I did. I use Eclipse version 2023-06 (4.28.0), which seems to be the latest eclipse version (at least for my plattform).

**Comment by buchen** [comment]
You also need to update the target platform manually (open the target file, refresh, click reload). That should resolve the error.

**Comment by Nirus2000** [comment]
Nope... it doesn't work

**Comment by buchen** [comment]
Very interesting. The target platform resolution on Windows results in a different set of bundles on macOS and Windows. SWT chart is still pulling in the "old" inject bundle
