### ISSUE TITLE
Dependency issue

### ISSUE THREAD

**Issue by henrydatei** [buchen/portfolio#3432]
**Describe the bug**
Similar to #3414 I followed the guide to setup Eclipse. When trying to start PP I get the following error:
```
!SESSION 2023-07-01 18:22:08.479 -----------------------------------------------
eclipse.buildId=unknown
java.version=17.0.7
java.vendor=Eclipse Adoptium
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=de_DE
Framework arguments:  -product name.abuchen.portfolio.bootstrap.product
Command-line arguments:  -product name.abuchen.portfolio.bootstrap.product -data /home/henry/eclipse-workspace/../runtime-PortfolioPerformance -dev file:/home/henry/eclipse-workspace/.metadata/.plugins/org.eclipse.pde.core/PortfolioPerformance/dev.properties -os linux -ws gtk -arch x86_64 -consoleLog

!ENTRY org.eclipse.equinox.app 0 0 2023-07-01 18:22:10.131
!MESSAGE Das Produkt name.abuchen.portfolio.bootstrap.product kann nicht gefunden werden.

!ENTRY name.abuchen.portfolio.bootstrap 2 0 2023-07-01 18:22:10.276
!MESSAGE Could not resolve module: name.abuchen.portfolio.bootstrap [19]
  Unresolved requirement: Require-Bundle: jakarta.inject.jakarta.inject-api


!ENTRY org.eclipse.osgi 4 0 2023-07-01 18:22:10.277
!MESSAGE Anwendungsfehler
!STACK 1
java.lang.RuntimeException: Es konnten keine Anwendungskennung gefunden werden.
	at org.eclipse.equinox.internal.app.EclipseAppContainer.startDefaultApp(EclipseAppContainer.java:246)
	at org.eclipse.equinox.internal.app.MainApplicationLauncher.run(MainApplicationLauncher.java:33)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1440)
Ein Fehler ist aufgetreten. Informationen hierzu enthält die Protokolldatei
/home/henry/eclipse-workspace/.metadata/.plugins/org.eclipse.pde.core/PortfolioPerformance/1688228528635.log.
```
As suggested in #3414 I refreshed and reloaded the target file but this doesn't help. I'm using Eclipse 4.28.0 (2023-06) and Ubuntu 22.04

**Comment by buchen** [comment]
Very interesting: target platform resolution on macOS results in a different set of bundles than on Windows. Should be fixed now
