### ISSUE TITLE
NPE @ Control.internal_new_GC

### ISSUE THREAD

**Issue by buchen** [buchen/portfolio#355]
```
Sat Oct 03 08:01:02 CEST 2015
Internal Error

java.lang.NullPointerException
	at org.eclipse.swt.widgets.Control.internal_new_GC(Control.java:2118)
	at org.eclipse.swt.graphics.GC.cocoa_new(GC.java:207)
	at org.eclipse.swt.widgets.Table.sendMeasureItem(Table.java:3130)
	at org.eclipse.swt.widgets.Table.cellSize(Table.java:235)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:5528)
	at org.eclipse.swt.internal.cocoa.OS.objc_msgSendSuper_stret(Native Method)
	at org.eclipse.swt.widgets.Widget.expansionFrameWithFrame_inView(Widget.java:798)
	at org.eclipse.swt.widgets.Table.expansionFrameWithFrame_inView(Table.java:1186)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:5907)
	at org.eclipse.swt.internal.cocoa.OS.objc_msgSend_bool(Native Method)
	at org.eclipse.swt.internal.cocoa.NSRunLoop.runMode(NSRunLoop.java:42)
	at org.eclipse.swt.widgets.Display.sleep(Display.java:4691)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$9$1.eventLoopIdle(PartRenderingEngine.java:1129)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$9.run(PartRenderingEngine.java:1155)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1032)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:148)
	at org.eclipse.e4.ui.internal.workbench.swt.E4Application.start(E4Application.java:164)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:648)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:603)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1465)
```

**Comment by buchen** [comment]
https://bugs.eclipse.org/bugs/show_bug.cgi?id=434393

**Comment by buchen** [comment]
Updated to 4.5.2 - den Code um Exceptions zu ignorieren belassen ich mal drin...
