### ISSUE TITLE
CSV-Import: java.lang.IndexOutOfBoundsException

### ISSUE THREAD

**Issue by bcutter** [buchen/portfolio#416]
Hi,

nachdem einige Test-Imports noch funktionierten, erhalte ich nun nur noch einen "java.lang.IndexOutOfBoundsException: Index: 0, Size: 0". Egal welches CSV; sogar bei einem welches sich vorher noch tadellos importieren ließ. Programm wurde mehrfach neugestartet, ohne Veränderung.

Hängt irgendwas von dem Java-Gedöns noch im RAM? System-Neustart noch nicht probiert; jedenfalls schonmal ein etwas unbefriedigender Start mit PP... :(

**Comment by bcutter** [comment]
Pff, jetzt läuft´s wieder... gab wohl irgend einen Timeout.

**Comment by bcutter** [comment]
...aaaaaaand it´s gone. Wieder gleicher Fehler. v0.21.4.

Das Programm macht einem den Start wirklich nicht leicht! Gewinne gerade meine Excel-Listen wieder lieb...

```
Sun Jan 31 17:13:49 CET 2016
Internal Error

org.eclipse.e4.core.di.InjectionException: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0

	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:68)

	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:252)

	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:234)

	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:132)

	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:152)

	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:493)

	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:486)

	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:210)

	at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.executeItem(HandledContributionItem.java:799)

	at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.handleWidgetSelection(HandledContributionItem.java:675)

	at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.access$7(HandledContributionItem.java:659)

	at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem$4.handleEvent(HandledContributionItem.java:592)

	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)

	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4362)

	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1113)

	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4180)

	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3769)

	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1127)

	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)

	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1018)

	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)

	at org.eclipse.e4.ui.internal.workbench.swt.E4Application.start(E4Application.java:159)

	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)

	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)

	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)

	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)

	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)

	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)

	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)

	at java.lang.reflect.Method.invoke(Unknown Source)

	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:669)

	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:608)

	at org.eclipse.equinox.launcher.Main.run(Main.java:1515)

Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0

	at java.util.ArrayList.rangeCheck(Unknown Source)

	at java.util.ArrayList.get(Unknown Source)

	at name.abuchen.portfolio.ui.wizards.datatransfer.SelectSecurityPage.createControl(SelectSecurityPage.java:49)

	at org.eclipse.jface.wizard.Wizard.createPageControls(Wizard.java:175)

	at org.eclipse.jface.wizard.WizardDialog.createPageControls(WizardDialog.java:705)

	at org.eclipse.jface.wizard.WizardDialog.createContents(WizardDialog.java:597)

	at org.eclipse.jface.window.Window.create(Window.java:430)

	at org.eclipse.jface.dialogs.Dialog.create(Dialog.java:1096)

	at org.eclipse.jface.window.Window.open(Window.java:792)

	at name.abuchen.portfolio.ui.handlers.ImportCSVHandler.execute(ImportCSVHandler.java:49)

	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)

	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)

	at java.lang.reflect.Method.invoke(Unknown Source)

	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:56)

	... 33 more

´´´

**Comment by buchen** [comment]
Danke @bcutter für den Bug Report.

Das Problem tritt auf wenn man keine aktiven Wertpapiere hat. Aktiv ist ein Wertpapier wenn das Häkchen bei "inaktiv" nicht gesetzt ist. Das ist natürlich blöd wenn man direkt mit dem CSV Import beginnen möchte...  und man noch gar keine Wertpapiere hat. Das werde ich beheben.

In Deinem Fall müsste es funktionieren ein Wertpapier manuell anzulegen.
