### ISSUE TITLE
Beim Klicken auf Wertpapiere

### ISSUE THREAD

**Issue by BoyPlunga** [buchen/portfolio#457]
Wed Mar 02 14:57:06 CET 2016
Internal Error

java.lang.UnsupportedOperationException: at least one data point must be provided

	at name.abuchen.portfolio.math.NPVFunction.<init>(NPVFunction.java:22)

	at name.abuchen.portfolio.math.IRR.calculate(IRR.java:12)

	at name.abuchen.portfolio.snapshot.security.IRRCalculation.getIRR(IRRCalculation.java:71)

	at name.abuchen.portfolio.snapshot.security.SecurityPerformanceRecord.calculateIRR(SecurityPerformanceRecord.java:312)

	at name.abuchen.portfolio.snapshot.security.SecurityPerformanceRecord.calculate(SecurityPerformanceRecord.java:293)

	at name.abuchen.portfolio.snapshot.security.SecurityPerformanceSnapshot.doCreateSnapshot(SecurityPerformanceSnapshot.java:76)

	at name.abuchen.portfolio.snapshot.security.SecurityPerformanceSnapshot.create(SecurityPerformanceSnapshot.java:33)

	at name.abuchen.portfolio.ui.views.SecuritiesPerformanceView.reportingPeriodUpdated(SecuritiesPerformanceView.java:878)

	at name.abuchen.portfolio.ui.views.SecuritiesPerformanceView.createTopTable(SecuritiesPerformanceView.java:276)

	at name.abuchen.portfolio.ui.views.AbstractListView.createBody(AbstractListView.java:20)

	at name.abuchen.portfolio.ui.AbstractFinanceView.createViewControl(AbstractFinanceView.java:108)

	at name.abuchen.portfolio.ui.PortfolioPart.activateView(PortfolioPart.java:471)

	at name.abuchen.portfolio.ui.ClientEditorSidebar$ActivateViewAction.run(ClientEditorSidebar.java:64)

	at name.abuchen.portfolio.ui.Sidebar.select(Sidebar.java:253)

	at name.abuchen.portfolio.ui.Sidebar$Item$2.mouseDown(Sidebar.java:438)

	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:192)

	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)

	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4362)

	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1113)

	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4180)

	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3769)

	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1127)

	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)

	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1018)

	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)

	at org.eclipse.e4.ui.internal.workbench.swt.E4Application.start(E4Application.java:159)

	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)

	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)

	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)

	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)

	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)

	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)

	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)

	at java.lang.reflect.Method.invoke(Unknown Source)

	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:669)

	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:608)

	at org.eclipse.equinox.launcher.Main.run(Main.java:1515)

**Comment by buchen** [comment]
Danke für die Testdatei.

Das Problem war ein Wertpapier, für das im Berichtszeitraum nur eine Steuerrückerstattung existierte. Damit konnte man keinen IZF berechnen. Stattdessen wird jetzt NaN (Not a Number) ausgegeben.
