### ISSUE TITLE
NullPointerException by Performance Zeitraum bis 32 Tage bzw 1 Monat

### ISSUE THREAD

**Issue by JosScha** [buchen/portfolio#458]
Hallo Andreas 
Unter Performance Diagramm bei Zeiträume 1 Monat oder bis zu 32 Tage tritt der unten angeführte NullPointer auf. Das Gruppierungsintervall (täglich|wöchentlich|..) ist dabei nicht relevant. Ich habe versucht das gleich beim beigefügten Kommer Depot nachzuvollziehen, das war aber nicht erfolgreich.
Ich habe beim Testen auch noch festgestellt, wenn so ein fraglicher Zeitraum gewählt ist und das Diagramm Menü verlassen wird, kommt man auch nicht mehr zurück. der Screen bleibt grau und der NullPointer scheint auf. 

Wed Mar 02 19:36:21 CET 2016
Internal Error

java.lang.NullPointerException

	at name.abuchen.portfolio.snapshot.Aggregation.aggregate(Aggregation.java:114)

	at name.abuchen.portfolio.ui.views.PerformanceChartView.addSecurityBenchmark(PerformanceChartView.java:306)

	at name.abuchen.portfolio.ui.views.PerformanceChartView.addSecurity(PerformanceChartView.java:289)

	at name.abuchen.portfolio.ui.views.PerformanceChartView.setChartSeries(PerformanceChartView.java:215)

	at name.abuchen.portfolio.ui.views.PerformanceChartView.createBody(PerformanceChartView.java:157)

	at name.abuchen.portfolio.ui.views.PerformanceChartView.createBody(PerformanceChartView.java:1)

	at name.abuchen.portfolio.ui.AbstractFinanceView.createViewControl(AbstractFinanceView.java:108)

	at name.abuchen.portfolio.ui.PortfolioPart.activateView(PortfolioPart.java:471)

	at name.abuchen.portfolio.ui.ClientEditorSidebar$ActivateViewAction.run(ClientEditorSidebar.java:64)

	at name.abuchen.portfolio.ui.Sidebar.select(Sidebar.java:253)

	at name.abuchen.portfolio.ui.Sidebar$Item$2.mouseDown(Sidebar.java:438)

	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:192)

	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)

	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4362)

	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1113)

	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4180)

	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3769)

	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1127)

	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)

	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1018)

	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)

	at org.eclipse.e4.ui.internal.workbench.swt.E4Application.start(E4Application.java:159)

	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)

	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)

	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)

	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)

	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)

	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)

	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)

	at java.lang.reflect.Method.invoke(Unknown Source)

	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:669)

	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:608)

	at org.eclipse.equinox.launcher.Main.run(Main.java:1515)

**Comment by buchen** [comment]
Unter Windows? Dann ```c:\Users\USER\AppData\Local/PortfolioPerformance/workspace/.metadata/.plugins/name.abuchen.portfolio.ui```. Einfach mal alle Dateien löschen. Die werden mit den Einstellungen wieder neu angelegt.

Der StackTrace ist schon mal hilfreich - mir ist aber noch nicht ganz klar was da passiert :-(

Es passiert wohl bei Benchmarks die über "Benchmark hinzufügen..." hinzugefügt wurde. Welcher ist das?

**Comment by JosScha** [comment]
![diagrammbeispiel](https://cloud.githubusercontent.com/assets/17599939/13471611/8d59f108-e0b1-11e5-81ef-231a0d6ba3be.PNG)

**Comment by JosScha** [comment]
Die Zusammenstellung des Diagramms habe ich nicht geändert (habe ich schon seit einem Monat in ähnlicher Form).
Ich habe ursprünglich einfach den Zeitraum auf 1 Monat reduziert. In weitere Folge habe ich es auch für 32 Tage getestet

**Comment by JosScha** [comment]
Ich konnte es auch beim DAX Beispiel nicht nachvollziehen. Also muss es schon speziell zu meinem Setting sein.

**Comment by buchen** [comment]
Es muss irgendwie an den Benchmarks liegen - also DAX, oder MSCI EM, oder MSCI World. Wenn Du die der Reihe nach weg nimmst / hinzufügst, kannst Du feststellen welcher das Probleme macht?

**Comment by JosScha** [comment]
Ich habe mal einen Datenexport "Diagrammdaten exportieren" beigefügt.
[Performance-Diagramm.csv.txt](https://github.com/buchen/portfolio/files/155440/Performance-Diagramm.csv.txt)

**Comment by JosScha** [comment]
Benchmark entfernen hilft und es sind Benchmarks die keine aktuellen Daten haben. Beide MSCI Benchmarks haben vom 29-1-2016 die letzten historischen Daten, das sind etwa 32 Tage.

**Comment by buchen** [comment]
okay, das muss ich mir jetzt näher anschauen. Aber es scheint Probleme geben, wenn es für den Benchmark in dem Zeitraum gar keine Daten gibt. Das schaue ich mir an. Aber nicht jetzt sofort. Jetzt erst mal Fußball.

**Comment by JosScha** [comment]
Ich wünsch dir viele Tore und danke.

**Comment by buchen** [comment]
Mit der nächsten version
