### ISSUE TITLE
internal error beim Update von 0.22 auf 0.22.1

### ISSUE THREAD

**Issue by megabugman** [buchen/portfolio#462]
nach dem Programmstart Update Meldung bestätigt, danach kam Fehlermeldung:
![update_fehler](https://cloud.githubusercontent.com/assets/17204819/13556866/22c19af4-e3e4-11e5-94a3-d38eb0c25306.png)
Nach einem Neustart war 0.22.1 installiert. Nach dem durchgeführten Update ist eine Reproduktion schwierig, möglicherweise reicht aber die Fehlermeldung für eine Analyse & evtl. anschließender Korrektur aus.

**Comment by buchen** [comment]
Um den Restart anzustossen, brauche ich das aktive Anwendungsfenster. Vielleicht war ein weiterer Dialog offen - dann geht das schief. Muss ich mir anschauen.

Das Update selber sollte okay sein.

**Comment by gsthys** [comment]
vielleicht als Hinweis: nach der Abfrage nach dem Update oeffnet sich ein leeres Fenster und ein zweites mit der "Internal Error" Meldung. Das Update selber ist ok, beim ersten Öffnen wird aber nur der Willkommen-Bildschirm angezeigt, andere Dateien muessen neu geoeffnet werden.

**Comment by buchen** [comment]
> Ich hab beim Neubau des Portfolios mitbekommen, man kann 2 Portfolios nebeneinander legen, oder sogar den Frame komplett aus dem Program ziehen. Tolles Feature :w00t: Dabei ist mir aber aufgefallen, ich konnte keine Aktualisierung aller historischer Kurse mehr anstoßen, da der Reiter "Datei/Online/Hilfe" im Hauptfenster blieb und nur auf das aktive Frame dort angewandt wurde. Ist das gewollt oder ein Bug?

--> Checken: vermutlich ähnliches Problem weil ich mir das falsche Objekt aus dem Application Model injizieren lasse

**Comment by buchen** [comment]
```
org.eclipse.swt.SWTException: Failed to execute runnable (java.lang.IllegalStateException: Application does not have an active window)
	at org.eclipse.swt.SWT.error(SWT.java:4491)
	at org.eclipse.swt.SWT.error(SWT.java:4406)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:138)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4024)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3700)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:827)
	at org.eclipse.jface.window.Window.open(Window.java:803)
	at name.abuchen.portfolio.ui.PortfolioPart.lambda$1(PortfolioPart.java:287)
	at name.abuchen.portfolio.ui.PortfolioPart$$Lambda$24/663413332.run(Unknown Source)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:35)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:135)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4024)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3700)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1127)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1018)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)
	at org.eclipse.e4.ui.internal.workbench.swt.E4Application.start(E4Application.java:159)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:669)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:608)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1515)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1488)
Caused by: java.lang.IllegalStateException: Application does not have an active window
	at org.eclipse.e4.ui.internal.workbench.ApplicationPartServiceImpl.getActiveWindowService(ApplicationPartServiceImpl.java:43)
	at org.eclipse.e4.ui.internal.workbench.ApplicationPartServiceImpl.saveAll(ApplicationPartServiceImpl.java:157)
	at org.eclipse.e4.ui.internal.workbench.ApplicationPartServiceImpl.saveAll(ApplicationPartServiceImpl.java:157)
	at name.abuchen.portfolio.ui.update.UpdateHelper.lambda$0(UpdateHelper.java:108)
	at name.abuchen.portfolio.ui.update.UpdateHelper$$Lambda$37/1907718598.run(Unknown Source)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:35)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:135)
	... 28 more
```

**Comment by buchen** [comment]
Der Fix ist nicht ganz die Lösung, aber zumindest gibt es eine bessere Fehlermeldung: "Dialog schliessen, speichern, dann neustarren".
