### ISSUE TITLE
Wertpapiere mit gleicher ISIN / WKN beim Import

### ISSUE THREAD

**Issue by notaword** [buchen/portfolio#477]
Hallo, mein erster Post hier!
Bei mir ist folgendes Problem aufgetreten: Ich habe ein Wertpapier mit gleicher ISIN und WKN angelegt, eines jedoch in der Währung USD mit dem NASDAQ-Ticker und eines in meiner "Hauswährung" Euro mit dem Ticker aus Frankfurt. In der Folge war es mir aber nicht mehr möglich die Import-Funktion (für **jegliche** comdirect-Importe) zu nutzen. Es hat erst eine Weile gedauert, bis ich den Zusammenhang zu den Wertpapieren mit gleicher ISIN/WKN mit Hilfe des Error-Logs identifiziert habe.
Die Wertpapiere:
![github_gleicheisinundwkn](https://cloud.githubusercontent.com/assets/18026197/13982295/72e31b90-f0e9-11e5-8e3d-0def7566c770.JPG)
Error-Log-Meldung:

> Wed Mar 23 09:00:10 CET 2016
An internal error occurred during: "comdirect".

java.lang.IllegalArgumentException: ISIN US00507V1098 existiert mehrfach

	at name.abuchen.portfolio.datatransfer.SecurityCache.failWith(SecurityCache.java:47)

	at name.abuchen.portfolio.datatransfer.SecurityCache.lambda$2(SecurityCache.java:33)

	at java.util.HashMap.merge(Unknown Source)

	at java.util.stream.Collectors.lambda$toMap$172(Unknown Source)

	at java.util.stream.ReduceOps$3ReducingSink.accept(Unknown Source)

	at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)

	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)

	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)

	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)

	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)

	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)

	at java.util.stream.ReferencePipeline.collect(Unknown Source)

	at name.abuchen.portfolio.datatransfer.SecurityCache.<init>(SecurityCache.java:32)

	at name.abuchen.portfolio.datatransfer.pdf.AbstractPDFExtractor.extract(AbstractPDFExtractor.java:65)

	at name.abuchen.portfolio.datatransfer.pdf.ComdirectPDFExtractor.extract(ComdirectPDFExtractor.java:1)

	at name.abuchen.portfolio.ui.wizards.datatransfer.ReviewExtractedItemsPage$10.run(ReviewExtractedItemsPage.java:503)

	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

Wenn man bei einem der Wertpapiere ISIN **und** WKN entfernt, ist die Benutzung der Import-Funktion wieder möglich (hat bei mir aber erstmal gedauert bis ich draufgekommen bin).

VG Tobi

**Comment by buchen** [comment]
Du hast Recht, ich sollte vielleicht nicht ganz so brutal sein und gar keine Importe mehr erlauben. Ehrlich gesagt habe ich nicht damit gerechnet, dass Benutzer Wertpapiere mit derselben ISIN / WKN mehrfach anlegen. Damit mein Programm nicht in weitere Probleme reinläuft, breche ich einfach mit dieser Fehlermeldung ab.

Ich muss mir mal überlegen wie ich damit umgehe. Wenn ich Wertpapiere mit doppelter WKN/ISIN ignoriere, dann aber Buchungen im PDF für dieses Wertpapier sind, dann würde ich ggf. das Wertpapier erneut anlegen. 

Natürlich könnte ich den Benutzer bei doppelten ISIN auch fragen - den Aufwand habe ich bisher gescheut weil ich dachte es tritt nicht so häufig auf.

Bis ich was geändert habe, führt leider kein Weg daran vorbei die ISIN und WKN für das zweite Wertpapier einfach leer zu lassen.

**Comment by buchen** [comment]
Der Import schlägt jetzt nur noch fehl (mit Fehlermeldung um UI) wenn man ein Wertpapier importieren will, das tatsächlich doppelte ISIN, WKN oder Ticker Symbole hat.
