### ISSUE TITLE
^DJI aktualisiert nicht

### ISSUE THREAD

**Issue by hjbflyer** [buchen/portfolio#480]
Beim Parsen des ^DJI gibt es einen Fehler. Wahrscheinlich wurde das Format umgestellt.

`!ENTRY name.abuchen.portfolio.ui 4 -1 2016-03-25 10:46:17.761
!MESSAGE Fehler beim Aktualisieren der Kurse
!SUBENTRY 1 name.abuchen.portfolio.ui 4 4 2016-03-25 10:46:17.762
!MESSAGE Yahoo Finance
!SUBENTRY 2 name.abuchen.portfolio.ui 4 0 2016-03-25 10:46:17.762
!MESSAGE Fehler beim Umwandeln der Werte von Yahoo Finance: "^DJI",N/A,N/A,N/A,N/A,N/A,N/A
!STACK 0
java.io.IOException: Fehler beim Umwandeln der Werte von Yahoo Finance: "^DJI",N/A,N/A,N/A,N/A,N/A,N/A
	at name.abuchen.portfolio.online.impl.YahooFinanceQuoteFeed.updateLatestQuotes(YahooFinanceQuoteFeed.java:117)
	at name.abuchen.portfolio.ui.UpdateQuotesJob.doUpdateLatestQuotes(UpdateQuotesJob.java:117)
	at name.abuchen.portfolio.ui.UpdateQuotesJob.run(UpdateQuotesJob.java:59)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: java.time.format.DateTimeParseException: Text 'N/A' could not be parsed at index 0
	at java.time.format.DateTimeFormatter.parseResolved0(DateTimeFormatter.java:1949)
	at java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1851)
	at java.time.LocalDate.parse(LocalDate.java:400)
	at name.abuchen.portfolio.online.impl.YahooHelper.asDate(YahooHelper.java:38)
	at name.abuchen.portfolio.online.impl.YahooFinanceQuoteFeed.buildPrice(YahooFinanceQuoteFeed.java:136)
	at name.abuchen.portfolio.online.impl.YahooFinanceQuoteFeed.updateLatestQuotes(YahooFinanceQuoteFeed.java:107)
	... 3 more`

**Comment by buchen** [comment]
Für den Dow Jones werden nur noch "N/A" als Werte geliefert. Ich meine ich hätte gelesen, Yahoo Finance hätte die Rechte nicht mehr. Allerdings gibt es immer noch die historischen Werte. Ich weiß es nicht genau. Allerdings kann ich hier programmatisch wenig machen, weil ich aus "N/A" not availalbe nix bekomme.
