### ISSUE TITLE
Heatmap der Performance

### ISSUE THREAD

**Issue by buchen** [buchen/portfolio#512]
Aus dem [Wertpapier Forum](http://www.wertpapier-forum.de/topic/38306-portfolio-performance-mein-neues-programm/page__view__findpost__p__1027873):
>  Darstellung der Performance in einer Heatmap.

![post-32656-0-87099900-1463310717_thumb](https://cloud.githubusercontent.com/assets/587976/15295636/b97e2f86-1b91-11e6-8450-9374ffc8cd71.png)

**Comment by simpsus** [comment]
Die Achsen sind beides Zeitachsen und unterscheiden sich in der Dimension. 
Eine Zelle ist ein Monat, ansonsten unterscheiden sich die Zellen nicht. 
Das ist eine Tabelle, weniger ein Chart mit 2 Achsen. 

Hat sich an der lib zu Charts etwas geändert? 
Wenn nein, dann geht das damit imho nicht, das ist zu unflexibel. 
Hast Du eine Idee welche lib oder Technik für eine solche Tabelle angewendet werden kann? Eine neue ist glaube ich nicht gerechtfertigt.

Ansonsten:
Wo soll das hin?
Wird die Skala durch die Werte bestimmt oder ist fix oder einstellbar?
Haben wir die historischen Werte "einer Auswahl" schon vorliegen?

**Comment by buchen** [comment]
> Das ist eine Tabelle, weniger ein Chart mit 2 Achsen.

Ich denke auch es ist eher eine Tabelle. Man könnte es direkt als Tabelle umsetzen (ähnlich zu den Dividenden). Oder vielleicht einfach "nur" ein GridLayout (es sind ja immer 12 Monatsspalten + ein Label) - da bekommt man die Formatierung schöner hin.

> Wo soll das hin?

Da habe ich mir noch gar keine Gedanken gemacht. Ich denke, wenn man es für ein Wertpapier macht, dann in einen Reiter unter Performance -> Wertpapiere. Im unteren Bereich kann man ja schon zwischen dem Kursdiagramm und den Umsätzen wählen. Da könnte man auch die Heatmap auswählen, oder?

Ich bin gerade dabei eine Art "Dashboard" zu bauen - siehe in den entsprechenden Branch. Vielleicht kann man es da als "Widget" anbieten. Dann kann man sich die Heatmap für beliebige Wertpapiere oder das gesamte Portfolio anzeigen lassen.

Einen eigenen Reiter würde ich erst mal nicht spendieren.

> Wird die Skala durch die Werte bestimmt oder ist fix oder einstellbar?

Gute Frage... müsste man etwas ausprobieren. Spontan würde ich sagen, dass eine "fixe" Skala schon passen würde. Ab -7% dunkelrot. Dann kann man das vergleichen wenn man zwischen Wertpapieren hin und her wechselt. Wie macht die Webseite justetf das denn?

> Haben wir die historischen Werte "einer Auswahl" schon vorliegen?

Du meinst *ab wann* die Werte berechnet werden? Das würde ich erst mal hart kodieren. Oder an der ersten Buchung festmachen.
Oder meinst Du die Werte in der Heatmap? Dann vermutlich TTWROR oder IZF zur Auswahl?

**Comment by simpsus** [comment]
Ich habe mir den dashboard branch angeschaut. Sieht super aus!
Ich würde den branchen und versuchen ein heatmap widget zu bauen. Mal schauen wie weit ich komme.

**Comment by buchen** [comment]
> Ich würde den branchen und versuchen ein heatmap widget zu bauen. 

👍 

Aktuell fehlt bei den Dashboard noch ein grösseres Feature: Ich will frei auswählen lassen, auf welches Objekt sich die Kennzahl bezieht. Momentan ist das immer die gesamte Datei ("Client"), aber es soll genauso gut ein Wertpapiere, eine Depot, eine Klassifikation sein. Ich weiss noch nicht genau wie ich das einbaue, aber jedes Widget zieht die Daten ja momentan aus dem `DashboardData` Objekt - irgendwo kommt das da rein. Lange Rede, kurzer Sinn: ich würde die Frage auf welches Objekt sich die Heatmap bezieht einfach erst mal ignorieren. Und wenn Du das annehmen musst, den gesamten "Client" nutzen.

**Comment by simpsus** [comment]
So, das "Hallo Welt" ist geschafft:
<img width="319" alt="screenshot 2016-06-10 16 47 47" src="https://cloud.githubusercontent.com/assets/1447101/15968174/28792f10-2f2b-11e6-89b2-5c501a10beec.png">
Was funktioniert ist aus dem Interval der ReportingPeriode zum einen die Tabelle als solche und zum anderen die Monate die zum Interval gehören zu identifizieren, siehe 75eabe6 

Jetzt brauche ich etwas Hilfe:
die update Methode des Widgets. Momentan zeichne ich labels, ich habe keine Klasse die die Referenz Monat->Widget hat sodass ich den Text updaten könnte. Auch muss ich beim Ändern der Periode ja eine andere Anzahl an Labels erstellen, das passt also nicht. Im wesentlichen will ich beim update() nochmal die createControl() aufrufen. Wie mache ich das?

Die Performance zwischen 2 Monaten. Ich habe also einen Monat und will da die Performance zum Monat zuvor haben. Wie komme ich da ran? Ist das im client schon drin? Ist das schon berechnet? Letzteres kann ich mir kaum vorstellen, denn das ist doch das erste mal dass diese beiden Monate gegeneinander betrachtet werden....

**Comment by buchen** [comment]
> Auch muss ich beim Ändern der Periode ja eine andere Anzahl an Labels erstellen, das passt also nicht. Im wesentlichen will ich beim update() nochmal die createControl() aufrufen. Wie mache ich das?

Ich denke Du könntest a) in createControl ein Composite anlegen und als Instanzvariable merken und b) in der update Methode die Kinder per #dispose löschen und neuanlagen. Eventuell wenn sich die Jahre ändern noch was wie getParent.layout(true) zum Layouting.

> Die Performance zwischen 2 Monaten. Ich habe also einen Monat und will da die Performance zum Monat zuvor haben. Wie komme ich da ran? Ist das im client schon drin? Ist das schon berechnet? Letzteres kann ich mir kaum vorstellen, denn das ist doch das erste mal dass diese beiden Monate gegeneinander betrachtet werden....

Könnte man nicht in einer Schleife entsprechende ReportingPeriods anlegen ("Letzter Tag Vormonat" bis "Letzter Tag Monat") und dann per  getDashboardData().calculate(PerformanceIndex.class, reportingPeriod);` den Wert berechnen lassen?

**Comment by simpsus** [comment]
Habemus Heatmap

<img width="348" alt="screenshot 2016-06-11 20 14 13" src="https://cloud.githubusercontent.com/assets/1447101/15986776/5e7e4d52-3011-11e6-81c8-5e64b8f5ccc2.png">

Siehe auch 29621cc

Bin auf Deine Kommentare gespannt, ob das bereit für einen pull request in feature_dashboard ist ...

**Comment by buchen** [comment]
Hi @simpsus,

sieht doch schon gut aus! 😄

Ich habe ganz kurz über den Code geschaut, dabei sind mir ein paar Kleinigkeiten aufgefallen:
* Bisher hat jedes Widget eine Bezeichnung ("label") an die ich die Kontextmenüs hänge (`attachContextMenu`). Die Bezeichnung existiert unabhängig davon ob der Benutzer noch eine "fette" Überschrift verwendet.
* SWT Resources müssen wie Fonts und Farben müssen explizit freigegeben werden ("disposed"). Wiederverwendete Resourcen habe ich in `DashboardResources` gesteckt. Da könnte auch der kleine Font hin. Vielleicht macht es Sinn den `LocalResourceManager` für die Farben wiederzuverwenden? Ansonsten mindestens lokal im Widget eine Instanz halten.
* Bei der Heatmap macht es vielleicht Sinn die Spalten für die Monate alle gleich breit zu machen.

Schönes WE noch!

**Comment by simpsus** [comment]
220d701 (Ich hatte eine Datei vergessen und dann ... keine Ahnung)

Das mit dem Label habe ich verstanden. Ich habe mir dann von anderen abgeschaut, dass der Text mit `getWidget().getLabel()` gesetzt wird. Macht Sinn. Bringt mir aber eine NPE. Keine Ahnung warum ...

Ich habe den Font in die `DashboardResources` verschoben. Macht Sinn wenn es extra sowas gibt. 

Bei den Farben bin ich mir nicht ganz sicher. Ich habe jetzt den `LocalResourceManager`exponiert und dort die Farben erstellt und registriert. Reicht das?

Das mit den gleichbreiten Spalten habe ich probiert, aber es nur hinbekommen, dass alle Spalten gleichgroß sind. Damit sind die Jahresspalten zu klein. Wenn alle Monatsspalten gleichgroß wären, und sie so groß sind dass eine Minuszahl mit Nachkomma rein passt, dann ist das Widget zu breit.

**Comment by buchen** [comment]
> Ich habe jetzt den LocalResourceManagerexponiert und dort die Farben erstellt und registriert. Reicht das?

Ich denke das passt. Hauptsache die Ressourcen werden freigegeben 😉 

> Ich habe mir dann von anderen abgeschaut, dass der Text mit getWidget().getLabel() gesetzt wird. Macht Sinn. Bringt mir aber eine NPE.

Stacktrace?

> Das mit den gleichbreiten Spalten habe ich probiert, aber es nur hinbekommen, dass alle Spalten gleichgroß sind. 

Ah, die Jahresspalte. Vielleicht per "hint" auf der Zelle direkt (siehe auch GridDataFactory)? Es ist ja eher ein kleines Detail.... Schick mir einen PR wenn es soweit ist.

**Comment by simpsus** [comment]
Stacktrace:
`java.lang.IllegalArgumentException: Argument cannot be null
	at org.eclipse.swt.SWT.error(SWT.java:4472)
	at org.eclipse.swt.SWT.error(SWT.java:4406)
	at org.eclipse.swt.SWT.error(SWT.java:4377)
	at org.eclipse.swt.widgets.Widget.error(Widget.java:799)
	at org.eclipse.swt.widgets.Label.setText(Label.java:523)
	at name.abuchen.portfolio.ui.views.dashboard.PerformanceHeatmapWidget.fillTable(PerformanceHeatmapWidget.java:75)
	at name.abuchen.portfolio.ui.views.dashboard.PerformanceHeatmapWidget.createControl(PerformanceHeatmapWidget.java:45)
	at name.abuchen.portfolio.ui.views.dashboard.DashboardView.buildDelegate(DashboardView.java:313)
	at name.abuchen.portfolio.ui.views.dashboard.DashboardView.buildColumns(DashboardView.java:273)
	at name.abuchen.portfolio.ui.views.dashboard.DashboardView.selectDashboard(DashboardView.java:432)
	at name.abuchen.portfolio.ui.views.dashboard.DashboardView.createBody(DashboardView.java:256)
	at name.abuchen.portfolio.ui.AbstractFinanceView.createViewControl(AbstractFinanceView.java:108)
	at name.abuchen.portfolio.ui.PortfolioPart.createView(PortfolioPart.java:499)
	at name.abuchen.portfolio.ui.PortfolioPart.activateView(PortfolioPart.java:478)
	at name.abuchen.portfolio.ui.ClientEditorSidebar$ActivateViewAction.run(ClientEditorSidebar.java:64)
	at name.abuchen.portfolio.ui.Sidebar.select(Sidebar.java:253)
	at name.abuchen.portfolio.ui.Sidebar$Item$2.mouseDown(Sidebar.java:438)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:192)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4230)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1491)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1514)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1499)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1299)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4072)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3698)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1127)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1018)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)
	at org.eclipse.e4.ui.internal.workbench.swt.E4Application.start(E4Application.java:159)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:669)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:608)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1515)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1488)`

Die Zeile 75 in dem Widget ist:`title.setText(getWidget().getLabel());`
Ich stelle jetzt den PR und dann können wir das da weiter diskutieren.

**Comment by simpsus** [comment]
Keine Ahnung ob das hier her passt.
Ich habe den aktuellen feature_dashboard gebranched um die Tooltips einzufügen.
Ich bekomme aber immernoch die selbe NPE die ich auch schon weiter oben moniere. Bei Dir geht das bestimmt, denn sonst wäre das nicht so eingechecked. Hast Du irgendeine Idee was das sein könnte? ansonsten muss ich das auskommentieren und Du dann beim merge cherry picken:

java.lang.IllegalArgumentException: Argument cannot be null
	at org.eclipse.swt.SWT.error(SWT.java:4472)
	at org.eclipse.swt.SWT.error(SWT.java:4406)
	at org.eclipse.swt.SWT.error(SWT.java:4377)
	at org.eclipse.swt.widgets.Widget.error(Widget.java:799)
	at org.eclipse.swt.widgets.Label.setText(Label.java:523)
	at name.abuchen.portfolio.ui.views.dashboard.PerformanceHeatmapWidget.createControl(PerformanceHeatmapWidget.java:50)
	at name.abuchen.portfolio.ui.views.dashboard.DashboardView.buildDelegate(DashboardView.java:335)

**Comment by buchen** [comment]
Das Label in de Widget ist null. Das darf eigentlich nicht passieren, weil das immer mit Label angelegt wird. Ich vermute mal, Du testet mit einer Datei die vielleicht einen komischen Zwischenstand hatte?!?

**Comment by simpsus** [comment]
Ich denke nicht, das war auf dem vorherigen branch auch so. Das sind immer
branches die ich von deinem feature_dashboard genommen habe (head). ganz
diabolischer verdacht: Ist evtl. eine Datei in dem branch nicht hochgeladen
oä?

**Comment by buchen** [comment]
Tritt das auf wenn Du ein *neues* Dashbaord anlegst?

**Comment by buchen** [comment]
Ansonsten müssten man immer auf "null" im Label prüfen und ggf. #setText mit einem leeren String aufzurufen.
