### ISSUE TITLE
Unable to process "ReBalancingViewer#setUseIndirectQuotation()" on opening classifications

### ISSUE THREAD

**Issue by sebasbaumh** [buchen/portfolio#521]
_Version:_ 0.23.2.201605311949

_Steps to reproduce:_
- Create a new file
- Add a stock
- Add "Region" to classifications
- Select the "Region" classification
- only an error is shown:

```
Unable to process "ReBalancingViewer#setUseIndirectQuotation()": no actual value was found for the argument "boolean".

org.eclipse.e4.core.di.InjectionException: Unable to process "ReBalancingViewer#setUseIndirectQuotation()": no actual value was found for the argument "boolean".
    at org.eclipse.e4.core.internal.di.InjectorImpl.reportUnresolvedArgument(InjectorImpl.java:424)
    at org.eclipse.e4.core.internal.di.InjectorImpl.resolveRequestorArgs(InjectorImpl.java:415)
    at org.eclipse.e4.core.internal.di.InjectorImpl.inject(InjectorImpl.java:110)
    at org.eclipse.e4.core.internal.di.InjectorImpl.internalMake(InjectorImpl.java:345)
    at org.eclipse.e4.core.internal.di.InjectorImpl.make(InjectorImpl.java:278)
    at org.eclipse.e4.core.contexts.ContextInjectionFactory.make(ContextInjectionFactory.java:186)
    at name.abuchen.portfolio.ui.AbstractFinanceView.make(AbstractFinanceView.java:198)
    at name.abuchen.portfolio.ui.views.taxonomy.TaxonomyView.createBody(TaxonomyView.java:164)
    at name.abuchen.portfolio.ui.AbstractFinanceView.createViewControl(AbstractFinanceView.java:108)
    at name.abuchen.portfolio.ui.PortfolioPart.createView(PortfolioPart.java:499)
    at name.abuchen.portfolio.ui.PortfolioPart.activateView(PortfolioPart.java:478)
    at name.abuchen.portfolio.ui.ClientEditorSidebar$ActivateViewAction.run(ClientEditorSidebar.java:64)
    at name.abuchen.portfolio.ui.Sidebar.select(Sidebar.java:253)
    at name.abuchen.portfolio.ui.ClientEditorSidebar.addAndOpenTaxonomy(ClientEditorSidebar.java:518)
    at name.abuchen.portfolio.ui.ClientEditorSidebar.access$8(ClientEditorSidebar.java:512)
    at name.abuchen.portfolio.ui.ClientEditorSidebar$11.run(ClientEditorSidebar.java:411)
    at org.eclipse.jface.action.Action.runWithEvent(Action.java:473)
    at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:595)
    at org.eclipse.jface.action.ActionContributionItem.access$2(ActionContributionItem.java:511)
    at org.eclipse.jface.action.ActionContributionItem$5.handleEvent(ActionContributionItem.java:420)
    at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
    at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4362)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1113)
    at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4180)
    at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3769)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1127)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1018)
    at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)
    at org.eclipse.e4.ui.internal.workbench.swt.E4Application.start(E4Application.java:159)
    at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:669)
    at org.eclipse.equinox.launcher.Main.basicRun(Main.java:608)
    at org.eclipse.equinox.launcher.Main.run(Main.java:1515)
```

**Comment by buchen** [comment]
Ich habe den Fehler ebenfalls schon mal gesehen. Bisher aber nur in meiner Entwicklungsumgebung. Da hat ein "clean build" geholfen.

Ansonsten habe ich nicht verstanden woher das Problem kommt.

**Comment by sunnylars** [comment]
In meiner Entwicklungsumgebung kann ich ihn reproduzieren mit meinen Live Daten.
Hatte den Fehler an einem anderen PC mit der donwgeloadeten Version und meinen Live Daten.

Ich schau mal, ob ich was raus finde

**Comment by buchen** [comment]
:+1: Eigentlich sollte durch den [PreferencesInitializer](https://github.com/buchen/portfolio/blob/master/name.abuchen.portfolio.ui/src/name/abuchen/portfolio/ui/preferences/PreferencesInitializer.java#L17) immer ein Wert vorhanden sein. Mir ist unklar - und nicht reproduzierbar - unter welchen Umständen der Wert nicht existiert.

**Comment by sebasbaumh** [comment]
Ich teste es nochmal mit einem Clean-Build, obwohl ich das eigentlich gemacht hatte.

**Comment by sebasbaumh** [comment]
Bei mir taucht der Fehler wieder auf.
Ich habe versucht, `C:\Users\$USERNAME\AppData\Local\PortfolioPerformance\` zu löschen - bringt aber auch nichts.

Auch das Leeren aller `target`-Verzeichnisse in allen Projektordnern ändert leider daran nichts.
Kann man den `PreferencesInitializer` irgendwie aktiv anstoßen?

**Comment by buchen** [comment]
> Kann man den PreferencesInitializer irgendwie aktiv anstoßen?

Ich kenne mich in der Ecke von dem Eclipse e4 nicht gut genug aus um das sagen zu können.

Das ist aber wieder in Deiner "Build" Umgebung passiert, oder? Und nicht in einer normalen Installation

**Comment by sebasbaumh** [comment]
Es ist seltsam...
Zwischendurch hat es beim Debuggen funktioniert und nach dem Bauen der Anwendung sowohl beim Start der Exe als auch beim Debuggen nicht mehr - obwohl dann beide einen unterschiedlichen Workspace nutzen.
Im Maven habe ich nur ein `clean package` bei der `portfolio-app` ausgeführt.

**Comment by sebasbaumh** [comment]
Ich habe es auf einem anderen Rechner mit eclipse noch einmal neu gebaut und diese Fassung funktioniert seltsamerweise.

Vielleicht lässt es sich eingrenzen, wenn ich bei meinem Rechner mal einen neuen Workspace nur mit portfolio aufbaue.

**Comment by buchen** [comment]
Ich habe das Problem schon lange nicht mehr gehabt. Gerade habe ich die Eclipse Version auf Neon hochgesetzt. Hast Du die Target Platform angepasst - vielleicht entsteht durch so einen "mismatch" das Problem.

**Comment by sebasbaumh** [comment]
In einem neuen eclipse Workspace mit frisch ausgechecktem portfolio besteht das Problem nicht.
Ich vermute daher ein Problem mit meinem normalen Workspace und schließe das Ticket mal hier.
