### ISSUE TITLE
Internal Error bei Update

### ISSUE THREAD

**Issue by megabugman** [buchen/portfolio#527]
der Fehler wurde [hier](https://github.com/buchen/portfolio/issues/462) bereits gemeldet und ein "fix" implementiert, jedoch besteht das Problem weiterhin. Beim Update erhalte ich lediglich die Meldung 
![01](https://cloud.githubusercontent.com/assets/17204819/15834445/dd19ab5a-2c2b-11e6-9fcb-5d148981671f.png)
Fehlerprotokoll:
![02](https://cloud.githubusercontent.com/assets/17204819/15834457/e8a6aba8-2c2b-11e6-8f50-5f7df80aed53.png)
Error Log:
Mon Jun 06 20:58:20 CEST 2016
Internal Error

org.eclipse.swt.SWTException: Failed to execute runnable (java.lang.IllegalStateException: Application does not have an active window)

	at org.eclipse.swt.SWT.error(SWT.java:4491)

	at org.eclipse.swt.SWT.error(SWT.java:4406)

	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:138)

	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4155)

	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3772)

	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1127)

	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)

	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1018)

	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)

	at org.eclipse.e4.ui.internal.workbench.swt.E4Application.start(E4Application.java:159)

	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)

	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)

	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)

	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)

	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)

	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

	at java.lang.reflect.Method.invoke(Method.java:497)

	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:669)

	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:608)

	at org.eclipse.equinox.launcher.Main.run(Main.java:1515)

Caused by: java.lang.IllegalStateException: Application does not have an active window

	at org.eclipse.e4.ui.internal.workbench.ApplicationPartServiceImpl.getActiveWindowService(ApplicationPartServiceImpl.java:36)

	at org.eclipse.e4.ui.internal.workbench.ApplicationPartServiceImpl.saveAll(ApplicationPartServiceImpl.java:157)

	at name.abuchen.portfolio.ui.update.UpdateHelper.lambda$2(UpdateHelper.java:103)

	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:35)

	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:135)

	... 19 more

Nach Restart scheint alles i.O. das Update **scheint** korrekt ausgeführt worden zu sein.

**Comment by buchen** [comment]
Der Fehler passiert *nach* dem Update, und zwar *vor* dem Restart wenn es darum geht all offenen Dateien zu löschen. Das Update an sich ist okay, denke ich.

Frage: Weißt Du noch von welcher Version Du aktualisiert hast? Von 0.23.0 (aktuell ist 0.23.1)

**Comment by buchen** [comment]
Hintergrund: wenn es von einer älteren Version wäre, dann würde es den Fehler erklären. Es braucht ja erst mal ein Update, um die Fehlerbehebung einzuspielen. Und die kam erst mit 0.23.0, also am 24. April.

**Comment by megabugman** [comment]
hört sich logisch an. ich denke ich habe von 0.22.0 aktualisiert.

**Comment by buchen** [comment]
Schauen wir mal ob meine Theorie stimmt ... beim nächsten Update 😄
