### ISSUE TITLE
Kursaktualisierung nicht möglich

### ISSUE THREAD

**Issue by peter149** [buchen/portfolio#530]
Habe Vers. 0.23.1 in Windows 10 / java 32-bit installiert.
Wertpapiere lassen sich anlegen. Historische Kurse Lieferant Yahoo Finance; als Boersenplatz wird vom System automatisch der Ticker des Wertpapieres eingetragen; keine Boersenauswahl möglich.
Bei Kursaktualisierung keine Reaktion.
Nachstehdnd Fehlermeldung
Wed Jun 08 18:48:17 CEST 2016
Dt. Telekom
------
Wed Jun 08 18:48:17 CEST 2016
ichart.finance.yahoo.com
java.net.UnknownHostException: ichart.finance.yahoo.com
	at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
	at java.net.PlainSocketImpl.connect(Unknown Source)
	at java.net.SocksSocketImpl.connect(Unknown Source)
	at java.net.Socket.connect(Unknown Source)
	at java.net.Socket.connect(Unknown Source)
	at sun.net.NetworkClient.doConnect(Unknown Source)
	at sun.net.www.http.HttpClient.openServer(Unknown Source)
	at sun.net.www.http.HttpClient.openServer(Unknown Source)
	at sun.net.www.http.HttpClient.<init>(Unknown Source)
	at sun.net.www.http.HttpClient.New(Unknown Source)
	at sun.net.www.http.HttpClient.New(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.connect(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at java.net.URL.openStream(Unknown Source)
	at name.abuchen.portfolio.online.impl.YahooFinanceQuoteFeed.openStream(YahooFinanceQuoteFeed.java:362)
	at name.abuchen.portfolio.online.impl.YahooFinanceQuoteFeed.openReader(YahooFinanceQuoteFeed.java:350)
	at name.abuchen.portfolio.online.impl.YahooFinanceQuoteFeed.internalGetQuotes(YahooFinanceQuoteFeed.java:228)
	at name.abuchen.portfolio.online.impl.YahooFinanceQuoteFeed.updateHistoricalQuotes(YahooFinanceQuoteFeed.java:162)
	at name.abuchen.portfolio.ui.UpdateQuotesJob$2.run(UpdateQuotesJob.java:262)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

------

**Comment by buchen** [comment]
Die Meldung `java.net.UnknownHostException` heißt, das Programm kann auf den Server nicht zugreifen. Die URL stimmt. Ist da eine Firewall installiert / aktiviert, die verhindert, dass PP die Kurse abrufen kann?

**Comment by peter149** [comment]
Problem ist gelöst. Nach Abschalten von Kaspersky funktioniert der Datenabruf. Danke für die schnelle Lösung. Ich werde das Programm sicher gut nutzen können.
