### ISSUE TITLE
Duplicate key name.abuchen.portfolio.ui.views.dataseries.DataSeries@4a34e9f

### ISSUE THREAD

**Issue by buchen** [buchen/portfolio#571]
Guten Morgen,

erstmal ein dickes Lob für dieses Programm. Etwas vergleichbares habe ich, auch nach langer Suche, bis jetzt noch nicht gefunden.
Das Dashboard ist ne Wucht und ergibt eine Menge Möglichkeiten seine Übersicht individuell einzurichten.
Leider habe ich seit dem Update ein Problem mit meinen Diagrammen und komme nicht weiter.
Folgend habe ich den Fehlercode angehängt.

Vielen Dank für Deine Hilfe

Gruß
louismiguel

```
Duplicate key name.abuchen.portfolio.ui.views.dataseries.DataSeries@4a34e9f

java.lang.IllegalStateException: Duplicate key name.abuchen.portfolio.ui.views.dataseries.DataSeries@4a34e9f
at java.util.stream.Collectors.lambda$throwingMerger$107(Collectors.java:133)
at java.util.stream.Collectors$Lambda$164/1935870377.apply(Unknown Source)
at java.util.HashMap.merge(HashMap.java:1245)
at java.util.stream.Collectors.lambda$toMap$165(Collectors.java:1320)
at java.util.stream.Collectors$Lambda$166/411787317.accept(Unknown Source)
at java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512)
at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
at name.abuchen.portfolio.ui.views.dataseries.DataSeriesSerializer.load(DataSeriesSerializer.java:40)
at name.abuchen.portfolio.ui.views.dataseries.DataSeriesSerializer.fromString(DataSeriesSerializer.java:24)
at name.abuchen.portfolio.ui.views.dataseries.DataSeriesConfigurator.<init>(DataSeriesConfigurator.java:63)
at name.abuchen.portfolio.ui.views.StatementOfAssetsHistoryView.createBody(StatementOfAssetsHistoryView.java:124)
at name.abuchen.portfolio.ui.views.StatementOfAssetsHistoryView.createBody(StatementOfAssetsHistoryView.java:1)
at name.abuchen.portfolio.ui.AbstractFinanceView.createViewControl(AbstractFinanceView.java:108)
at name.abuchen.portfolio.ui.PortfolioPart.createView(PortfolioPart.java:499)
at name.abuchen.portfolio.ui.PortfolioPart.activateView(PortfolioPart.java:478)
at name.abuchen.portfolio.ui.ClientEditorSidebar$ActivateViewAction.run(ClientEditorSidebar.java:64)
at name.abuchen.portfolio.ui.Sidebar.select(Sidebar.java:253)
at name.abuchen.portfolio.ui.Sidebar$Item$2.mouseDown(Sidebar.java:438)
at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:192)
at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4230)
at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1491)
at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1514)
at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1499)
at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1299)
at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4072)
at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3698)
at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1127)
at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1018)
at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)
at org.eclipse.e4.ui.internal.workbench.swt.E4Application.start(E4Application.java:159)
at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:483)
at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:669)
at org.eclipse.equinox.launcher.Main.basicRun(Main.java:608)
at org.eclipse.equinox.launcher.Main.run(Main.java:1515) 
```

**Comment by buchen** [comment]
Problem: einige Wertpapiere haben keine UUID
