### ISSUE TITLE
Internal Error - org.eclipse.swt.SWTException: Widget is disposed

### ISSUE THREAD

**Issue by nikzim** [buchen/portfolio#620]
Bei mir hat sich Portfolio Performance v0.25.0 beim Erstellen von Kontobewegungen im Bereich "Stammdaten -> Konten" mit dem o.g. Fehler aufgehängt. Ich nutze OSX 10.11.6. Das Programm hat dann 100% Prozessorlast erzeugt. Ich konnte es nur noch über "Sofort Beenden" schließen.

Ich habe einen Screenshot der Fehlermeldung sowie den OS X Fehlerbericht und eine "Activity Monitor" Analyse angehängt.

Ich kann den Fehler zur Zeit nicht reproduzieren.
[Analyse_Portfolio_Performance_SWTExeption.txt](https://github.com/buchen/portfolio/files/471819/Analyse_Portfolio_Performance_SWTExeption.txt)
[Fehlerbericht_Performance_Portfolio.txt](https://github.com/buchen/portfolio/files/471820/Fehlerbericht_Performance_Portfolio.txt)
![swtexeption-widget_disposed](https://cloud.githubusercontent.com/assets/22193170/18509444/fb5021f8-7a78-11e6-881a-7190a5e669b8.png)

**Comment by buchen** [comment]
Das sieht nach einem Fehler in der Java VM aus - wenn ich auf die Textdateien schauen.
Der Screenshot passt da nicht ganz dazu - das sieht nach einem Fehler in meinem Programm aus.

Die Traces der VM ist von 12:17 und 12:32. Eigentlich sollte dann die Anwendung beendet werden. Ist der Dialog davor angezeigt worden?

**Comment by nikzim** [comment]
Zunächst kam die Fehlermeldung und das Programm hing komplett mit 100% Prozessorlast. Das Programm ließ sich nicht mehr bedienen (Anzeige des drehenden "Beachballs", wenn ich mit der Maus über dem Programmfenster war), ich konnte noch nicht einmal im Dialog-Fenster die Details der Fehlermeldung öffnen, oder die Fehlermeldung durch "OK" schließen.

Ich habe dann im "Activity Monitor" nachgeschaut was los ist und mir darin die "Analyse" des Portfolio Performance Prozesses ausgeben lassen (um 12:17).

Ich habe dann das Programm noch etwas weiterlaufen lassen, in der Hoffnung, es gäbe ein Timeout und das Programm könnte sich von selbst wieder fangen. Als dies nicht passierte, habe ich es um 12:32 über "Sofort Beenden" geschlossen und habe dann von OSX den "Fehlerbericht" geliefert bekommen.

**Comment by buchen** [comment]
Ah okay, Danke für die Rückmeldung.

So ein Trace deutet immer auf ein Problem mit der Java VM hin. Das liegt außerhalb von meinem Code. Was ich aber verhindern kann, dass es zu der "Widget disposed" Meldung kommt (und damit hoffentlich auch zu dem Crash). Dazu bräuchte ich vor allem das vollständige Log.

Das liegt unter ```~/Library/Application\ Support/name.abuchen.portfolio.product/workspace/.metadata/.log```. Könntest Du das an den Issue anhängen oder mir per Mail an portfolio DOT performance DOT help AT gmail DOT com schicken? Da sollte nichts sensitives Drinstehen, aber von (möglichen) Fehlermeldungen vom Kursdownload könnte man natürlich zurück schliessen welche Wertpapiere Du haben könntest.

**Comment by nikzim** [comment]
Ich habe den Teil für die entsprechende Session, wo der Fehler aufgetreten ist, mal aus dem langen Log-file rauskopiert. Die diversen "Yahoo Finance" Fehlermeldungen bzgl. Kursdownload aus der Session habe ich auch rausgelöscht. 
Ich hoffe, damit hast Du die Informationen die Du benötigst.
Die Session wo das Problem aufgetreten ist, startete am 12.09.2016. Der Fehler ist dann am 14.09. um 12:09. Ich habe das Programm am 14.09. um 12:36 erneut gestartet.
[log_2016-09-14.txt](https://github.com/buchen/portfolio/files/475321/log_2016-09-14.txt)

**Comment by buchen** [comment]
Passt. Das ist der relevante Exception Stack Trace. Allein, da wird gar kein PP Code durchlaufen.
Tritt das häufig auf? Oder war das eine einmalige Geschichte? Meine Beste Chance ist die SWT Bibliothek zu aktualisieren - das habe ich mit #522 vor, bin aber noch nicht dazu gekommen.

```
org.eclipse.swt.SWTException: Widget is disposed
	at org.eclipse.swt.SWT.error(SWT.java:4491)
	at org.eclipse.swt.SWT.error(SWT.java:4406)
	at org.eclipse.swt.SWT.error(SWT.java:4377)
	at org.eclipse.swt.widgets.Widget.error(Widget.java:799)
	at org.eclipse.swt.widgets.Widget.checkWidget(Widget.java:588)
	at org.eclipse.swt.widgets.Control.getVisible(Control.java:2023)
	at org.eclipse.swt.widgets.DateTime.isDropped(DateTime.java:465)
	at org.eclipse.swt.widgets.DateTime.hideCalendar(DateTime.java:321)
	at org.eclipse.swt.widgets.DateTime$1.handleEvent(DateTime.java:230)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.filterEvent(Display.java:1105)
```

**Comment by nikzim** [comment]
Das Problem ist bisher nur einmal aufgetreten und ich konnte es bisher nicht reproduzieren.

**Comment by vv01f** [comment]
Eventuell hilft das über das Auftreten bei mir hinaus…

Ich kann in 0.44 den gleichen Fehler provozieren indem ich das Fenster horizontal verkleinere (z. B. per [Super]+[Rechts] an den rechten Bildschirmrand stauche) und dann in die Ansicht "Performance" wechsel. Das ist hier reproduzierbar.

log:
```
Fri Jan 24 09:46:08 CET 2020
Internal Error

org.eclipse.e4.core.di.InjectionException: org.eclipse.swt.SWTException: Widget is disposed
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:68)
	at org.eclipse.e4.ui.internal.di.UIEventObjectSupplier$UIEventHandler$1.run(UIEventObjectSupplier.java:67)
	at org.eclipse.swt.widgets.Synchronizer.syncExec(Synchronizer.java:236)
	at org.eclipse.swt.widgets.Display.syncExec(Display.java:5941)
	at org.eclipse.e4.ui.internal.workbench.swt.E4Application$1.syncExec(E4Application.java:215)
	at org.eclipse.e4.ui.internal.di.UIEventObjectSupplier$UIEventHandler.handleEvent(UIEventObjectSupplier.java:64)
	at org.eclipse.equinox.internal.event.EventHandlerWrapper.handleEvent(EventHandlerWrapper.java:204)
	at org.eclipse.equinox.internal.event.EventHandlerTracker.dispatchEvent(EventHandlerTracker.java:199)
	at org.eclipse.equinox.internal.event.EventHandlerTracker.dispatchEvent(EventHandlerTracker.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:233)
	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:151)
	at org.eclipse.equinox.internal.event.EventAdminImpl.dispatchEvent(EventAdminImpl.java:138)
	at org.eclipse.equinox.internal.event.EventAdminImpl.sendEvent(EventAdminImpl.java:81)
	at org.eclipse.equinox.internal.event.EventComponent.sendEvent(EventComponent.java:42)
	at org.eclipse.e4.ui.services.internal.events.EventBroker.send(EventBroker.java:55)
	at org.eclipse.e4.ui.workbench.UIEvents.publishEvent(UIEvents.java:378)
	at org.eclipse.e4.ui.workbench.UIEvents.publishEvent(UIEvents.java:347)
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.activate(PartServiceImpl.java:731)
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.activate(PartServiceImpl.java:684)
	at org.eclipse.e4.ui.internal.workbench.swt.AbstractPartRenderer.activate(AbstractPartRenderer.java:97)
	at org.eclipse.e4.ui.workbench.renderers.swt.ContributedPartRenderer.lambda$0(ContributedPartRenderer.java:63)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5797)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1374)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1400)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1383)
	at org.eclipse.swt.widgets.Shell.setActiveControl(Shell.java:1920)
	at org.eclipse.swt.widgets.Shell.setActiveControl(Shell.java:1883)
	at org.eclipse.swt.widgets.Control.sendFocusEvent(Control.java:4446)
	at org.eclipse.swt.widgets.Control.gtk_event_after(Control.java:3605)
	at org.eclipse.swt.widgets.Tree.gtk_event_after(Tree.java:2315)
	at org.eclipse.swt.widgets.Widget.windowProc(Widget.java:1976)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:6524)
	at org.eclipse.swt.widgets.Tree.windowProc(Tree.java:4193)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:6014)
	at org.eclipse.swt.internal.gtk.GTK._gtk_widget_grab_focus(Native Method)
	at org.eclipse.swt.internal.gtk.GTK.gtk_widget_grab_focus(GTK.java:8893)
	at org.eclipse.swt.widgets.Control.forceFocus(Control.java:2839)
	at org.eclipse.swt.widgets.Composite.forceFocus(Composite.java:656)
	at org.eclipse.swt.widgets.Control.forceFocus(Control.java:2832)
	at org.eclipse.swt.widgets.Control.setFocus(Control.java:5161)
	at org.eclipse.swt.widgets.Composite.setFocus(Composite.java:1648)
	at org.eclipse.swt.widgets.Composite.setFocus(Composite.java:1646)
	at org.eclipse.swt.widgets.Composite.setFocus(Composite.java:1646)
	at org.eclipse.swt.custom.CTabFolder.setFocus(CTabFolder.java:2645)
	at org.eclipse.swt.widgets.Control.fixFocus(Control.java:278)
	at org.eclipse.swt.widgets.Control.releaseWidget(Control.java:4381)
	at org.eclipse.swt.widgets.Composite.releaseWidget(Composite.java:1546)
	at org.eclipse.swt.widgets.ToolBar.releaseWidget(ToolBar.java:562)
	at org.eclipse.swt.widgets.Widget.release(Widget.java:1199)
	at org.eclipse.swt.widgets.Control.release(Control.java:4358)
	at org.eclipse.swt.widgets.Composite.releaseChildren(Composite.java:1532)
	at org.eclipse.swt.widgets.Widget.release(Widget.java:1190)
	at org.eclipse.swt.widgets.Control.release(Control.java:4358)
	at org.eclipse.swt.widgets.Composite.releaseChildren(Composite.java:1532)
	at org.eclipse.swt.widgets.Widget.release(Widget.java:1190)
	at org.eclipse.swt.widgets.Control.release(Control.java:4358)
	at org.eclipse.swt.widgets.Widget.dispose(Widget.java:502)
	at name.abuchen.portfolio.ui.editor.PortfolioPart.disposeView(PortfolioPart.java:539)
	at name.abuchen.portfolio.ui.editor.PortfolioPart.activateView(PortfolioPart.java:488)
	at name.abuchen.portfolio.ui.editor.PortfolioPart.activateView(PortfolioPart.java:480)
	at name.abuchen.portfolio.ui.editor.ClientEditorSidebar$1.select(ClientEditorSidebar.java:68)
	at name.abuchen.portfolio.ui.editor.ClientEditorSidebar$1.select(ClientEditorSidebar.java:1)
	at name.abuchen.portfolio.ui.editor.Sidebar$Entry.handleMouseDown(Sidebar.java:389)
	at org.eclipse.swt.events.MouseListener$2.mouseDown(MouseListener.java:96)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:196)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5797)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1374)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:5051)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4583)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1173)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1062)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)
	at org.eclipse.e4.ui.internal.workbench.swt.E4Application.start(E4Application.java:165)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:199)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:391)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:246)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:595)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1501)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1474)
Caused by: org.eclipse.swt.SWTException: Widget is disposed
	at org.eclipse.swt.SWT.error(SWT.java:4595)
	at org.eclipse.swt.SWT.error(SWT.java:4510)
	at org.eclipse.swt.SWT.error(SWT.java:4481)
	at org.eclipse.swt.widgets.Widget.error(Widget.java:506)
	at org.eclipse.swt.widgets.Widget.checkWidget(Widget.java:443)
	at org.eclipse.swt.custom.CTabItem.getControl(CTabItem.java:170)
	at org.eclipse.e4.ui.css.swt.dom.CTabFolderElement.getVisibleChildNodes(CTabFolderElement.java:161)
	at org.eclipse.e4.ui.css.core.impl.engine.AbstractCSSEngine.applyStyles(AbstractCSSEngine.java:431)
	at org.eclipse.e4.ui.css.core.impl.engine.AbstractCSSEngine.applyStyles(AbstractCSSEngine.java:364)
	at org.eclipse.e4.ui.css.core.impl.engine.AbstractCSSEngine.applyStyles(AbstractCSSEngine.java:435)
	at org.eclipse.e4.ui.css.core.impl.engine.AbstractCSSEngine.applyStyles(AbstractCSSEngine.java:364)
	at org.eclipse.e4.ui.css.core.impl.engine.AbstractCSSEngine.applyStyles(AbstractCSSEngine.java:435)
	at org.eclipse.e4.ui.css.core.impl.engine.AbstractCSSEngine.applyStyles(AbstractCSSEngine.java:364)
	at org.eclipse.e4.ui.css.core.impl.engine.AbstractCSSEngine.applyStyles(AbstractCSSEngine.java:435)
	at org.eclipse.e4.ui.css.core.impl.engine.AbstractCSSEngine.applyStyles(AbstractCSSEngine.java:364)
	at org.eclipse.e4.ui.css.core.impl.engine.AbstractCSSEngine.applyStyles(AbstractCSSEngine.java:435)
	at org.eclipse.e4.ui.css.core.impl.engine.AbstractCSSEngine.applyStyles(AbstractCSSEngine.java:364)
	at org.eclipse.e4.ui.css.core.impl.engine.AbstractCSSEngine.applyStyles(AbstractCSSEngine.java:435)
	at org.eclipse.e4.ui.css.core.impl.engine.AbstractCSSEngine.applyStyles(AbstractCSSEngine.java:364)
	at org.eclipse.e4.ui.css.core.impl.engine.AbstractCSSEngine.applyStyles(AbstractCSSEngine.java:435)
	at org.eclipse.e4.ui.css.core.impl.engine.AbstractCSSEngine.applyStyles(AbstractCSSEngine.java:364)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$8.setClassnameAndId(PartRenderingEngine.java:1392)
	at org.eclipse.e4.ui.workbench.renderers.swt.SWTPartRenderer.setCSSInfo(SWTPartRenderer.java:114)
	at org.eclipse.e4.ui.workbench.renderers.swt.SWTPartRenderer.styleElement(SWTPartRenderer.java:84)
	at org.eclipse.e4.ui.workbench.renderers.swt.StackRenderer.subscribeTopicActivateChanged(StackRenderer.java:536)
	at jdk.internal.reflect.GeneratedMethodAccessor21.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:58)
	... 88 more
```

**Comment by ndsvw** [comment]
Ich bekam diesen Error gerade durch einen Rechtsklick auf ein Konto in der Kontoübersicht. Ließ sich aber nicht wieder reproduzieren. Version: 0.61.4 (März 2023)


```
Mon Apr 03 17:50:33 CEST 2023
Internal Error

org.eclipse.swt.SWTException: Widget is disposed
	at org.eclipse.swt.SWT.error(SWT.java:4918)
	at org.eclipse.swt.SWT.error(SWT.java:4833)
	at org.eclipse.swt.SWT.error(SWT.java:4804)
	at org.eclipse.swt.widgets.Widget.error(Widget.java:565)
	at org.eclipse.swt.widgets.Widget.checkWidget(Widget.java:480)
	at org.eclipse.swt.widgets.Widget.getData(Widget.java:591)
	at org.eclipse.jface.viewers.StructuredViewer.associate(StructuredViewer.java:570)
	at org.eclipse.jface.viewers.AbstractTableViewer$VirtualManager.lambda$0(AbstractTableViewer.java:103)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5855)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1529)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1555)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1538)
	at org.eclipse.swt.widgets.Table.checkData(Table.java:289)
	at org.eclipse.swt.widgets.Table.cellDataProc(Table.java:227)
	at org.eclipse.swt.widgets.Display.cellDataProc(Display.java:994)
	at org.eclipse.swt.internal.gtk.GTK.gtk_list_store_remove(Native Method)
	at org.eclipse.swt.widgets.Table.remove(Table.java:2716)
	at org.eclipse.swt.widgets.Table.setItemCount(Table.java:3652)
	at org.eclipse.jface.viewers.TableViewer.doSetItemCount(TableViewer.java:231)
	at org.eclipse.jface.viewers.AbstractTableViewer.internalVirtualRefreshAll(AbstractTableViewer.java:646)
	at org.eclipse.jface.viewers.AbstractTableViewer.internalRefresh(AbstractTableViewer.java:620)
	at org.eclipse.jface.viewers.AbstractTableViewer.internalRefresh(AbstractTableViewer.java:610)
	at org.eclipse.jface.viewers.AbstractTableViewer.lambda$0(AbstractTableViewer.java:572)
	at org.eclipse.jface.viewers.StructuredViewer.preservingSelection(StructuredViewer.java:1398)
	at org.eclipse.jface.viewers.StructuredViewer.preservingSelection(StructuredViewer.java:1359)
	at org.eclipse.jface.viewers.AbstractTableViewer.inputChanged(AbstractTableViewer.java:572)
	at org.eclipse.jface.viewers.ContentViewer.setInput(ContentViewer.java:282)
	at org.eclipse.jface.viewers.StructuredViewer.setInput(StructuredViewer.java:1632)
	at name.abuchen.portfolio.ui.views.panes.AccountTransactionsPane.setInput(AccountTransactionsPane.java:525)
	at name.abuchen.portfolio.ui.editor.InformationPane.setInput(InformationPane.java:221)
	at name.abuchen.portfolio.ui.editor.AbstractFinanceView.setInformationPaneInput(AbstractFinanceView.java:136)
	at name.abuchen.portfolio.ui.views.AccountListView.lambda$5(AccountListView.java:267)
	at org.eclipse.jface.viewers.Viewer$1.run(Viewer.java:151)
	at org.eclipse.jface.util.SafeRunnable$1.run(SafeRunnable.java:129)
	at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:174)
	at org.eclipse.jface.viewers.Viewer.fireSelectionChanged(Viewer.java:148)
	at org.eclipse.jface.viewers.StructuredViewer.updateSelection(StructuredViewer.java:2128)
	at org.eclipse.jface.viewers.StructuredViewer.handleSelect(StructuredViewer.java:1176)
	at org.eclipse.jface.viewers.StructuredViewer$4.widgetSelected(StructuredViewer.java:1205)
	at org.eclipse.jface.util.OpenStrategy.fireSelectionEvent(OpenStrategy.java:263)
	at org.eclipse.jface.util.OpenStrategy$1.handleEvent(OpenStrategy.java:421)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5855)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1529)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:5065)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4517)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.e4.ui.internal.workbench.swt.E4Application.start(E4Application.java:168)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1440)


```
