### ISSUE TITLE
0.26.2 - Erster Aufruf der Asset Allocation führt zu NPE mit GTK 3

### ISSUE THREAD

**Issue by yetipenguin** [buchen/portfolio#719]
Beim Nachstellen von Issue #716 unter Kubuntu 16.04.1 LTS beobachtet:
1. GTK-Version in ini auf 3 umstellen
2. PP starten und direkt auf die Asset Allocation wechseln

Beobachtetes Verhalten:
Es tritt eine NPE auf
Sat Feb 11 11:36:34 CET 2017
Internal Error

org.eclipse.swt.SWTException: Failed to execute runnable (org.eclipse.e4.core.di.InjectionException: java.lang.NullPointerException)
	at org.eclipse.swt.SWT.error(SWT.java:4533)
	at org.eclipse.swt.SWT.error(SWT.java:4448)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4536)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4154)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1121)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1022)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:150)
	at org.eclipse.e4.ui.internal.workbench.swt.E4Application.start(E4Application.java:161)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:673)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:610)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1519)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1492)
Caused by: org.eclipse.e4.core.di.InjectionException: java.lang.NullPointerException
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:65)
	at org.eclipse.e4.ui.internal.di.UIEventObjectSupplier$UIEventHandler$1.run(UIEventObjectSupplier.java:56)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:35)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:182)
	... 20 more
Caused by: java.lang.NullPointerException
	at name.abuchen.portfolio.ui.util.EmbeddedBrowser.refresh(EmbeddedBrowser.java:80)
	at name.abuchen.portfolio.ui.views.taxonomy.PieChartViewer.nodeChange(PieChartViewer.java:47)
	at name.abuchen.portfolio.ui.views.taxonomy.TaxonomyModel.lambda$4(TaxonomyModel.java:338)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at name.abuchen.portfolio.ui.views.taxonomy.TaxonomyModel.fireTaxonomyModelChange(TaxonomyModel.java:338)
	at name.abuchen.portfolio.ui.views.taxonomy.TaxonomyView.notifyModelUpdated(TaxonomyView.java:157)
	at name.abuchen.portfolio.ui.PortfolioPart.onExchangeRatesLoaded(PortfolioPart.java:469)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:55)
	... 23 more

Beim zweiten Aufruf hat es dann funktioniert.

**Comment by buchen** [comment]
Siehe #769
