### ISSUE TITLE
0.26.2 - Eclipse Luna - Asset Allocation und Asset Classes können nicht geladen werden

### ISSUE THREAD

**Issue by yetipenguin** [buchen/portfolio#720]
Da ich mir die Renderingprobleme aus #716 mal selbst anschauen wollte, habe ich meine Entwicklungsumgebung gemäß https://github.com/buchen/portfolio eingerichtet.

Wenn ich das Product nun starte und dann auf die Asset Allocation oder Asset Classes gehe, erhalte ich diesen Stacktrace:

!ENTRY name.abuchen.portfolio.ui 4 0 2017-02-11 12:32:15.311
!MESSAGE Unable to process "ReBalancingViewer#setUseIndirectQuotation()": no actual value was found for the argument "boolean".
!STACK 0
org.eclipse.e4.core.di.InjectionException: Unable to process "ReBalancingViewer#setUseIndirectQuotation()": no actual value was found for the argument "boolean".
	at org.eclipse.e4.core.internal.di.InjectorImpl.reportUnresolvedArgument(InjectorImpl.java:452)
	at org.eclipse.e4.core.internal.di.InjectorImpl.resolveRequestorArgs(InjectorImpl.java:443)
	at org.eclipse.e4.core.internal.di.InjectorImpl.inject(InjectorImpl.java:140)
	at org.eclipse.e4.core.internal.di.InjectorImpl.internalMake(InjectorImpl.java:375)
	at org.eclipse.e4.core.internal.di.InjectorImpl.make(InjectorImpl.java:308)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.make(ContextInjectionFactory.java:186)
	at name.abuchen.portfolio.ui.AbstractFinanceView.make(AbstractFinanceView.java:197)
	at name.abuchen.portfolio.ui.views.taxonomy.TaxonomyView.createBody(TaxonomyView.java:181)
	at name.abuchen.portfolio.ui.AbstractFinanceView.createViewControl(AbstractFinanceView.java:108)
	at name.abuchen.portfolio.ui.PortfolioPart.createView(PortfolioPart.java:515)
	at name.abuchen.portfolio.ui.PortfolioPart.activateView(PortfolioPart.java:494)
	at name.abuchen.portfolio.ui.ClientEditorSidebar$ActivateViewAction.run(ClientEditorSidebar.java:64)
	at name.abuchen.portfolio.ui.Sidebar.select(Sidebar.java:253)
	at name.abuchen.portfolio.ui.Sidebar$Item$2.mouseDown(Sidebar.java:438)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:193)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5227)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1340)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4561)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4151)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1121)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1022)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:150)
	at org.eclipse.e4.ui.internal.workbench.swt.E4Application.start(E4Application.java:161)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:673)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:610)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1519)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1492)

Fehlen mir noch Bibliotheken?

**Comment by buchen** [comment]
Siehe #521 

Mir ist noch total unklar woher dieser Fehler kommt. Er tritt aber anscheinend nur in der Entwicklungsumgebung auf.
