### ISSUE TITLE
Runtime Exception: no actual value was found for the argument ...

### ISSUE THREAD

**Issue by jrahlf** [buchen/portfolio#729]
Seit neuestem fliegt die folgende Exception, wenn das Depot geladen werden soll:

```
Unable to process "StatementOfAssetsView.factory": no actual value was found for the argument "ExchangeRateProviderFactory".

org.eclipse.e4.core.di.InjectionException: Unable to process "StatementOfAssetsView.factory": no actual value was found for the argument "ExchangeRateProviderFactory".
	at org.eclipse.e4.core.internal.di.InjectorImpl.reportUnresolvedArgument(InjectorImpl.java:452)
	at org.eclipse.e4.core.internal.di.InjectorImpl.resolveRequestorArgs(InjectorImpl.java:443)
	at org.eclipse.e4.core.internal.di.InjectorImpl.inject(InjectorImpl.java:140)
	at org.eclipse.e4.core.internal.di.InjectorImpl.internalMake(InjectorImpl.java:375)
	at org.eclipse.e4.core.internal.di.InjectorImpl.make(InjectorImpl.java:294)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.make(ContextInjectionFactory.java:162)
	at name.abuchen.portfolio.ui.PortfolioPart.createView(PortfolioPart.java:519)
	at name.abuchen.portfolio.ui.PortfolioPart.activateView(PortfolioPart.java:502)
	at name.abuchen.portfolio.ui.ClientEditorSidebar$ActivateViewAction.run(ClientEditorSidebar.java:64)
	at name.abuchen.portfolio.ui.Sidebar.select(Sidebar.java:253)
	at name.abuchen.portfolio.ui.ClientEditorSidebar.selectDefaultView(ClientEditorSidebar.java:135)
	at name.abuchen.portfolio.ui.PortfolioPart.createContainerWithViews(PortfolioPart.java:186)
	at name.abuchen.portfolio.ui.PortfolioPart.access$3(PortfolioPart.java:161)
	at name.abuchen.portfolio.ui.PortfolioPart$2.createContainer(PortfolioPart.java:292)
	at name.abuchen.portfolio.ui.PortfolioPart$BuildContainerRunnable.run(PortfolioPart.java:82)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:35)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:182)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4536)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4154)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1121)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1022)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:150)
	at org.eclipse.e4.ui.internal.workbench.swt.E4Application.start(E4Application.java:161)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(java.base@9-internal/Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(java.base@9-internal/NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(java.base@9-internal/DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(java.base@9-internal/Method.java:531)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:673)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:610)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1519)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1492)
```

**Comment by buchen** [comment]
Siehe auch #521

Frage: tritt das auf, wenn Du PP aus der Eclipse IDE heraus startest? (das war bisher der Fall)
Oder startest Du PP ganz normal über den EXE Launcher?


Und: ich sehe bei Dir Java 9. Ich weiß nicht ob Eclipse damit schon kann. Zumindest in der Vergangenheit gab es da Probleme.

**Comment by jrahlf** [comment]
Habe zurück auf openjdk-8 (Ubuntu) gewechselt und seitdem geht es wieder.
Benutze es ohne Eclipse.

**Comment by buchen** [comment]
Ah, okay, mit Java 9 kommen einige Änderungen. Das habe ich mir noch gar nicht angeschaut.
