### ISSUE TITLE
Support für WebKitGtk2

### ISSUE THREAD

**Issue by mgeha** [buchen/portfolio#769]
Hallo zusammen,

auf meiner gentoo Maschine kann ich nur noch WebKitGtk in der Version 2.x installieren, evtl. kann man PP um diesen Support erweitern.

_$ eix webkit-gtk
[I] net-libs/webkit-gtk
     Available versions:  
     (3)    2.4.11-r1(3/25)
     (2)    2.4.11-r200
     (4)    2.16.3(4/37)_

_$ locate libwebkit
/usr/lib64/libwebkit2gtk-4.0.so
/usr/lib64/libwebkit2gtk-4.0.so.37
/usr/lib64/libwebkit2gtk-4.0.so.37.19.6_

**Comment by buchen** [comment]
> auf meiner gentoo Maschine kann ich nur noch WebKitGtk in der Version 2.x installieren, evtl. kann man PP um diesen Support erweitern.

Und die Installation bringt dann nix?


In der PortfolioPerformance.ini Datei zwinge ich auf GTK2, es geht aber auch GTK3. Vielleicht willst du das mal ausprobieren. Einfach die beiden Zeilen entfernen:

```
--launcher.GTK_version
2
```

**Comment by mgeha** [comment]
Hi. Durch die Umstellung verschwinden die Fehler auf der Seite Bestände (bitte libgtk installieren) - die Seite selbst bleibt aber leer.

Beim Starten von PP erhalte ich diese Warnungen und Fehlermeldungen. Evtl. hilft dir das weiter.

Ansonsten scheint alles andere mit GTK3 auch normal zu funktionieren.

```
(Portfolio Performance:19575): Gtk-WARNING **: Negative content width -6 (allocation 1, extents 4x3) while allocating gadget (node toolbar, owner GtkToolbar)

(Portfolio Performance:19575): Gtk-WARNING **: Allocating size to GtkBox 0x7fc6d1ad3750 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?

(Portfolio Performance:19575): Gtk-WARNING **: Negative content width -6 (allocation 1, extents 4x3) while allocating gadget (node toolbar, owner GtkToolbar)

(Portfolio Performance:19575): Gtk-WARNING **: Negative content width -6 (allocation 1, extents 4x3) while allocating gadget (node toolbar, owner GtkToolbar)

(Portfolio Performance:19575): Gtk-WARNING **: Negative content width -6 (allocation 1, extents 4x3) while allocating gadget (node toolbar, owner GtkToolbar)

(Portfolio Performance:19575): Gtk-CRITICAL **: gtk_cell_renderer_set_fixed_size: assertion 'width >= -1 && height >= -1' failed

(Portfolio Performance:19575): Gtk-CRITICAL **: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(Portfolio Performance:19575): Gtk-CRITICAL **: gtk_cell_renderer_set_fixed_size: assertion 'width >= -1 && height >= -1' failed

```

**Comment by michaellass** [comment]
Unter Arch Linux wird das auch zum Problem, da die webkitgtk-Pakete (heißt: Webkit1 für GTK2 und GTK3) entfernt wurden. Es gibt jetzt nur noch webkit2gtk, also Webkit2 für GTK3. Das wirft zwei Probleme auf:

* webkit2gtk gibt es nur für GTK3 (zumindest unter Arch Linux)
  * Die Lösung ist oben beschrieben, Portfolio Performance lässt sich auch mit GTK3 nutzen
* Eclipse benötigt Support für webkit2gtk
  * Das ist aktuell noch ein offener Bug: https://bugs.eclipse.org/bugs/show_bug.cgi?id=516838

Eine weitere Variante wäre xulrunner als SWT Browser Engine zu verwenden, aber die dafür nötige libxpcom.so ist im Firefox nicht mehr enthalten: https://bugs.archlinux.org/task/41171

Bisher habe ich keine funktionierende Variante ohne die Nutzung von verwaisten Webkit1 Paketen gefunden.

**Comment by buchen** [comment]
> Die Lösung ist oben beschrieben, Portfolio Performance lässt sich auch mit GTK3 nutzen

Vermutlich sollte ich mal die Zeile rausnehmen und GTK 3 erlauben.
Anfangs war der GTK3 Port wohl noch so buggy - da bin ich in diverse Probleme reingelaufen.


Ich bin hoffnungsvoll. Es gibt schon einen erste Version für eine Chromium SWT Browser Version. Damit hätte ich nicht nur den selben Browser auf allen Plattformen sondern die Linux Probleme mit dem nachinstallierten sollten auch ein Ende haben:

https://github.com/maketechnology/cefswt

**Comment by michaellass** [comment]
> Vermutlich sollte ich mal die Zeile rausnehmen und GTK 3 erlauben.
Anfangs war der GTK3 Port wohl noch so buggy - da bin ich in diverse Probleme reingelaufen.

Aktuell habe ich unter GTK3 das Problem, dass beim Wechsel zwischen Tabs (also mehreren Portfolio-Dateien oder dem Willkommen-Tab) ein Internal Error geworfen wird:
`org.eclipse.swt.SWTError: No more handles`

Ist dir der schon einmal begegnet? Ich kann ihn i.d.R. einfach schließen und das Programm weiter nutzen.

**Comment by buchen** [comment]
> Ist dir der schon einmal begegnet?

Interessant. Ich nutze die Linux Version selber überhaupt nicht. Nur ab und an mal checke ich unter VMWare das sie einigermassen okay aussieht.

Ich habe gerade mal danach gesucht. Der Fehler scheint häufiger aufzutreten - aber nicht nur mit GTK3, sondern auch auf Windows etc. Mich würde der komplette Stack Trace interessieren.

Ich schaue mal ob ich den in meiner VM nachvollziehen kann.

**Comment by mgeha** [comment]
Evtl. hilft dir der weiter?

```Der Fehlertext
  "No more handles [Unknown Mozilla path (MOZILLA_FIVE_HOME not set)]"
heisst meistens, dass libwebkitgtk installiert werden muss. Unter Ubuntu 14.4 z.B. mit
  sudo apt-get install libwebkitgtk-1.0-0


Details:
org.eclipse.swt.SWTError: No more handles [Unknown Mozilla path (MOZILLA_FIVE_HOME not set)]
	at org.eclipse.swt.SWT.error(SWT.java:4559)
	at org.eclipse.swt.browser.Mozilla.initMozilla(Mozilla.java:2237)
	at org.eclipse.swt.browser.Mozilla.create(Mozilla.java:691)
	at org.eclipse.swt.browser.Browser.<init>(Browser.java:99)
	at name.abuchen.portfolio.ui.util.EmbeddedBrowser.createControl(EmbeddedBrowser.java:49)
	at name.abuchen.portfolio.ui.views.HoldingsPieChartView.createBody(HoldingsPieChartView.java:59)
	at name.abuchen.portfolio.ui.AbstractFinanceView.createViewControl(AbstractFinanceView.java:108)
	at name.abuchen.portfolio.ui.PortfolioPart.createView(PortfolioPart.java:535)
	at name.abuchen.portfolio.ui.PortfolioPart.activateView(PortfolioPart.java:514)
	at name.abuchen.portfolio.ui.ClientEditorSidebar$ActivateViewAction.run(ClientEditorSidebar.java:65)
	at name.abuchen.portfolio.ui.Sidebar.select(Sidebar.java:266)
	at name.abuchen.portfolio.ui.Sidebar$Item$2.mouseDown(Sidebar.java:454)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:193)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5227)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1340)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4561)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4151)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1121)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1022)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:150)
	at org.eclipse.e4.ui.internal.workbench.swt.E4Application.start(E4Application.java:161)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:673)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:610)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1519)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1492)
```

**Comment by buchen** [comment]
Notiz: erste Webgitk2 Implementierung vorhanden: https://bugs.eclipse.org/bugs/show_bug.cgi?id=441568 Ist die in Oxygen verfügbar?

**Comment by michaellass** [comment]
Ich habe endlich den Stack Trace zu dem Fehler gefunden, der mir beim Wechseln von Tabs unter GTK3 begegnet (im Fehlerlog natürlich – da wo er hin gehört :wink: )

```
org.eclipse.swt.SWTError: No more handles
	at org.eclipse.swt.SWT.error(SWT.java:4559)
	at org.eclipse.swt.SWT.error(SWT.java:4448)
	at org.eclipse.swt.SWT.error(SWT.java:4419)
	at org.eclipse.swt.graphics.Cursor.<init>(Cursor.java:173)
	at org.eclipse.swt.widgets.Display.getSystemCursor(Display.java:2688)
	at org.eclipse.e4.ui.workbench.addons.dndaddon.DragAgent.dragFinished(DragAgent.java:157)
	at org.eclipse.e4.ui.workbench.addons.dndaddon.PartDragAgent.dragFinished(PartDragAgent.java:93)
	at org.eclipse.e4.ui.workbench.addons.dndaddon.DnDManager.finishDrag(DnDManager.java:285)
	at org.eclipse.e4.ui.workbench.addons.dndaddon.DnDManager.startDrag(DnDManager.java:252)
	at org.eclipse.e4.ui.workbench.addons.dndaddon.DnDManager$1.dragDetected(DnDManager.java:89)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:128)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5227)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1340)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4561)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4151)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1121)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1022)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:150)
	at org.eclipse.e4.ui.internal.workbench.swt.E4Application.start(E4Application.java:161)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:673)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:610)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1519)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1492)
```

**Comment by t3sec** [comment]
Moin,
da mich das Thema unter Fedora 27 nervt:
ich sponsere einen Bugfix mit insgesamt 50,- EUR aufgesplittet in zwei gleiche Teile - einmal fix für @buchen und der andere Teil für den Ersteller des PR. Kann daher auch komplett @buchen zugehen.
Gezahlt wird per Paypal sobald das automatische Update den Fix beinhaltet.
Hintergrund: Ich schätze und nutze Portfolio Performance und möchte damit meine Wertschätzung ausdrücken und einen Anreiz schaffen, mein Problem mit PP zu beheben. ;-)
Gruß,
Marcus.

**Comment by unclezero** [comment]
Ich würde 50 Franken drauflegen, wenn das hilft.

Coden im erforderlichen Masse kann ich leider nicht.

**Comment by buchen** [comment]
Okay, Okay, es gibt offensichtlich Bedarf 😄 

Erstmal: es scheint gute Nachrichten zu geben. Ich habe gerade mal in den entsprechenden Foren gesucht. Mit Photon Milestone 5 ist der libwebkit2 auch der Default: https://www.eclipse.org/eclipse/news/4.8/M5/#webkit2default

Allerdings: Die Photon Release ist für den *27. Juni* geplant. 😞 


Es gibt wohl "preliminary" support. Den hab ich aber jetzt noch nicht ausprobiert.

Dazu müsste man - wie oben beschrieben - auf GTK3 gehen (i.e. --launcher.GTK_version 2 aus PortfolioPerformance.ini entfernen). Und die Environment Variable ```SWT_WEBKIT2=1``` setzen. Ich kann es jetzt gerade nicht selber ausprobieren - jemand von Euch?

**Comment by michaellass** [comment]
Ich habe es mal kurz getestet, aber mit mäßigem Erfolg:

- Die Graphen, die mit Hilfe von WebKit dargstellt werden, fehlen (leeres weißes Fenster)
- Ich habe weiterhin die "No more handles" Fehler beim Wechseln von Tabs sobald GTK3 verwendet wird
- Von Zeit zu Zeit Segfaults der Java VM

Scheinbar ist die GTK3 Integration noch nicht ganz ausgereift...

**Comment by unclezero** [comment]
Hallo 

Danke für's schnelle Anschauen.
Bei mir treten ähnliche Fehler auf:
- Fenster ist weiss
- beim Beenden kommt im Terminal Java Runtime fatal error:
  A fatal error has been detected by the Java Runtime Environment:


#  SIGSEGV (0xb) at pc=0x00007fe8f5270b3c, pid=6428, tid=0x00007fe990446700
#
# JRE version: OpenJDK Runtime Environment (8.0_162-b12) (build 1.8.0_162-b12)
# Java VM: OpenJDK 64-Bit Server VM (25.162-b12 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [libjavascriptcoregtk-4.0.so.18+0xd73b3c]  WTFCrash+0x1c
#
# Core dump written. Default location: /data/home/Programs/portfolio/core or core.6428
#
# An error report file with more information is saved as:
# /data/home/Programs/portfolio/hs_err_pid6428.log

Gruess

**Comment by unclezero** [comment]
Schön sieht das aus

**Comment by buchen** [comment]
Ich habe für Euch mal eine Build mit *Photon* gebaut:

[PortfolioPerformance-0.30.2-SNAPSHOT-linux.gtk.x86.tar.gz](https://www.dropbox.com/s/k0sjx2hcck16j99/PortfolioPerformance-0.30.2-SNAPSHOT-linux.gtk.x86.tar.gz?dl=0)
[PortfolioPerformance-0.30.2-SNAPSHOT-linux.gtk.x86_64.tar.gz](https://www.dropbox.com/s/ygtu1v1rfva7j95/PortfolioPerformance-0.30.2-SNAPSHOT-linux.gtk.x86_64.tar.gz?dl=0)

Noch tut nicht alles. Die "Bestände" tun. Aber die Kuchendiagramme bei den Klassifikationen ("Donut") werden nur angezeigt, wenn man sie zuletzt geöffnet hatte und dann die Klassifikation noch mal neu anklickt (also z.B. kurz zu der Vermögensaufstellung und zurück). Mir ist noch nicht ganz klar was da schief geht...

Was fällt Euch noch auf?

**Comment by unclezero** [comment]
Toll!

Auf den ersten Blick funktioniert es.

Deine Aussage zum Donut-Diagramm kann ich ebenfalls nachvollziehen.

**Comment by mgeha** [comment]
Dito, kann ich bestätigen, funktioniert bei mir wie beschrieben mit der Einschränkung beim Cops-favrourite Diagramm ^^

**Comment by phobeus81** [comment]
Jawohl! Vielen dank, seit Monaten endlich mal wieder ein Donut :) Beim ersten öffnen wurde er angezeigt und danach ne weiße Seite. Nach erneuten öffnen funktioniert es einwandfrei. Keine Ahnung, was da schief ging (vielleicht weil er gerade parallel noch Kurse abrief?). Ansonsten bisher in keine Probleme reingelaufen. Vielen Dank für das Update!

**Comment by l-ray** [comment]
Das klingt nach richtig guten Neuigkeiten. 
Kannst Du schon sagen, ab welcher Version die Änderungen im Hauptbranch angekommen sind bzw. welche Parameter gesetzt werden muessen um m.H.v. Maven eine  Eclipse Photon M6 Version bauen zu koennen? Ich wuerde das dann direkt in den Packages für RH/Fedora anpasssen (https://copr.fedorainfracloud.org/coprs/lray/PortfolioPerformance/)

**Comment by buchen** [comment]
Ich habe die Änderung (mittlerweile Milestone 7) mal den branch [feature_gtkwebkit2](https://github.com/buchen/portfolio/tree/feature_gtkwebkit2) gepusht. Ich kann gerne jede Release auch in den Branch mergen.

Die Photon Release ist Ende Juni. Wenn alles gut geht, würde ich dann im Juli auf Photon umstellen.

**Comment by michaellass** [comment]
Ich habe eben auch die Version aus dem feature branch gebaut und mit GTK3 als Toolkit funktioniert  der Donut wieder! Auch der "No more handles" Fehler, den ich oben einmal beschrieben hatte, ist damit passé. Klasse! :slightly_smiling_face:

**Comment by buchen** [comment]
FYI Ich habe gerade die version 0.31.1 in den Feature Branch gemergt.
Der Build ging durch - allerdings habe ich jetzt nicht unter Linux getestet.

**Comment by l-ray** [comment]
Dankeschoen - hab eben gebaut und geprueft - sieht auch alles soweit gut aus. 
Die neue Version ist fuer RedHat im o.g. Copr als version `0.31.1-0.1.webkit2` verfuegbar.

**Comment by buchen** [comment]
FYI - jetzt ich haben Version 0.32.0 in den Branch gemergt. Und auf Photon 4.8 RC4 aktualisiert.

**Comment by l-ray** [comment]
Danke - Ist im RedHat/Fedora Copr entsprechend als  `portfolio-performance.x86_64 0.32.0-0.1.webkit2` verfuegbar. Scheint auf dem lokalen Rechner gut zu laufen.

**Comment by unclezero** [comment]
Ich habe das jetzt mal via Fedora Repo installiert.
Funktioniert auf F27 bestens.

Vielen Dank.

**Comment by unclezero** [comment]
@buchen wie kann ich mein Versprechen einlösen?

**Comment by JohannesNeu** [comment]
Version 0.32.0 (linux, x86_64) auf Manjaro funktioniert noch nicht. Es ist die Standardversion von der Website. Sollte sie das mittlerweile?

Im Fehlerprotokoll taucht noch folgendes auf:

![grafik](https://user-images.githubusercontent.com/39328632/41890277-23336ec8-790f-11e8-9184-3ad43fb0dad6.png)

**Comment by buchen** [comment]
> Es ist die Standardversion von der Website. Sollte sie das mittlerweile?

Nein. Aktuell tut der Branch. Und das Fedora Repo das @l-ray baut.

Am 27 Juni wird die Photon Release offiziell freigebe. Ich denke mit der nächsten Version werde ich das auch in den master branch übernehmen.

**Comment by phobeus81** [comment]
Scheint hier eigentlich recht gut zu funktionieren (Fedora 28). Schau mal nach im Ini-File, ob dort noch das explizite setzen des Webkit2 drin ist. Dies war bei mir der Fall und führte zu dem gewohnten Fehler. Als ich dies entfernt habe, war das Problem nicht mehr da. Keine Ahnung, ob dies bei einem Update hätte auch angepasst werden müssen oder eben durch einen vorherigen Versuch es zu reparieren verursacht wurde.

**Comment by JohannesNeu** [comment]
Hi phobeus81, vielen Dank für den Tipp, es lag tatsächlich an einem: "--launcher.GTK_version 2" in der ini.

**Comment by buchen** [comment]
> Hi phobeus81, vielen Dank für den Tipp, es lag tatsächlich an einem: "--launcher.GTK_version 2" in der ini.

😒 Mist. Das habe ich übersehen. Schmeisse ich in der nächsten Version raus.
