### ISSUE TITLE
ArrayIndexOutOfBoundsException bei Heatmap in der Performance-Ansicht

### ISSUE THREAD

**Issue by sebasbaumh** [buchen/portfolio#868]
Beim Aufruf der Performance-Ansicht kommt bei mir diese Exception:
```
-1103
java.lang.ArrayIndexOutOfBoundsException: -1103
	at name.abuchen.portfolio.ui.views.dashboard.PerformanceHeatmapWidget.createCell(PerformanceHeatmapWidget.java:300)
	at name.abuchen.portfolio.ui.views.dashboard.PerformanceHeatmapWidget.fillTable(PerformanceHeatmapWidget.java:282)
	at name.abuchen.portfolio.ui.views.dashboard.PerformanceHeatmapWidget.createControl(PerformanceHeatmapWidget.java:207)
	at name.abuchen.portfolio.ui.views.dashboard.DashboardView.buildDelegate(DashboardView.java:316)
	at name.abuchen.portfolio.ui.views.dashboard.DashboardView.buildColumns(DashboardView.java:275)
	at name.abuchen.portfolio.ui.views.dashboard.DashboardView.selectDashboard(DashboardView.java:432)
	at name.abuchen.portfolio.ui.views.dashboard.DashboardView.createBody(DashboardView.java:255)
	at name.abuchen.portfolio.ui.AbstractFinanceView.createViewControl(AbstractFinanceView.java:108)
	at name.abuchen.portfolio.ui.PortfolioPart.createView(PortfolioPart.java:535)
	at name.abuchen.portfolio.ui.PortfolioPart.activateView(PortfolioPart.java:514)
	at name.abuchen.portfolio.ui.ClientEditorSidebar$ActivateViewAction.run(ClientEditorSidebar.java:65)
	at name.abuchen.portfolio.ui.Sidebar.select(Sidebar.java:266)
	at name.abuchen.portfolio.ui.Sidebar$Item$2.mouseDown(Sidebar.java:454)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:193)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4418)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1079)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4236)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3824)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1121)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1022)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:150)
	at org.eclipse.e4.ui.internal.workbench.swt.E4Application.start(E4Application.java:161)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:673)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:610)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1519)
```

Anscheinend erscheint sie, weil ich das Heatmap-Widget darauf eingeblendet habe.
Mit der Beispiel-DAX-Datei tritt der Fehler beim Hinzufügen des "Monatsrenditen in einer Heatmap"-Widgets auch auf.

**Comment by TSFO27** [comment]
Hallo, denke gleicher Fehler und hoffentlich schon mit #868 gefixt.

`-342

java.lang.ArrayIndexOutOfBoundsException: -342

	at name.abuchen.portfolio.ui.views.dashboard.PerformanceHeatmapWidget.createCell(PerformanceHeatmapWidget.java:308)

	at name.abuchen.portfolio.ui.views.dashboard.PerformanceHeatmapWidget.fillTable(PerformanceHeatmapWidget.java:282)

	at name.abuchen.portfolio.ui.views.dashboard.PerformanceHeatmapWidget.createControl(PerformanceHeatmapWidget.java:207)

	at name.abuchen.portfolio.ui.views.dashboard.DashboardView.buildDelegate(DashboardView.java:316)

	at name.abuchen.portfolio.ui.views.dashboard.DashboardView.buildColumns(DashboardView.java:275)

	at name.abuchen.portfolio.ui.views.dashboard.DashboardView.selectDashboard(DashboardView.java:432)

	at name.abuchen.portfolio.ui.views.dashboard.DashboardView.createBody(DashboardView.java:255)

	at name.abuchen.portfolio.ui.AbstractFinanceView.createViewControl(AbstractFinanceView.java:108)

	at name.abuchen.portfolio.ui.PortfolioPart.createView(PortfolioPart.java:535)

	at name.abuchen.portfolio.ui.PortfolioPart.activateView(PortfolioPart.java:514)

	at name.abuchen.portfolio.ui.ClientEditorSidebar$ActivateViewAction.run(ClientEditorSidebar.java:65)

	at name.abuchen.portfolio.ui.Sidebar.select(Sidebar.java:266)

	at name.abuchen.portfolio.ui.Sidebar$Item$2.mouseDown(Sidebar.java:454)

	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:193)

	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)

	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4418)

	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1079)

	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4236)

	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3824)

	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1121)

	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)

	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1022)

	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:150)

	at org.eclipse.e4.ui.internal.workbench.swt.E4Application.start(E4Application.java:161)

	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)

	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)

	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)

	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)

	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)

	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)

	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)

	at java.lang.reflect.Method.invoke(Unknown Source)

	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:673)

	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:610)

	at org.eclipse.equinox.launcher.Main.run(Main.java:1519)

`

**Comment by sebasbaumh** [comment]
Danke fürs Mergen @buchen.

@TSFO27 das sieht sehr stark nach demselben Problem aus, die Zahlen waren bei mir je nach Anzahl der Kurse auch unterschiedlich. Falls nicht, mach das Ticket einfach nochmal auf.
