### ISSUE TITLE
0.28.0 Kubuntu 14.04.5 LTS ArrayIndexOutOfBoundsException in Performance-Ansicht

### ISSUE THREAD

**Issue by yetipenguin** [buchen/portfolio#873]
Nach dem automatischen Update auf 0.28.0 tritt unter Kubuntu 14.04.5 LTS eine ArrayIndexOutOfBoundsException in der Performance-Ansicht auf. Problem tritt sowohl mit GTK2 als auch mit GTK 3 auf. GUI zurücksetzen hat nichts geholfen.
So wie es aussieht tritt es nur mit einer bestimmten Datei auf, die ich aber nicht veröffentliche möchte.
Ich versuche mal Testdaten zu erzeugen.

Sun Nov 05 23:09:00 CET 2017
-342

java.lang.ArrayIndexOutOfBoundsException: -342
	at name.abuchen.portfolio.ui.views.dashboard.PerformanceHeatmapWidget.createCell(PerformanceHeatmapWidget.java:308)
	at name.abuchen.portfolio.ui.views.dashboard.PerformanceHeatmapWidget.fillTable(PerformanceHeatmapWidget.java:282)
	at name.abuchen.portfolio.ui.views.dashboard.PerformanceHeatmapWidget.createControl(PerformanceHeatmapWidget.java:207)
	at name.abuchen.portfolio.ui.views.dashboard.DashboardView.buildDelegate(DashboardView.java:316)
	at name.abuchen.portfolio.ui.views.dashboard.DashboardView.buildColumns(DashboardView.java:275)
	at name.abuchen.portfolio.ui.views.dashboard.DashboardView.selectDashboard(DashboardView.java:432)
	at name.abuchen.portfolio.ui.views.dashboard.DashboardView.createBody(DashboardView.java:255)
	at name.abuchen.portfolio.ui.AbstractFinanceView.createViewControl(AbstractFinanceView.java:108)
	at name.abuchen.portfolio.ui.PortfolioPart.createView(PortfolioPart.java:535)
	at name.abuchen.portfolio.ui.PortfolioPart.activateView(PortfolioPart.java:514)
	at name.abuchen.portfolio.ui.ClientEditorSidebar$ActivateViewAction.run(ClientEditorSidebar.java:65)
	at name.abuchen.portfolio.ui.Sidebar.select(Sidebar.java:266)
	at name.abuchen.portfolio.ui.Sidebar.selectById(Sidebar.java:275)
	at name.abuchen.portfolio.ui.ClientEditorSidebar.selectDefaultView(ClientEditorSidebar.java:164)
	at name.abuchen.portfolio.ui.PortfolioPart.createContainerWithViews(PortfolioPart.java:197)
	at name.abuchen.portfolio.ui.PortfolioPart.access$3(PortfolioPart.java:163)
	at name.abuchen.portfolio.ui.PortfolioPart$2.createContainer(PortfolioPart.java:303)
	at name.abuchen.portfolio.ui.PortfolioPart$BuildContainerRunnable.run(PortfolioPart.java:84)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:35)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:182)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4536)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4154)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1121)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1022)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:150)
	at org.eclipse.e4.ui.internal.workbench.swt.E4Application.start(E4Application.java:161)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:673)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:610)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1519)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1492)

**Comment by yetipenguin** [comment]
Die Plausibilitätsprüfung meldet auch keine Probleme.

**Comment by norgoe** [comment]
Ich erhalte auch nahezug den gleichen Fehler mit 0.28.0 auf Windows 10 mit meinem seit längerer Zeit gehegten und gepflegten xml:

Mon Nov 06 09:55:33 CET 2017
-343

java.lang.ArrayIndexOutOfBoundsException: -343

	at name.abuchen.portfolio.ui.views.dashboard.PerformanceHeatmapWidget.createCell(PerformanceHeatmapWidget.java:308)

	at name.abuchen.portfolio.ui.views.dashboard.PerformanceHeatmapWidget.fillTable(PerformanceHeatmapWidget.java:282)

	at name.abuchen.portfolio.ui.views.dashboard.PerformanceHeatmapWidget.createControl(PerformanceHeatmapWidget.java:207)

	at name.abuchen.portfolio.ui.views.dashboard.DashboardView.buildDelegate(DashboardView.java:316)

	at name.abuchen.portfolio.ui.views.dashboard.DashboardView.buildColumns(DashboardView.java:275)

	at name.abuchen.portfolio.ui.views.dashboard.DashboardView.selectDashboard(DashboardView.java:432)

	at name.abuchen.portfolio.ui.views.dashboard.DashboardView.createBody(DashboardView.java:255)

	at name.abuchen.portfolio.ui.AbstractFinanceView.createViewControl(AbstractFinanceView.java:108)

	at name.abuchen.portfolio.ui.PortfolioPart.createView(PortfolioPart.java:535)

	at name.abuchen.portfolio.ui.PortfolioPart.activateView(PortfolioPart.java:514)

	at name.abuchen.portfolio.ui.ClientEditorSidebar$ActivateViewAction.run(ClientEditorSidebar.java:65)

	at name.abuchen.portfolio.ui.Sidebar.select(Sidebar.java:266)

	at name.abuchen.portfolio.ui.Sidebar$Item$2.mouseDown(Sidebar.java:454)

	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:193)

	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)

	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4418)

	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1079)

	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4236)

	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3824)

	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1121)

	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)

	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1022)

	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:150)

	at org.eclipse.e4.ui.internal.workbench.swt.E4Application.start(E4Application.java:161)

	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)

	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)

	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)

	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)

	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)

	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)

	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)

	at java.lang.reflect.Method.invoke(Unknown Source)

	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:673)

	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:610)

	at org.eclipse.equinox.launcher.Main.run(Main.java:1519)

**Comment by yetipenguin** [comment]
Mit 0.28.1 ist das Problem bei mir behoben. Vielen Dank für die schnelle Abhilfe!
Und was eigentlich noch wichtiger ist: Unter Linux mit GTK 3 wird nun auch die "Bestand"-Spalte in der Vermögensaufstellung gerendert. :-)
