### ISSUE TITLE
Can't start app on OSX High Sierra

### ISSUE THREAD

**Issue by tobsch** [buchen/portfolio#909]
App crashes with the following stacktrace:

```
!ENTRY name.abuchen.portfolio.bootstrap 2 0 2017-12-04 10:17:55.993
!MESSAGE Could not resolve module: name.abuchen.portfolio.bootstrap [15]
  Unresolved requirement: Import-Package: org.eclipse.e4.core.di.annotations
    -> Export-Package: org.eclipse.e4.core.di.annotations; bundle-version="1.5.0.v20151127-1241"; bundle-symbolic-name="org.eclipse.e4.core.di.annotations"; version="0.0.0"
       org.eclipse.e4.core.di.annotations [59]
         Unresolved requirement: Require-Capability: osgi.ee; filter:="(&(osgi.ee=JavaSE)(version=1.8))"
  Unresolved requirement: Import-Package: org.eclipse.e4.core.contexts
    -> Export-Package: org.eclipse.e4.core.contexts; bundle-version="1.5.1.v20170203-1100"; bundle-symbolic-name="org.eclipse.e4.core.contexts"; version="0.0.0"
       org.eclipse.e4.core.contexts [56]
         Unresolved requirement: Require-Capability: osgi.ee; filter:="(&(osgi.ee=JavaSE)(version=1.8))"
         Unresolved requirement: Require-Bundle: org.eclipse.e4.core.di
           -> Bundle-SymbolicName: org.eclipse.e4.core.di; bundle-version="1.6.1.v20160712-0927"
              org.eclipse.e4.core.di [58]
                Unresolved requirement: Require-Capability: osgi.ee; filter:="(&(osgi.ee=JavaSE)(version=1.8))"
                Unresolved requirement: Require-Bundle: org.eclipse.e4.core.di.annotations; bundle-version="[1.4.0,2.0.0)"; visibility:="reexport"
                  -> Bundle-SymbolicName: org.eclipse.e4.core.di.annotations; bundle-version="1.5.0.v20151127-1241"


!ENTRY org.eclipse.osgi 4 0 2017-12-04 10:17:55.994
!MESSAGE Anwendungsfehler
!STACK 1
java.lang.RuntimeException: Application "org.eclipse.e4.ui.workbench.swt.E4Application" could not be found in the registry. The applications available are: org.eclipse.equinox.app.error, org.eclipse.equinox.p2.garbagecollector.application, org.eclipse.equinox.p2.touchpoint.natives.nativePackageExtractor.
	at org.eclipse.equinox.internal.app.EclipseAppContainer.startDefaultApp(EclipseAppContainer.java:248)
	at org.eclipse.equinox.internal.app.MainApplicationLauncher.run(MainApplicationLauncher.java:29)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:673)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:610)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1519)
```

**Comment by buchen** [comment]
**JDK 8** installed?

On Mac OS X, you need the JDK. The JRE is not enough.

https://forum.portfolio-performance.info/t/installation-auf-macos-10-12-2-nicht-moeglich/345/6

**Comment by tobsch** [comment]
sorry, thanks!
