### ISSUE TITLE
PP blockiert bei Hinzufügen eines Wertpapiers

### ISSUE THREAD

**Issue by gsthys** [buchen/portfolio#968]
Hinzufügen eines Wertpapiers durch Suchen auf Yahoo Finance (hier im Fall nach Staramba):
Effekt: Suche findet nichts und beendet sich aber auch nicht
Button "Abbrechen" und "Übernehmen" sind ausgegraut, der Versuch, über "x" das Fenster zu schliessen, führt zur Meldung "Der Assistent kann auf Grund einer aktiven Operation nicht geschlossen werden. Sie müssen die Operation erst abrechen ..."
Die Aktion wurde ausgeführt, während im Background diverse Kursupdates durchgeführt wurden, wo folgende Fehler im Log auftauchen, wie: java.io.IOException: Downloadfehler bei Versuch 2 für Ticker WDI.DE: Yahoo Crumb nicht gefunden 
Ev. hat das miteinander zu tun ..

**Comment by sebasbaumh** [comment]
Ich habe dazu einen Pull Request #971 angelegt, der die Suche fixt.

**Comment by buchen** [comment]
Ich kann den Fehler bei mir nicht wirklich nachvollziehen. Bei mir tut die Suche auch so. Die Suche tut aber auch mit dem PR #971 bei mir. Wenn damit das Problem behoben wird, dann merge ich die Änderungen rein.

**Comment by gsthys** [comment]
Ev. als Ergänzung: grundsaetzlich tauche bei yahoo recht viele Fehlermeldungen auf:
z.B.:
!MESSAGE Downloadfehler bei Versuch 2 für Ticker MDO.DE: HTTP error fetching URL
!STACK 0
java.io.IOException: Downloadfehler bei Versuch 2 für Ticker MDO.DE: HTTP error fetching URL
        at name.abuchen.portfolio.online.impl.YahooFinanceQuoteFeed.internalGetQuotes(YahooFinanceQuoteFeed.java:250)
        at name.abuchen.portfolio.online.impl.YahooFinanceQuoteFeed.updateHistoricalQuotes(YahooFinanceQuoteFeed.java:178)
        at name.abuchen.portfolio.ui.UpdateQuotesJob$2.run(UpdateQuotesJob.java:267)
        at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
Caused by: org.jsoup.HttpStatusException: HTTP error fetching URL. Status=404, URL=https://query1.finance.yahoo.com/v7/finance/download/MDO.DE?period1=1525816800&period2=1525903200&interval=1d&events=history&crumb=x2yWM7VRsIL
        at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:537)
        at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:493)
        at org.jsoup.helper.HttpConnection.execute(HttpConnection.java:205)
        at name.abuchen.portfolio.online.impl.YahooFinanceQuoteFeed.requestData(YahooFinanceQuoteFeed.java:300)
        at name.abuchen.portfolio.online.impl.YahooFinanceQuoteFeed.internalGetQuotes(YahooFinanceQuoteFeed.java:243)
        ... 3 more
-----
wenn man den Link im Browser eingibt, dann bekommt man folgenden Fehler angezeigt:
{
    "finance": {
        "error": {
            "code": "Unauthorized",
            "description": "Invalid cookie"
        }
    }
}
Gruesse,

**Comment by sebasbaumh** [comment]
Witzigerweise ist mir das aufgefallen, als ich einem Freund das tolle Programm zeigen wollte und ein Wertpapier hinzufügen wollte ;-)

Ansonsten ist Yahoo leider momentan weniger brauchbar, da es eben oft die Fehlermeldungen bei den Kursen gibt.
@gsthys probiere mal Alpha Vantage als Kursquelle aus.
